/*------------------------------------------------------------
The AABB is a Bounding Volume used 
in the Killer Collision engine. 

Uses the boost test library.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.


Written by Maxwell Miller
-------------------------------------------------------------*/

#include <boost/test/unit_test.hpp>
#include <Engine/Atom.h>
#include <Engine/Menu.h>
#include <Engine/Point.h>
#include <Engine/Text.h>
#include <Boxes/Box.h>

namespace KE = KillerEngine;
namespace KM = KillerMath;

class MenuSelector : public KE::GameObject
{
public:
	MenuSelector(void)
	{  }

	~MenuSelector(void)
	{  }

	void v_Update(void)
	{  }
};

BOOST_AUTO_TEST_CASE(MenuConstructorAndAccessors)
{
	KE::Menu menu{ };

	menu.SetPosition(KM::Point(50.0f, 100.0f));

	BOOST_CHECK_EQUAL(menu.GetPosition()[x], 50.0f);
	BOOST_CHECK_EQUAL(menu.GetPosition()[y], 100.0f);

	menu.SetItemOffset(KM::Point(0.0f, 25.0f));
	
	BOOST_CHECK_EQUAL(menu.GetItemOffset()[x], 0.0f);
	BOOST_CHECK_EQUAL(menu.GetItemOffset()[y], 25.0f);	

	menu.SetOffsetFromTitle(KM::Point(0.0f, 50.0f));

	BOOST_CHECK_EQUAL(menu.GetOffsetFromTitle()[x], 0.0f);
	BOOST_CHECK_EQUAL(menu.GetOffsetFromTitle()[y], 50.0f);
}

bool menuItem1ActionStatus = false;

void MenuItem1Action(void)
{
	menuItem1ActionStatus = true;
}

BOOST_AUTO_TEST_CASE(MenuItemAddRemove)
{
	KE::Menu menu { };

	menu.SetPosition(0.0f, -100.0f);
	menu.SetItemOffset(10.0f, -25.0f);
	menu.SetSelectorOffset(-10.0f, 0.0f);
	
	KE::MenuItem item1 { };
	item1.text = KE::Text("Item1");

	menu.AddItem(item1);

	BOOST_CHECK_EQUAL(menu.GetTotalItems(), 1);

	KE::MenuItem item2 { };
	item2.text = KE::Text("Item2");

	menu.AddItem(item2);

	BOOST_CHECK_EQUAL(menu.GetTotalItems(), 2);

//ToDo: Test Positions

	menu.RemoveItem(1);

	BOOST_CHECK_EQUAL(menu.GetTotalItems(), 1);

	menu.RemoveItem(1);

	BOOST_CHECK_EQUAL(menu.GetTotalItems(), 1);

	menu.RemoveItem(0);

	BOOST_CHECK_EQUAL(menu.GetTotalItems(), 0);	
}

BOOST_AUTO_TEST_CASE(MenuItemSelector)
{
	KE::Menu menu { };

	menu.SetPosition(0.0f, -100.0f);
	menu.SetItemOffset(10.0f, -25.0f);
	menu.SetSelectorOffset(-10.0f, 0.0f);
	
	KE::MenuItem item1 { };
	item1.text = KE::Text("Item1");
	item1.Action = &MenuItem1Action;

	KE::MenuItem item2 { };
	item2.text = KE::Text("Item2");

	menu.AddItem(item1);
	menu.AddItem(item2);

	MenuSelector selector { };
	selector.SetActive(false);

	//Failing because of openGL code... look into it. 
	//Consider not calling openGL code in GameObject Constructors. 
	//menu.SetSelector(shared_ptr<KE::GameObject>(&selector));
}