#pragma once

//=====Engine includes=====
#include <Engine/Atom.h>
#include <Engine/Texture.h>
#include <Engine/CharacterData.h>
#include <Engine/TextureManager.h>

#include <Extern/rapidxml.hpp>

//=====STL includes=====
#include <fstream>
#include <sstream>
#include <vector>
#include <map>
#include <list>
#include <memory>

namespace KillerEngine
{
//==========================================================================================================================
//Documentation
//==========================================================================================================================
/*! The Font class is used to open a .fnt file, extract the needed character data, and then save that for text processing 
	later on.
	
	CreateCharacter is a CharSprite Factory. This may be important to know. */
	class Font
	{
	public:
//==========================================================================================================================
//
//Constructors
//
//==========================================================================================================================
/*! Default Constructor. No special actions taken. */
		Font(void);

/*! Copy Constructor. Calls GetTextureID(), GetFile() and GetName(). 
	\param f Font&: Font to be copied.*/
		Font(const Font& f);

/*! Copy Constructor. Calls GetTextureID(), GetFile() and GetName(). 
	\param f Font*: Font to be copied.*/
		Font(const Font* f);

//==========================================================================================================================
//
//Font Functions
//
//==========================================================================================================================
/*! Initializes all data needed to be able to create RenderedCharacters as part of a RenderedText. Set's the fontName name, 
	which is currently not used. Later this will be used with a manager to class to find the font you need. Opens fontFile, 
	parses the file and extracts the needed character data. The only currently supported file format is a .fnt file. This 
	class has only been tested with .fnt files generated by BMFont tool found at http://www.angelcode.com/products/bmfont/
	\param fontName string. Name of the font you are creating.
	\param fontFile string. File Path to the .fnt file that is used to get the character data needed. */
		void InitFont(string fontName, string filePath);

//==========================================================================================================================
//
//Operators
//
//==========================================================================================================================
/*! Copies Font pointer. Calls GetTextureID(), GetFile(), GetName() and GetCharacterData(). */
		Font& operator=(const Font* font);

/*! Copies Font reference. Calls GetTextureID(), GetFile(), GetName() and GetCharacterData(). */
		Font& operator=(const Font& font);

//==========================================================================================================================
//
//Accessors
//
//==========================================================================================================================
/*! Set's the name of font. Not used actively in any major way.
	\param fontName string: New name of the font. */
		inline void SetName(string fontName)
		{
			_fontName = fontName; 
		}

/*! Returns the current name of the font. Not used in any major way. */		
		inline const string GetName(void) const
		{
			return _fontName; 
		}

/*! Returns the current texture ID for the texture. */		
		inline const Texture& GetTexture(void) const
		{
			return  _texture; 
		}

		inline void SetTexture(const Texture& tex)
		{
			_texture = tex;
		}

/*! Returns the map containing all data for all characters found in the loaded font. The ID of each character is found in 
	the .fnt file and is the ASCII int value of a char */
		inline std::map<U32, CharacterData> GetCharacterData(void) const
		{ 
			return _characterData; 
		}

		CharacterData GetCharacterData(char c);

	private:
//==========================================================================================================================
//
//Data
//
//==========================================================================================================================	
		Texture 					 _texture; 				///< ID for Texture loaded into the TextureManager.
		string  					 _fontName;				///< Name of the font. Not really used right now.
		std::map<U32, CharacterData> _characterData;			///< All data from .fnt file stored in a RenderText can use for placement.


	};
}