#pragma once

//=====Engine Includes=====
#include "stdafx.h"
#include <Engine/Atom.h>

namespace Tempest
{
    enum TEMPEST_API Keys
    {
        NO_KEY, 			
        A,					
        B,					
        C,					
        D,					
        E,					
        F,					
        G,					
        H,					
        I,					
        J,					
        K,					
        L,					
        M,					
        N,					
        O,					
        P,					
        Q,					
        R,					
        S,					
        T,					
        U,					
        V,					
        W,					
        X,					
        Y,					
        Z,					
        UP_ARROW,			
        DOWN_ARROW,			
        LEFT_ARROW,			
        RIGHT_ARROW,		
        ZERO,				
        ONE,				
        TWO,				
        THREE,				
        FOUR,				
        FIVE,				
        SIX,				
        SEVEN,				
        EIGHT,				
        NINE,				
        MINUS,				
        EQUAL,				
        SPACE,				
        ESCAPE,				
        TAB,				
        LSHIFT,				
        RSHIFT,				
        ENTER,				
        RIGHT_MOUSE,		
        LEFT_MOUSE,			
        MIDDLE_MOUSE,		
        F1,					
        F2,					
        F3,					
        F4,					
        F5,					
        F6,					
        F7,					
        F8,					
        F9,					
        F10,				
        F11,				
        TOTAL_KEYS			
    };
}