.TH "__GLXEvent" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGLXPbufferClobberEvent\fP \fBglxpbufferclobber\fP"
.br
.ti -1c
.RI "long \fBpad\fP [24]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
