.TH "_EAXEXCLUSIONPROPERTIES" 3 "Sat Jun 15 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_EAXEXCLUSIONPROPERTIES
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBlExclusion\fP"
.br
.ti -1c
.RI "float \fBflExclusionLFRatio\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
