.TH "_EAXREVERBPROPERTIES" 3 "Mon Mar 2 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_EAXREVERBPROPERTIES
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBulEnvironment\fP"
.br
.ti -1c
.RI "float \fBflEnvironmentSize\fP"
.br
.ti -1c
.RI "float \fBflEnvironmentDiffusion\fP"
.br
.ti -1c
.RI "long \fBlRoom\fP"
.br
.ti -1c
.RI "long \fBlRoomHF\fP"
.br
.ti -1c
.RI "long \fBlRoomLF\fP"
.br
.ti -1c
.RI "float \fBflDecayTime\fP"
.br
.ti -1c
.RI "float \fBflDecayHFRatio\fP"
.br
.ti -1c
.RI "float \fBflDecayLFRatio\fP"
.br
.ti -1c
.RI "long \fBlReflections\fP"
.br
.ti -1c
.RI "float \fBflReflectionsDelay\fP"
.br
.ti -1c
.RI "\fBEAXVECTOR\fP \fBvReflectionsPan\fP"
.br
.ti -1c
.RI "long \fBlReverb\fP"
.br
.ti -1c
.RI "float \fBflReverbDelay\fP"
.br
.ti -1c
.RI "\fBEAXVECTOR\fP \fBvReverbPan\fP"
.br
.ti -1c
.RI "float \fBflEchoTime\fP"
.br
.ti -1c
.RI "float \fBflEchoDepth\fP"
.br
.ti -1c
.RI "float \fBflModulationTime\fP"
.br
.ti -1c
.RI "float \fBflModulationDepth\fP"
.br
.ti -1c
.RI "float \fBflAirAbsorptionHF\fP"
.br
.ti -1c
.RI "float \fBflHFReference\fP"
.br
.ti -1c
.RI "float \fBflLFReference\fP"
.br
.ti -1c
.RI "float \fBflRoomRolloffFactor\fP"
.br
.ti -1c
.RI "unsigned long \fBulFlags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
