.TH "BDF_PropertyRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BDF_PropertyRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BDF_PropertyType \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   const char * \fBatom\fP"
.br
.ti -1c
.RI "   FT_Int32 \fBinteger\fP"
.br
.ti -1c
.RI "   FT_UInt32 \fBcardinal\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
