.TH "Boxes::Projectile" 3 "Mon Jun 24 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boxes::Projectile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerEngine::GameObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBv_Update\fP (void)"
.br
.ti -1c
.RI "void \fBSetMaxDistance\fP (\fBF32\fP dist)"
.br
.ti -1c
.RI "\fBF32\fP \fBGetMaxDistance\fP (void)"
.br
.ti -1c
.RI "void \fBSetSpeedScale\fP (\fBF32\fP scale)"
.br
.ti -1c
.RI "\fBF32\fP \fBGetSpeedScale\fP (void)"
.br
.ti -1c
.RI "void \fBSetType\fP (ProjectileType type)"
.br
.ti -1c
.RI "ProjectileType \fBGetType\fP (void)"
.br
.ti -1c
.RI "void \fBAddScaledVelocity\fP (const \fBKM::Vector4\fP &vec, \fBF32\fP scale)"
.br
.ti -1c
.RI "KP::p_RigidBody2D \fBGetRigidBody\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBF32\fP \fB_maxDistance\fP"
.br
.ti -1c
.RI "\fBF32\fP \fB_sqrDistance\fP"
.br
.ti -1c
.RI "\fBF32\fP \fB_speedScale\fP"
.br
.ti -1c
.RI "\fBKM::Point\fP \fB_startingLocation\fP"
.br
.ti -1c
.RI "ProjectileType \fB_type\fP"
.br
.ti -1c
.RI "KP::p_RigidBody2D \fBp_rigidBody\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
