.TH "Boxes::Payload" 3 "Tue Jun 4 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boxes::Payload
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKP::Particle\fP \fBparticle\fP"
.br
.ti -1c
.RI "\fBF32\fP \fBtimeAlive\fP"
.br
.ti -1c
.RI "\fBU32\fP \fBspawnNewRule\fP"
.br
.ti -1c
.RI "bool \fBspawnNew\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
