.TH "Boxes::Box" 3 "Sat Jun 15 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boxes::Box
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerEngine::GameObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBox\fP (const \fBKM::Point\fP &pos, \fBF32\fP width, \fBF32\fP height)"
.br
.ti -1c
.RI "\fBBox\fP (const \fBKM::Point\fP &pos, \fBF32\fP width, \fBF32\fP height, const \fBKE::Color\fP &col)"
.br
.ti -1c
.RI "\fBBox\fP (const \fBKM::Point\fP &pos, \fBF32\fP width, \fBF32\fP height, const \fBKE::Color\fP &col, shared_ptr< \fBKE::Texture\fP > texture)"
.br
.ti -1c
.RI "void \fBv_Update\fP (void)"
.br
.ti -1c
.RI "bool \fBOverlapCheck\fP (const shared_ptr< \fBBox\fP > other)"
.br
.ti -1c
.RI "void \fBOnCollide\fP (void)"
.br
.ti -1c
.RI "void \fBSetSpeed\fP (\fBF32\fP s)"
.br
.ti -1c
.RI "\fBF32\fP \fBGetSpeed\fP (void) const"
.br
.ti -1c
.RI "void \fBSetDirection\fP (const \fBKM::Vector4\fP &dir)"
.br
.ti -1c
.RI "void \fBSetDirection\fP (\fBF32\fP x, \fBF32\fP y)"
.br
.ti -1c
.RI "const \fBKM::Vector4\fP & \fBGetDirection\fP (void) const"
.br
.ti -1c
.RI "const \fBKC::AABB\fP & \fBGetBounding\fP (void) const"
.br
.ti -1c
.RI "void \fBInitBounding\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBF32\fP \fB_speed\fP"
.br
.ti -1c
.RI "\fBKM::Vector4\fP \fB_direction\fP"
.br
.ti -1c
.RI "\fBKC::AABB\fP \fB_boundingBox\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
