.TH "Boxes::MovingBoxes" 3 "Sat Jun 1 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boxes::MovingBoxes
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerEngine::Level\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBv_InitLevel\fP (\fBU32\fP id, \fBS32\fP w, \fBS32\fP h, const \fBKE::Color\fP &c)"
.br
.ti -1c
.RI "void \fBv_Update\fP (void)"
.br
.ti -1c
.RI "void \fBCheckBoxEdge\fP (\fBKE::GameObject\fP &b)"
.br
.ti -1c
.RI "void \fBCheckCollisions\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBF32\fP \fB_left\fP"
.br
.ti -1c
.RI "\fBF32\fP \fB_right\fP"
.br
.ti -1c
.RI "\fBF32\fP \fB_bottom\fP"
.br
.ti -1c
.RI "\fBF32\fP \fB_top\fP"
.br
.ti -1c
.RI "\fBBox\fP \fB_redbox\fP"
.br
.ti -1c
.RI "\fBBox\fP \fB_bluebox\fP"
.br
.ti -1c
.RI "\fBBox\fP \fB_greenbox\fP"
.br
.ti -1c
.RI "\fBKE::Text\fP \fB_levelTitle\fP"
.br
.ti -1c
.RI "\fBBox\fP * \fB_activeBox\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void MovingBoxes::v_InitLevel (\fBU32\fP id, \fBS32\fP w, \fBS32\fP h, const \fBKE::Color\fP & c)\fC [virtual]\fP"
Abstract function\&. Used to Initialize the default values, instantiate any objects that will be used and generally get things ready to go\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP is the ID used in the LevelManager\&. 
.br
\fIw\fP is the width of the Level\&. 
.br
\fIh\fP is the height of the Level\&. 
.RE
.PP

.PP
Implements \fBKillerEngine::Level\fP\&.
.SS "void MovingBoxes::v_Update (void)\fC [virtual]\fP"
Abstract function\&. Used to control what needs to happen during an update\&. Please note, objects added to the level are already being updated as part of Level::UpdateLevel\&. 
.PP
Implements \fBKillerEngine::Level\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
