.TH "Boxes::MainMenu" 3 "Sat Jun 15 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boxes::MainMenu
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerEngine::Level\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBv_Init\fP (void) final"
.br
.ti -1c
.RI "void \fBv_Update\fP (void) final"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "p_Box \fB_selector\fP"
.br
.ti -1c
.RI "\fBKE::Menu\fP \fB_menu\fP"
.br
.ti -1c
.RI "\fBKE::Font\fP \fB_menuItemFont\fP"
.br
.ti -1c
.RI "\fBKE::Text\fP \fB_mainTitle\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void MainMenu::v_Init (void)\fC [final]\fP, \fC [virtual]\fP"
Abstract function\&. Used to Initialize the default values, instantiate any objects that will be used and generally get things ready to go\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP is the ID used in the LevelManager\&. 
.br
\fIw\fP is the width of the Level\&. 
.br
\fIh\fP is the height of the Level\&. 
.RE
.PP

.PP
Implements \fBKillerEngine::Level\fP\&.
.SS "void MainMenu::v_Update (void)\fC [final]\fP, \fC [virtual]\fP"
Abstract function\&. Used to control what needs to happen during an update\&. Please note, objects added to the level are already being updated as part of Level::UpdateLevel\&. 
.PP
Implements \fBKillerEngine::Level\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
