.TH "Boxes::Cannon" 3 "Tue Jun 4 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boxes::Cannon
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerEngine::GameObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBv_Update\fP (void)"
.br
.ti -1c
.RI "void \fBFire\fP (const \fBKM::Vector4\fP &heading, shared_ptr< \fBProjectile\fP > projectile, ProjectileType type)"
.br
.ti -1c
.RI "void \fBSetMovementSpeed\fP (\fBF32\fP speed)"
.br
.ti -1c
.RI "\fBF32\fP \fBGetMovementSpeed\fP (void) const"
.br
.ti -1c
.RI "void \fBSetBottomBoundary\fP (\fBF32\fP boundary)"
.br
.ti -1c
.RI "\fBF32\fP \fBGetBottomBoundary\fP (void) const"
.br
.ti -1c
.RI "void \fBSetTopBoundary\fP (\fBF32\fP boundary)"
.br
.ti -1c
.RI "\fBF32\fP \fBGetTopBoundary\fP (void) const"
.br
.ti -1c
.RI "void \fBSetUpDirection\fP (const \fBKM::Vector4\fP &direction)"
.br
.ti -1c
.RI "const \fBKM::Vector4\fP & \fBGetUpDirection\fP (void) const"
.br
.ti -1c
.RI "void \fBSetDownDirection\fP (const \fBKM::Vector4\fP &direction)"
.br
.ti -1c
.RI "const \fBKM::Vector4\fP & \fBGetDownDirection\fP (void) const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBF32\fP \fB_movementSpeed\fP"
.br
.ti -1c
.RI "\fBF32\fP \fB_bottomBoundary\fP"
.br
.ti -1c
.RI "\fBF32\fP \fB_topBoundary\fP"
.br
.ti -1c
.RI "\fBKM::Vector4\fP \fB_upDirection\fP"
.br
.ti -1c
.RI "\fBKM::Vector4\fP \fB_downDirection\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
