.TH "Boxes::Cube" 3 "Wed May 15 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boxes::Cube
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerEngine::GameObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBv_Update\fP (void)"
.br
.ti -1c
.RI "void \fBInitCube\fP (string meshFilePath)"
.br
.ti -1c
.RI "void \fBInitCube\fP (string meshFilePath, \fBU32\fP shaderID)"
.br
.ti -1c
.RI "void \fBInitCube\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fB_rotateRight\fP"
.br
.ti -1c
.RI "bool \fB_rotateLeft\fP"
.br
.ti -1c
.RI "bool \fB_rotateUp\fP"
.br
.ti -1c
.RI "bool \fB_rotateDown\fP"
.br
.ti -1c
.RI "\fBF32\fP \fB_angle\fP"
.br
.ti -1c
.RI "\fBU32\fP \fB_defaultShaderID\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
