.TH "Boxes::ProjectFactory" 3 "Sat Jun 15 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boxes::ProjectFactory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "p_Box \fBMakeBox\fP (void)"
.br
.ti -1c
.RI "p_Cannon \fBMakeCannon\fP (void)"
.br
.ti -1c
.RI "p_Projectile \fBMakeProjectile\fP (void)"
.br
.ti -1c
.RI "p_Cube \fBMakeCube\fP (void)"
.br
.ti -1c
.RI "p_Firework \fBMakeFirework\fP (void)"
.br
.ti -1c
.RI "p_Payload \fBMakePayload\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static p_ProjectFactory \fBInstance\fP (void)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static p_ProjectFactory \fB_instance\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
