.TH "bug" 3 "Mon Feb 4 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBMember \fBKillerMath::Matrix::AddRotateX\fP (F32 val)\fP" 1c
Completely untested and probably not working at all\&.  
.IP "\fBMember \fBKillerMath::Matrix::AddRotateY\fP (F32 val)\fP" 1c
Completely untested and probably not working at all\&.  
.IP "\fBMember \fBKillerMath::Matrix::AddRotateZ\fP (F32 val)\fP" 1c
Completely untested and probably not working at all\&.  
.IP "\fBMember \fBKillerMath::Matrix::AddRotation\fP (F32 xVal, F32 yVal, F32 zVal)\fP" 1c
Not working at all\&. The math is wrong, and rotations are not working in general\&.  
.IP "\fBMember \fBKillerMath::Matrix::SetRotate\fP (F32 xVal, F32 yVal, F32 zVal)\fP" 1c
Not working at all\&. The math is wrong, and rotations are not working in general\&.  
.IP "\fBMember \fBKillerMath::Matrix::SetRotateX\fP (F32 val)\fP" 1c
This is not working at all\&.  
.IP "\fBMember \fBKillerMath::Matrix::SetRotateY\fP (F32 val)\fP" 1c
This is not working at all\&.  
.IP "\fBMember \fBKillerMath::Matrix::SetRotateZ\fP (F32 val)\fP" 1c
This is not working at all\&.  
.IP "\fBMember \fBKillerMath::Quaternion::Negate\fP (void)\fP" 1c
This should be changed to be the - operator\&. Multiplies all elements of this \fBQuaternion\fP by -1\&. 
.PP

