.TH "buttons" 3 "Thu Aug 9 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
buttons
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_1\fP   0"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_2\fP   1"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_3\fP   2"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_4\fP   3"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_5\fP   4"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_6\fP   5"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_7\fP   6"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_8\fP   7"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_LAST\fP   GLFW_MOUSE_BUTTON_8"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_LEFT\fP   GLFW_MOUSE_BUTTON_1"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_RIGHT\fP   GLFW_MOUSE_BUTTON_2"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_MIDDLE\fP   GLFW_MOUSE_BUTTON_3"
.br
.in -1c
.SH "Detailed Description"
.PP 
See \fBmouse button input\fP for how these are used\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
