.TH "CID_FaceDictRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CID_FaceDictRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPS_PrivateRec\fP \fBprivate_dict\fP"
.br
.ti -1c
.RI "FT_UInt \fBlen_buildchar\fP"
.br
.ti -1c
.RI "FT_Fixed \fBforcebold_threshold\fP"
.br
.ti -1c
.RI "FT_Pos \fBstroke_width\fP"
.br
.ti -1c
.RI "FT_Fixed \fBexpansion_factor\fP"
.br
.ti -1c
.RI "FT_Byte \fBpaint_type\fP"
.br
.ti -1c
.RI "FT_Byte \fBfont_type\fP"
.br
.ti -1c
.RI "\fBFT_Matrix\fP \fBfont_matrix\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBfont_offset\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_subrs\fP"
.br
.ti -1c
.RI "FT_ULong \fBsubrmap_offset\fP"
.br
.ti -1c
.RI "FT_Int \fBsd_bytes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
