.TH "CID_FaceInfoRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CID_FaceInfoRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_String * \fBcid_font_name\fP"
.br
.ti -1c
.RI "FT_Fixed \fBcid_version\fP"
.br
.ti -1c
.RI "FT_Int \fBcid_font_type\fP"
.br
.ti -1c
.RI "FT_String * \fBregistry\fP"
.br
.ti -1c
.RI "FT_String * \fBordering\fP"
.br
.ti -1c
.RI "FT_Int \fBsupplement\fP"
.br
.ti -1c
.RI "PS_FontInfoRec \fBfont_info\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBfont_bbox\fP"
.br
.ti -1c
.RI "FT_ULong \fBuid_base\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_xuid\fP"
.br
.ti -1c
.RI "FT_ULong \fBxuid\fP [16]"
.br
.ti -1c
.RI "FT_ULong \fBcidmap_offset\fP"
.br
.ti -1c
.RI "FT_Int \fBfd_bytes\fP"
.br
.ti -1c
.RI "FT_Int \fBgd_bytes\fP"
.br
.ti -1c
.RI "FT_ULong \fBcid_count\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_dicts\fP"
.br
.ti -1c
.RI "\fBCID_FaceDict\fP \fBfont_dicts\fP"
.br
.ti -1c
.RI "FT_ULong \fBdata_offset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
