.TH "DefinedObject3D" 3 "Mon Jun 24 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefinedObject3D
.SH SYNOPSIS
.br
.PP
.PP
Inherits GameObject3D\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBv_Update\fP (void)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
