.TH "EFXEAXREVERBPROPERTIES" 3 "Tue Jun 4 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EFXEAXREVERBPROPERTIES
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBflDensity\fP"
.br
.ti -1c
.RI "float \fBflDiffusion\fP"
.br
.ti -1c
.RI "float \fBflGain\fP"
.br
.ti -1c
.RI "float \fBflGainHF\fP"
.br
.ti -1c
.RI "float \fBflGainLF\fP"
.br
.ti -1c
.RI "float \fBflDecayTime\fP"
.br
.ti -1c
.RI "float \fBflDecayHFRatio\fP"
.br
.ti -1c
.RI "float \fBflDecayLFRatio\fP"
.br
.ti -1c
.RI "float \fBflReflectionsGain\fP"
.br
.ti -1c
.RI "float \fBflReflectionsDelay\fP"
.br
.ti -1c
.RI "float \fBflReflectionsPan\fP [3]"
.br
.ti -1c
.RI "float \fBflLateReverbGain\fP"
.br
.ti -1c
.RI "float \fBflLateReverbDelay\fP"
.br
.ti -1c
.RI "float \fBflLateReverbPan\fP [3]"
.br
.ti -1c
.RI "float \fBflEchoTime\fP"
.br
.ti -1c
.RI "float \fBflEchoDepth\fP"
.br
.ti -1c
.RI "float \fBflModulationTime\fP"
.br
.ti -1c
.RI "float \fBflModulationDepth\fP"
.br
.ti -1c
.RI "float \fBflAirAbsorptionGainHF\fP"
.br
.ti -1c
.RI "float \fBflHFReference\fP"
.br
.ti -1c
.RI "float \fBflLFReference\fP"
.br
.ti -1c
.RI "float \fBflRoomRolloffFactor\fP"
.br
.ti -1c
.RI "int \fBiDecayHFLimit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
