.TH "C:/Projects/Killer_Engine/Headers/Engine/ErrorManager.h" 3 "Sat Jul 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/Killer_Engine/Headers/Engine/ErrorManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <Engine/Atom\&.h>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKillerEngine::ErrorManager\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBKillerEngine::ErrorCode\fP { \fBKillerEngine::EC_NoError\fP = 0, \fBKillerEngine::EC_Unknown\fP, \fBKillerEngine::EC_Game\fP, \fBKillerEngine::EC_Engine\fP, \fBKillerEngine::EC_Physics\fP, \fBKillerEngine::EC_Windows\fP, \fBKillerEngine::EC_OpenGL\fP, \fBKillerEngine::EC_OpenGL_Shader\fP, \fBKillerEngine::EC_DirectInput\fP, \fBKillerEngine::EC_TextureManager\fP, \fBKillerEngine::EC_GameObject\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBKillerEngine::ErrorCode\fP"
Error codes that are used to give a hint as to where to code that is throwing the error is written\&. These are disaplyed to the user in a pop up window when the end application is run\&. These are paired with a more detailed message when the end error is set\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEC_NoError \fP\fP
Default value\&. Shouldn't ever be used\&. 
.TP
\fB\fIEC_Unknown \fP\fP
Fall through code, indicates an error in the setting of an error\&. 
.TP
\fB\fIEC_Game \fP\fP
Indicates the error is in the end application, or the game, not the engine\&. 
.TP
\fB\fIEC_Engine \fP\fP
Indicates the error is in the engine's main code, not very specific\&. 
.TP
\fB\fIEC_Physics \fP\fP
Indicates the error is in the KillerPhysics namespace\&. 
.TP
\fB\fIEC_Windows \fP\fP
Indicates that the error is related to the windowing system\&. 
.TP
\fB\fIEC_OpenGL \fP\fP
Indicates that the error is in OpenGL related code\&. 
.TP
\fB\fIEC_OpenGL_Shader \fP\fP
Indicates that the error is caused by OpenGL shader compilation\&. 
.TP
\fB\fIEC_DirectInput \fP\fP
Depricated\&. Indicates that the error is with the DirectInput setup\&. 
.TP
\fB\fIEC_TextureManager \fP\fP
Indicates that the error occured when trying to load a texture into memory\&. 
.TP
\fB\fIEC_GameObject \fP\fP
Indicates that the issue is in a game object specifically\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
