.TH "C:/Projects/Killer_Engine/Headers/Engine/ErrorManager.h" 3 "Sun Jan 13 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Projects/Killer_Engine/Headers/Engine/ErrorManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <Engine/Atom\&.h>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKillerEngine::ErrorManager\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBKillerEngine::ErrorCode\fP { \fBKillerEngine::NOT_ERROR\fP, \fBKillerEngine::UNKNOWN_ERROR\fP, \fBAPPLICATION\fP, \fBKillerEngine::ENGINE\fP, \fBKillerEngine::PHYSICS\fP, \fBKillerEngine::WINDOWS\fP, \fBKillerEngine::OPENGL\fP, \fBKillerEngine::SHADER\fP, \fBGLFW\fP, \fBTEXTURE_MANAGER\fP, \fBGAMEOBJECT\fP, \fBFREETYPE\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBKillerEngine::ErrorCode\fP"
Error codes that are used to give a hint as to where to code that is throwing the error is written\&. These are disaplyed to the user in a pop up window when the end application is run\&. These are paired with a more detailed message when the end error is set\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINOT_ERROR \fP\fP
Default value\&. Shouldn't ever be used\&. 
.TP
\fB\fIUNKNOWN_ERROR \fP\fP
Fall through code, indicates an error in the setting of an error\&. 
.TP
\fB\fIENGINE \fP\fP
Indicates the error is in the engine's main code, not very specific\&. 
.TP
\fB\fIPHYSICS \fP\fP
Indicates the error is in the KillerPhysics namespace\&. 
.TP
\fB\fIWINDOWS \fP\fP
Indicates that the error is related to the windowing system\&. 
.TP
\fB\fIOPENGL \fP\fP
Indicates that the error is in OpenGL related code\&. 
.TP
\fB\fISHADER \fP\fP
Indicates that the error is caused by OpenGL shader compilation\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
