.TH "FT_BBox_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_BBox_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Pos \fBxMin\fP"
.br
.ti -1c
.RI "FT_Pos \fByMin\fP"
.br
.ti -1c
.RI "FT_Pos \fBxMax\fP"
.br
.ti -1c
.RI "FT_Pos \fByMax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
