.TH "FT_Bitmap_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Bitmap_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBrows\fP"
.br
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBpitch\fP"
.br
.ti -1c
.RI "unsigned char * \fBbuffer\fP"
.br
.ti -1c
.RI "unsigned short \fBnum_grays\fP"
.br
.ti -1c
.RI "unsigned char \fBpixel_mode\fP"
.br
.ti -1c
.RI "unsigned char \fBpalette_mode\fP"
.br
.ti -1c
.RI "void * \fBpalette\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
