.TH "FT_Bitmap_Size_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Bitmap_Size_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Short \fBheight\fP"
.br
.ti -1c
.RI "FT_Short \fBwidth\fP"
.br
.ti -1c
.RI "FT_Pos \fBsize\fP"
.br
.ti -1c
.RI "FT_Pos \fBx_ppem\fP"
.br
.ti -1c
.RI "FT_Pos \fBy_ppem\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
