.TH "FT_BitmapGlyphRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_BitmapGlyphRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_GlyphRec\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_Int \fBleft\fP"
.br
.ti -1c
.RI "FT_Int \fBtop\fP"
.br
.ti -1c
.RI "\fBFT_Bitmap\fP \fBbitmap\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
