.TH "FT_FaceRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_FaceRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Long \fBnum_faces\fP"
.br
.ti -1c
.RI "FT_Long \fBface_index\fP"
.br
.ti -1c
.RI "FT_Long \fBface_flags\fP"
.br
.ti -1c
.RI "FT_Long \fBstyle_flags\fP"
.br
.ti -1c
.RI "FT_Long \fBnum_glyphs\fP"
.br
.ti -1c
.RI "FT_String * \fBfamily_name\fP"
.br
.ti -1c
.RI "FT_String * \fBstyle_name\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_fixed_sizes\fP"
.br
.ti -1c
.RI "\fBFT_Bitmap_Size\fP * \fBavailable_sizes\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_charmaps\fP"
.br
.ti -1c
.RI "\fBFT_CharMap\fP * \fBcharmaps\fP"
.br
.ti -1c
.RI "\fBFT_Generic\fP \fBgeneric\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBbbox\fP"
.br
.ti -1c
.RI "FT_UShort \fBunits_per_EM\fP"
.br
.ti -1c
.RI "FT_Short \fBascender\fP"
.br
.ti -1c
.RI "FT_Short \fBdescender\fP"
.br
.ti -1c
.RI "FT_Short \fBheight\fP"
.br
.ti -1c
.RI "FT_Short \fBmax_advance_width\fP"
.br
.ti -1c
.RI "FT_Short \fBmax_advance_height\fP"
.br
.ti -1c
.RI "FT_Short \fBunderline_position\fP"
.br
.ti -1c
.RI "FT_Short \fBunderline_thickness\fP"
.br
.ti -1c
.RI "\fBFT_GlyphSlot\fP \fBglyph\fP"
.br
.ti -1c
.RI "\fBFT_Size\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBFT_CharMap\fP \fBcharmap\fP"
.br
.ti -1c
.RI "FT_Driver \fBdriver\fP"
.br
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "\fBFT_Stream\fP \fBstream\fP"
.br
.ti -1c
.RI "\fBFT_ListRec\fP \fBsizes_list\fP"
.br
.ti -1c
.RI "\fBFT_Generic\fP \fBautohint\fP"
.br
.ti -1c
.RI "void * \fBextensions\fP"
.br
.ti -1c
.RI "FT_Face_Internal \fBinternal\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
