.TH "FT_GlyphSlotRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_GlyphSlotRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Library \fBlibrary\fP"
.br
.ti -1c
.RI "\fBFT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "\fBFT_GlyphSlot\fP \fBnext\fP"
.br
.ti -1c
.RI "FT_UInt \fBreserved\fP"
.br
.ti -1c
.RI "\fBFT_Generic\fP \fBgeneric\fP"
.br
.ti -1c
.RI "FT_Glyph_Metrics \fBmetrics\fP"
.br
.ti -1c
.RI "FT_Fixed \fBlinearHoriAdvance\fP"
.br
.ti -1c
.RI "FT_Fixed \fBlinearVertAdvance\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBadvance\fP"
.br
.ti -1c
.RI "FT_Glyph_Format \fBformat\fP"
.br
.ti -1c
.RI "\fBFT_Bitmap\fP \fBbitmap\fP"
.br
.ti -1c
.RI "FT_Int \fBbitmap_left\fP"
.br
.ti -1c
.RI "FT_Int \fBbitmap_top\fP"
.br
.ti -1c
.RI "\fBFT_Outline\fP \fBoutline\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_subglyphs\fP"
.br
.ti -1c
.RI "FT_SubGlyph \fBsubglyphs\fP"
.br
.ti -1c
.RI "void * \fBcontrol_data\fP"
.br
.ti -1c
.RI "long \fBcontrol_len\fP"
.br
.ti -1c
.RI "FT_Pos \fBlsb_delta\fP"
.br
.ti -1c
.RI "FT_Pos \fBrsb_delta\fP"
.br
.ti -1c
.RI "void * \fBother\fP"
.br
.ti -1c
.RI "FT_Slot_Internal \fBinternal\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
