.TH "FT_Glyph_Metrics_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Glyph_Metrics_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Pos \fBwidth\fP"
.br
.ti -1c
.RI "FT_Pos \fBheight\fP"
.br
.ti -1c
.RI "FT_Pos \fBhoriBearingX\fP"
.br
.ti -1c
.RI "FT_Pos \fBhoriBearingY\fP"
.br
.ti -1c
.RI "FT_Pos \fBhoriAdvance\fP"
.br
.ti -1c
.RI "FT_Pos \fBvertBearingX\fP"
.br
.ti -1c
.RI "FT_Pos \fBvertBearingY\fP"
.br
.ti -1c
.RI "FT_Pos \fBvertAdvance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
