.TH "FT_Glyph_Class_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Glyph_Class_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Long \fBglyph_size\fP"
.br
.ti -1c
.RI "FT_Glyph_Format \fBglyph_format\fP"
.br
.ti -1c
.RI "FT_Glyph_InitFunc \fBglyph_init\fP"
.br
.ti -1c
.RI "FT_Glyph_DoneFunc \fBglyph_done\fP"
.br
.ti -1c
.RI "FT_Glyph_CopyFunc \fBglyph_copy\fP"
.br
.ti -1c
.RI "FT_Glyph_TransformFunc \fBglyph_transform\fP"
.br
.ti -1c
.RI "FT_Glyph_GetBBoxFunc \fBglyph_bbox\fP"
.br
.ti -1c
.RI "FT_Glyph_PrepareFunc \fBglyph_prepare\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
