.TH "FT_Incremental_FuncsRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Incremental_FuncsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Incremental_GetGlyphDataFunc \fBget_glyph_data\fP"
.br
.ti -1c
.RI "FT_Incremental_FreeGlyphDataFunc \fBfree_glyph_data\fP"
.br
.ti -1c
.RI "FT_Incremental_GetGlyphMetricsFunc \fBget_glyph_metrics\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
