.TH "FT_Incremental_MetricsRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Incremental_MetricsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Long \fBbearing_x\fP"
.br
.ti -1c
.RI "FT_Long \fBbearing_y\fP"
.br
.ti -1c
.RI "FT_Long \fBadvance\fP"
.br
.ti -1c
.RI "FT_Long \fBadvance_v\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
