.TH "FT_MM_Axis_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_MM_Axis_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_String * \fBname\fP"
.br
.ti -1c
.RI "FT_Long \fBminimum\fP"
.br
.ti -1c
.RI "FT_Long \fBmaximum\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
