.TH "FT_Multi_Master_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Multi_Master_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBnum_axis\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_designs\fP"
.br
.ti -1c
.RI "FT_MM_Axis \fBaxis\fP [T1_MAX_MM_AXIS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
