.TH "FT_Module_Class_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Module_Class_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_ULong \fBmodule_flags\fP"
.br
.ti -1c
.RI "FT_Long \fBmodule_size\fP"
.br
.ti -1c
.RI "const FT_String * \fBmodule_name\fP"
.br
.ti -1c
.RI "FT_Fixed \fBmodule_version\fP"
.br
.ti -1c
.RI "FT_Fixed \fBmodule_requires\fP"
.br
.ti -1c
.RI "const void * \fBmodule_interface\fP"
.br
.ti -1c
.RI "FT_Module_Constructor \fBmodule_init\fP"
.br
.ti -1c
.RI "FT_Module_Destructor \fBmodule_done\fP"
.br
.ti -1c
.RI "FT_Module_Requester \fBget_interface\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
