.TH "FT_MM_Var_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_MM_Var_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBnum_axis\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_designs\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_namedstyles\fP"
.br
.ti -1c
.RI "\fBFT_Var_Axis\fP * \fBaxis\fP"
.br
.ti -1c
.RI "\fBFT_Var_Named_Style\fP * \fBnamedstyle\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
