.TH "FT_Outline_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Outline_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBn_contours\fP"
.br
.ti -1c
.RI "short \fBn_points\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP * \fBpoints\fP"
.br
.ti -1c
.RI "char * \fBtags\fP"
.br
.ti -1c
.RI "short * \fBcontours\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
