.TH "FT_Open_Args_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Open_Args_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBflags\fP"
.br
.ti -1c
.RI "const FT_Byte * \fBmemory_base\fP"
.br
.ti -1c
.RI "FT_Long \fBmemory_size\fP"
.br
.ti -1c
.RI "FT_String * \fBpathname\fP"
.br
.ti -1c
.RI "\fBFT_Stream\fP \fBstream\fP"
.br
.ti -1c
.RI "FT_Module \fBdriver\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_params\fP"
.br
.ti -1c
.RI "\fBFT_Parameter\fP * \fBparams\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
