.TH "FT_Raster_Params_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Raster_Params_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBFT_Bitmap\fP * \fBtarget\fP"
.br
.ti -1c
.RI "const void * \fBsource\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "FT_SpanFunc \fBgray_spans\fP"
.br
.ti -1c
.RI "FT_SpanFunc \fBblack_spans\fP"
.br
.ti -1c
.RI "FT_Raster_BitTest_Func \fBbit_test\fP"
.br
.ti -1c
.RI "FT_Raster_BitSet_Func \fBbit_set\fP"
.br
.ti -1c
.RI "void * \fBuser\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBclip_box\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
