.TH "FT_Renderer_Class_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Renderer_Class_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Module_Class\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_Glyph_Format \fBglyph_format\fP"
.br
.ti -1c
.RI "FT_Renderer_RenderFunc \fBrender_glyph\fP"
.br
.ti -1c
.RI "FT_Renderer_TransformFunc \fBtransform_glyph\fP"
.br
.ti -1c
.RI "FT_Renderer_GetCBoxFunc \fBget_glyph_cbox\fP"
.br
.ti -1c
.RI "FT_Renderer_SetModeFunc \fBset_mode\fP"
.br
.ti -1c
.RI "\fBFT_Raster_Funcs\fP * \fBraster_class\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
