.TH "FT_StreamRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_StreamRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char * \fBbase\fP"
.br
.ti -1c
.RI "unsigned long \fBsize\fP"
.br
.ti -1c
.RI "unsigned long \fBpos\fP"
.br
.ti -1c
.RI "\fBFT_StreamDesc\fP \fBdescriptor\fP"
.br
.ti -1c
.RI "\fBFT_StreamDesc\fP \fBpathname\fP"
.br
.ti -1c
.RI "FT_Stream_IoFunc \fBread\fP"
.br
.ti -1c
.RI "FT_Stream_CloseFunc \fBclose\fP"
.br
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "unsigned char * \fBcursor\fP"
.br
.ti -1c
.RI "unsigned char * \fBlimit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
