.TH "FT_SizeRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_SizeRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "\fBFT_Generic\fP \fBgeneric\fP"
.br
.ti -1c
.RI "\fBFT_Size_Metrics\fP \fBmetrics\fP"
.br
.ti -1c
.RI "FT_Size_Internal \fBinternal\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
