.TH "FT_Size_RequestRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Size_RequestRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Size_Request_Type \fBtype\fP"
.br
.ti -1c
.RI "FT_Long \fBwidth\fP"
.br
.ti -1c
.RI "FT_Long \fBheight\fP"
.br
.ti -1c
.RI "FT_UInt \fBhoriResolution\fP"
.br
.ti -1c
.RI "FT_UInt \fBvertResolution\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
