.TH "FT_SfntName_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_SfntName_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBplatform_id\fP"
.br
.ti -1c
.RI "FT_UShort \fBencoding_id\fP"
.br
.ti -1c
.RI "FT_UShort \fBlanguage_id\fP"
.br
.ti -1c
.RI "FT_UShort \fBname_id\fP"
.br
.ti -1c
.RI "FT_Byte * \fBstring\fP"
.br
.ti -1c
.RI "FT_UInt \fBstring_len\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
