.TH "FT_Size_Metrics_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Size_Metrics_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBx_ppem\fP"
.br
.ti -1c
.RI "FT_UShort \fBy_ppem\fP"
.br
.ti -1c
.RI "FT_Fixed \fBx_scale\fP"
.br
.ti -1c
.RI "FT_Fixed \fBy_scale\fP"
.br
.ti -1c
.RI "FT_Pos \fBascender\fP"
.br
.ti -1c
.RI "FT_Pos \fBdescender\fP"
.br
.ti -1c
.RI "FT_Pos \fBheight\fP"
.br
.ti -1c
.RI "FT_Pos \fBmax_advance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
