.TH "FT_Var_Named_Style_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Var_Named_Style_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Fixed * \fBcoords\fP"
.br
.ti -1c
.RI "FT_UInt \fBstrid\fP"
.br
.ti -1c
.RI "FT_UInt \fBpsid\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
