.TH "FT_Var_Axis_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Var_Axis_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_String * \fBname\fP"
.br
.ti -1c
.RI "FT_Fixed \fBminimum\fP"
.br
.ti -1c
.RI "FT_Fixed \fBdef\fP"
.br
.ti -1c
.RI "FT_Fixed \fBmaximum\fP"
.br
.ti -1c
.RI "FT_ULong \fBtag\fP"
.br
.ti -1c
.RI "FT_UInt \fBstrid\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
