.TH "FT_WinFNT_HeaderRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_WinFNT_HeaderRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBversion\fP"
.br
.ti -1c
.RI "FT_ULong \fBfile_size\fP"
.br
.ti -1c
.RI "FT_Byte \fBcopyright\fP [60]"
.br
.ti -1c
.RI "FT_UShort \fBfile_type\fP"
.br
.ti -1c
.RI "FT_UShort \fBnominal_point_size\fP"
.br
.ti -1c
.RI "FT_UShort \fBvertical_resolution\fP"
.br
.ti -1c
.RI "FT_UShort \fBhorizontal_resolution\fP"
.br
.ti -1c
.RI "FT_UShort \fBascent\fP"
.br
.ti -1c
.RI "FT_UShort \fBinternal_leading\fP"
.br
.ti -1c
.RI "FT_UShort \fBexternal_leading\fP"
.br
.ti -1c
.RI "FT_Byte \fBitalic\fP"
.br
.ti -1c
.RI "FT_Byte \fBunderline\fP"
.br
.ti -1c
.RI "FT_Byte \fBstrike_out\fP"
.br
.ti -1c
.RI "FT_UShort \fBweight\fP"
.br
.ti -1c
.RI "FT_Byte \fBcharset\fP"
.br
.ti -1c
.RI "FT_UShort \fBpixel_width\fP"
.br
.ti -1c
.RI "FT_UShort \fBpixel_height\fP"
.br
.ti -1c
.RI "FT_Byte \fBpitch_and_family\fP"
.br
.ti -1c
.RI "FT_UShort \fBavg_width\fP"
.br
.ti -1c
.RI "FT_UShort \fBmax_width\fP"
.br
.ti -1c
.RI "FT_Byte \fBfirst_char\fP"
.br
.ti -1c
.RI "FT_Byte \fBlast_char\fP"
.br
.ti -1c
.RI "FT_Byte \fBdefault_char\fP"
.br
.ti -1c
.RI "FT_Byte \fBbreak_char\fP"
.br
.ti -1c
.RI "FT_UShort \fBbytes_per_row\fP"
.br
.ti -1c
.RI "FT_ULong \fBdevice_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBface_name_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBbits_pointer\fP"
.br
.ti -1c
.RI "FT_ULong \fBbits_offset\fP"
.br
.ti -1c
.RI "FT_Byte \fBreserved\fP"
.br
.ti -1c
.RI "FT_ULong \fBflags\fP"
.br
.ti -1c
.RI "FT_UShort \fBA_space\fP"
.br
.ti -1c
.RI "FT_UShort \fBB_space\fP"
.br
.ti -1c
.RI "FT_UShort \fBC_space\fP"
.br
.ti -1c
.RI "FT_UShort \fBcolor_table_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBreserved1\fP [4]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
