.TH "FTC_ScalerRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_ScalerRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FTC_FaceID \fBface_id\fP"
.br
.ti -1c
.RI "FT_UInt \fBwidth\fP"
.br
.ti -1c
.RI "FT_UInt \fBheight\fP"
.br
.ti -1c
.RI "FT_Int \fBpixel\fP"
.br
.ti -1c
.RI "FT_UInt \fBx_res\fP"
.br
.ti -1c
.RI "FT_UInt \fBy_res\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
