.TH "FTC_SBitRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_SBitRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBwidth\fP"
.br
.ti -1c
.RI "FT_Byte \fBheight\fP"
.br
.ti -1c
.RI "FT_Char \fBleft\fP"
.br
.ti -1c
.RI "FT_Char \fBtop\fP"
.br
.ti -1c
.RI "FT_Byte \fBformat\fP"
.br
.ti -1c
.RI "FT_Byte \fBmax_grays\fP"
.br
.ti -1c
.RI "FT_Short \fBpitch\fP"
.br
.ti -1c
.RI "FT_Char \fBxadvance\fP"
.br
.ti -1c
.RI "FT_Char \fByadvance\fP"
.br
.ti -1c
.RI "FT_Byte * \fBbuffer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
