.TH "GLFWvidmode" 3 "Sat Jul 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLFWvidmode \- Video mode type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glfw3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBredBits\fP"
.br
.ti -1c
.RI "int \fBgreenBits\fP"
.br
.ti -1c
.RI "int \fBblueBits\fP"
.br
.ti -1c
.RI "int \fBrefreshRate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Video mode type\&. 

This describes a single video mode\&.
.PP
\fBSee also:\fP
.RS 4
\fBmonitor_modes\fP 
.PP
\fBglfwGetVideoMode\fP \fBglfwGetVideoModes\fP
.RE
.PP
\fBSince:\fP
.RS 4
Added in version 1\&.0\&.  Added refresh rate member\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int GLFWvidmode::blueBits"
The bit depth of the blue channel of the video mode\&. 
.SS "int GLFWvidmode::greenBits"
The bit depth of the green channel of the video mode\&. 
.SS "int GLFWvidmode::height"
The height, in screen coordinates, of the video mode\&. 
.SS "int GLFWvidmode::redBits"
The bit depth of the red channel of the video mode\&. 
.SS "int GLFWvidmode::refreshRate"
The refresh rate, in Hz, of the video mode\&. 
.SS "int GLFWvidmode::width"
The width, in screen coordinates, of the video mode\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
