.TH "GLFWimage" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLFWimage \- Image data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glfw3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "unsigned char * \fBpixels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Image data\&. 


.PP
\fBSee also:\fP
.RS 4
\fBcursor_custom\fP 
.PP
\fBwindow_icon\fP
.RE
.PP
\fBSince:\fP
.RS 4
Added in version 2\&.1\&.  Removed format and bytes-per-pixel members\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int GLFWimage::height"
The height, in pixels, of this image\&. 
.SS "unsigned char* GLFWimage::pixels"
The pixel data of this image, arranged left-to-right, top-to-bottom\&. 
.SS "int GLFWimage::width"
The width, in pixels, of this image\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
