.TH "GLFWgammaramp" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLFWgammaramp \- Gamma ramp\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glfw3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short * \fBred\fP"
.br
.ti -1c
.RI "unsigned short * \fBgreen\fP"
.br
.ti -1c
.RI "unsigned short * \fBblue\fP"
.br
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gamma ramp\&. 

This describes the gamma ramp for a monitor\&.
.PP
\fBSee also:\fP
.RS 4
\fBmonitor_gamma\fP 
.PP
\fBglfwGetGammaRamp\fP \fBglfwSetGammaRamp\fP
.RE
.PP
\fBSince:\fP
.RS 4
Added in version 3\&.0\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "unsigned short* GLFWgammaramp::blue"
An array of value describing the response of the blue channel\&. 
.SS "unsigned short* GLFWgammaramp::green"
An array of value describing the response of the green channel\&. 
.SS "unsigned short* GLFWgammaramp::red"
An array of value describing the response of the red channel\&. 
.SS "unsigned int GLFWgammaramp::size"
The number of elements in each array\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
