.TH "GLXHyperpipeConfigSGIX" 3 "Sun Jun 3 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXHyperpipeConfigSGIX
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [80]"
.br
.ti -1c
.RI "int \fBchannel\fP"
.br
.ti -1c
.RI "unsigned int \fBparticipationType\fP"
.br
.ti -1c
.RI "int \fBtimeSlice\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
