.TH "GLXHyperpipeNetworkSGIX" 3 "Mon Jun 4 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXHyperpipeNetworkSGIX
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [80]"
.br
.ti -1c
.RI "int \fBnetworkId\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
