.TH "GLXPbufferClobberEvent" 3 "Sat Jul 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPbufferClobberEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBevent_type\fP"
.br
.ti -1c
.RI "int \fBdraw_type\fP"
.br
.ti -1c
.RI "unsigned long \fBserial\fP"
.br
.ti -1c
.RI "Bool \fBsend_event\fP"
.br
.ti -1c
.RI "Display * \fBdisplay\fP"
.br
.ti -1c
.RI "GLXDrawable \fBdrawable\fP"
.br
.ti -1c
.RI "unsigned int \fBbuffer_mask\fP"
.br
.ti -1c
.RI "unsigned int \fBaux_buffer\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
