.TH "GLXPipeRect" 3 "Mon Jun 11 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPipeRect
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [80]"
.br
.ti -1c
.RI "int \fBsrcXOrigin\fP"
.br
.ti -1c
.RI "int \fBsrcYOrigin\fP"
.br
.ti -1c
.RI "int \fBsrcWidth\fP"
.br
.ti -1c
.RI "int \fBsrcHeight\fP"
.br
.ti -1c
.RI "int \fBdestXOrigin\fP"
.br
.ti -1c
.RI "int \fBdestYOrigin\fP"
.br
.ti -1c
.RI "int \fBdestWidth\fP"
.br
.ti -1c
.RI "int \fBdestHeight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
