.TH "KillerEngine::WinProgram" 3 "Sat Jul 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::WinProgram
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEndRunning\fP (void)"
.br
.ti -1c
.RI "bool \fBGetRunning\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetWidth\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetRight\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetLeft\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetHeight\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetTop\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetBottom\fP (void)"
.br
.ti -1c
.RI "void \fBSetBackgroundColor\fP (const \fBColor\fP &c)"
.br
.ti -1c
.RI "void \fBInit\fP (S32 width, S32 height, string wndName, bool isFullScreen)"
.br
.ti -1c
.RI "void \fBProcessEvents\fP (void)"
.br
.ti -1c
.RI "void \fBBufferSwap\fP (void)"
.br
.ti -1c
.RI "void \fBDisplayFPS\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBWinProgram\fP > \fBInstance\fP (void)"
.br
.ti -1c
.RI "static void \fBOnKey\fP (\fBGLFWwindow\fP *window, int key, int scancode, int action, int mode)"
.br
.RI "Sets up Windows Program\&. "
.ti -1c
.RI "static Keys \fBConvertKeyCodes\fP (int key)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fB_isFullScreen\fP"
.br
.ti -1c
.RI "bool \fB_running\fP"
.br
.ti -1c
.RI "S32 \fB_totalWidth\fP"
.br
.ti -1c
.RI "S32 \fB_totalHeight\fP"
.br
.ti -1c
.RI "S32 \fB_right\fP"
.br
.ti -1c
.RI "S32 \fB_left\fP"
.br
.ti -1c
.RI "S32 \fB_top\fP"
.br
.ti -1c
.RI "S32 \fB_bottom\fP"
.br
.ti -1c
.RI "string \fB_wndName\fP"
.br
.ti -1c
.RI "\fBColor\fP \fB_bgColor\fP"
.br
.ti -1c
.RI "\fBGLFWwindow\fP * \fB_window\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBWinProgram\fP > \fB_instance\fP = NULL"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void WinProgram::OnKey (\fBGLFWwindow\fP * window, int key, int scancode, int action, int mode)\fC [static]\fP"

.PP
Sets up Windows Program\&. Makes all calls needed to start up a window\&. This is means to abstract away system specific callls 
.PP
\fBParameters:\fP
.RS 4
\fIwidth\fP S32: width of created window 
.br
\fIheight\fP S32: height of created window 
.br
\fIwndName\fP string: title of window 
.br
\fIisFullScreen\fP bool: Sets if the system makes the window fullscreen 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
