.TH "KillerPhysics::ForceRegistry::_ParticleForceRegistration" 3 "Tue May 14 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ForceRegistry::_ParticleForceRegistration
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (\fB_ParticleForceRegistration\fP p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "shared_ptr< \fBParticle\fP > \fBparticle\fP"
.br
.RI "Pointer to object saved to add force to later\&. "
.ti -1c
.RI "shared_ptr< \fBForceGenerator\fP > \fBforceGen\fP"
.br
.RI "Pointer to force saved to be added to object later\&. "
.in -1c
.SH "Detailed Description"
.PP 
Private struct type that pairs a single \fBParticle\fP with a \fBForceGenerator\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool KillerPhysics::ForceRegistry::_ParticleForceRegistration::operator== (\fB_ParticleForceRegistration\fP p)\fC [inline]\fP"
Returns true if another registration matches this one\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp\fP is the registration to be compared against\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
