.TH "KillerEngine::Texture" 3 "Thu Jun 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::Texture
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTexture\fP (GLuint id, S32 width, S32 height)"
.br
.ti -1c
.RI "\fBTexture\fP (const \fBTexture\fP &T)"
.br
.ti -1c
.RI "\fBTexture\fP (const \fBTexture\fP *T)"
.br
.ti -1c
.RI "GLuint \fBGetID\fP (void) const"
.br
.ti -1c
.RI "void \fBSetID\fP (GLuint id)"
.br
.ti -1c
.RI "S32 \fBGetWidth\fP (void) const"
.br
.ti -1c
.RI "void \fBSetWidth\fP (S32 w)"
.br
.ti -1c
.RI "S32 \fBGetHeight\fP (void) const"
.br
.ti -1c
.RI "void \fBSetHeight\fP (S32 h)"
.br
.ti -1c
.RI "\fBTexture\fP & \fBoperator=\fP (const \fBTexture\fP &T)"
.br
.ti -1c
.RI "\fBTexture\fP & \fBoperator=\fP (\fBTexture\fP *T)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "GLuint \fB_id\fP"
.br
.ti -1c
.RI "S32 \fB_width\fP"
.br
.ti -1c
.RI "S32 \fB_height\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
