.TH "KillerPhysics::BoundingBox" 3 "Sun Jan 13 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::BoundingBox
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKM::Vector\fP \fBcenter\fP"
.br
.ti -1c
.RI "\fBKM::Vector\fP \fBhalfSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
