.TH "KillerPhysics::ParticleDragForce" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ParticleDragForce
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerPhysics::ForceGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticleDragForce\fP (real drag, real dragSqr)"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (shared_ptr< \fBParticle\fP > particle) final"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "real \fB_drag\fP"
.br
.ti -1c
.RI "real \fB_dragSqr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
