.TH "KillerEngine::Camera" 3 "Mon Jun 4 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::Camera
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetOrthographic\fP (void)"
.br
.ti -1c
.RI "void \fBSetPerspective\fP (void)"
.br
.ti -1c
.RI "void \fBSetDefaultMatrix\fP (void)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (F32 x, F32 y)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (const \fBKM::Vector2\fP &V)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (F32 x, F32 y, F32 z)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (const \fBKM::Vector3\fP &V)"
.br
.ti -1c
.RI "void \fBScalePosition\fP (F32 x, F32 y, F32 scale)"
.br
.ti -1c
.RI "void \fBScalePosition\fP (const \fBKM::Vector2\fP &v, F32 scale)"
.br
.ti -1c
.RI "void \fBScalePosition\fP (F32 x, F32 y, F32 z, F32 scale)"
.br
.ti -1c
.RI "void \fBScalePosition\fP (const \fBKM::Vector3\fP &V, F32 scale)"
.br
.ti -1c
.RI "void \fBSetColor\fP (const \fBColor\fP &col)"
.br
.ti -1c
.RI "void \fBSetUp\fP (GLuint shader)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBCamera\fP > \fBInstance\fP (void)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
