.TH "KillerEngine::Vertex" 3 "Thu Jan 31 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::Vertex
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVertex\fP (\fBKM::Vector\fP pos)"
.br
.ti -1c
.RI "\fBVertex\fP (const \fBKM::Vector\fP &pos, \fBColor\fP col)"
.br
.ti -1c
.RI "\fBVertex\fP (const \fBKM::Vector\fP &pos, F32 u, F32 v)"
.br
.ti -1c
.RI "\fBVertex\fP (const \fBKM::Vector\fP &pos, const \fBKM::Vector\fP &norm)"
.br
.ti -1c
.RI "\fBVertex\fP (const \fBKM::Vector\fP &pos, const \fBKM::Vector\fP &norm, F32 u, F32 v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKM::Vector\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBKM::Vector\fP \fBnormal\fP"
.br
.ti -1c
.RI "\fBTexCoord\fP \fBtexCoord\fP"
.br
.ti -1c
.RI "\fBColor\fP \fBcolor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
