.TH "KillerEngine::Level::LevelData" 3 "Sat Jul 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::Level::LevelData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmapWidth\fP"
.br
.ti -1c
.RI "int \fBmapHeight\fP"
.br
.ti -1c
.RI "int \fBtileWidth\fP"
.br
.ti -1c
.RI "int \fBtileHeight\fP"
.br
.ti -1c
.RI "\fBColor\fP \fBcolor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
