.TH "KillerEngine::Shader" 3 "Mon Feb 4 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::Shader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoadShader\fP (std::vector< \fBShaderData\fP > shaders)"
.br
.ti -1c
.RI "void \fBUse\fP (bool state=true)"
.br
.ti -1c
.RI "void \fBSetUniform\fP (const GLchar *name, const F32 val)"
.br
.ti -1c
.RI "void \fBSetUniform\fP (const GLchar *name, const \fBKM::Vector\fP &vec)"
.br
.ti -1c
.RI "void \fBSetUniformVec3\fP (const GLchar *name, const \fBKM::Vector\fP &vec)"
.br
.ti -1c
.RI "void \fBSetUniform\fP (const GLchar *name, \fBKM::Matrix\fP mat)"
.br
.ti -1c
.RI "void \fBSetUniformSampler\fP (const GLchar *name, S32 texSlot)"
.br
.ti -1c
.RI "void \fBSetUniform\fP (const GLchar *name, const \fBColor\fP &col)"
.br
.ti -1c
.RI "void \fBSetUniformVec3\fP (const GLchar *name, const \fBColor\fP &col)"
.br
.ti -1c
.RI "GLuint \fBGetProgram\fP (void) const"
.br
.ti -1c
.RI "void \fBSetProgram\fP (GLuint program)"
.br
.ti -1c
.RI "map< string, GLuint > \fBGetUniformLocations\fP (void) const"
.br
.ti -1c
.RI "void \fBSetUniformLocations\fP (map< string, GLuint > uniforms)"
.br
.ti -1c
.RI "\fBShader\fP & \fBoperator=\fP (const \fBShader\fP &shader)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "string \fB_GetFileString\fP (string path)"
.br
.ti -1c
.RI "bool \fB_CheckCompileErrors\fP (GLuint shader)"
.br
.ti -1c
.RI "GLuint \fB_GetUniformLocation\fP (const GLchar *name)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "map< string, GLuint > \fB_uniformLocations\fP"
.br
.ti -1c
.RI "GLuint \fB_shaderProgram\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
