.TH "KillerPhysics::ParticleContactResolver" 3 "Sun Jun 3 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ParticleContactResolver
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticleContactResolver\fP (U32 iterations)"
.br
.ti -1c
.RI "void \fBSetIterations\fP (U32 iterations)"
.br
.ti -1c
.RI "void \fBResolveContacts\fP (\fBParticleContact\fP *contactArray, U32 numContacts)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
