.TH "KillerPhysics::ParticleContact" 3 "Sun Jun 3 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ParticleContact
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetRestitution\fP (real restitution)"
.br
.ti -1c
.RI "void \fBSetContactNormal\fP (\fBKM::Vector2\fP &normal)"
.br
.ti -1c
.RI "void \fBSetContactNormal\fP (\fBKM::Vector3\fP &normal)"
.br
.ti -1c
.RI "void \fBSetContacts\fP (shared_ptr< \fBParticle2D\fP > particle1, shared_ptr< \fBParticle2D\fP > particle2=nullptr)"
.br
.ti -1c
.RI "void \fBSetContacts\fP (shared_ptr< \fBParticle3D\fP > particle1, shared_ptr< \fBParticle3D\fP > particle2=nullptr)"
.br
.ti -1c
.RI "void \fBSetPenetration\fP (real penetration)"
.br
.ti -1c
.RI "real \fBGetPenetration\fP (void)"
.br
.ti -1c
.RI "const shared_ptr< \fBParticle2D\fP > \fBGetParticleOne\fP (void)"
.br
.ti -1c
.RI "const shared_ptr< \fBParticle2D\fP > \fBGetParticleTwo\fP (void)"
.br
.ti -1c
.RI "void \fBResolve\fP (void)"
.br
.ti -1c
.RI "real \fBCalculateSeparatingVelocity\fP (void) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
