.TH "KillerPhysics::ParticleForceRegistry" 3 "Tue Jul 10 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ParticleForceRegistry
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_Particle2DForceRegistration\fP"
.br
.ti -1c
.RI "struct \fB_Particle3DForceRegistration\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (shared_ptr< \fBParticle2D\fP > particle, shared_ptr< \fBParticleForceGenerator\fP > forceGen)"
.br
.ti -1c
.RI "void \fBAdd\fP (shared_ptr< \fBParticle3D\fP > particle, shared_ptr< \fBParticleForceGenerator\fP > forceGen)"
.br
.ti -1c
.RI "void \fBRemove\fP (shared_ptr< \fBParticle2D\fP > particle, shared_ptr< \fBParticleForceGenerator\fP > forceGen)"
.br
.ti -1c
.RI "void \fBRemove\fP (shared_ptr< \fBParticle3D\fP > particle, shared_ptr< \fBParticleForceGenerator\fP > forceGen)"
.br
.ti -1c
.RI "void \fBClear\fP (void)"
.br
.ti -1c
.RI "void \fBUpdateForces\fP (void)"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef std::vector< \fB_Particle2DForceRegistration\fP > \fBRegistry2D\fP"
.br
.ti -1c
.RI "typedef std::vector< \fB_Particle3DForceRegistration\fP > \fBRegistry3D\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Registry2D \fB_registrations2D\fP"
.br
.ti -1c
.RI "Registry3D \fB_registrations3D\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
