.TH "KillerEngine::EnvironmentObject" 3 "Sun Jun 3 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::EnvironmentObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerEngine::GameObject2D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnvironmentObject\fP (const \fBKM::Vector2\fP &pos, F32 w, F32 h)"
.br
.ti -1c
.RI "\fBEnvironmentObject\fP (const \fBKM::Vector2\fP &pos, U32 textureID, F32 w, F32 h)"
.br
.ti -1c
.RI "void \fBv_Update\fP (void)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
