.TH "KillerPhysics::Particle2D" 3 "Sat Jul 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::Particle2D
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerEngine::GameObject2D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticle2D\fP (const \fBParticle2D\fP *particle)"
.br
.ti -1c
.RI "\fBParticle2D\fP (const \fBParticle2D\fP &particle)"
.br
.ti -1c
.RI "const real \fBGetDamping\fP (void) const"
.br
.ti -1c
.RI "void \fBSetDamping\fP (real damp)"
.br
.ti -1c
.RI "const \fBKM::Vector2\fP & \fBGetVelocity\fP (void) const"
.br
.ti -1c
.RI "void \fBSetVelocity\fP (const \fBKM::Vector2\fP &v)"
.br
.ti -1c
.RI "void \fBSetVelocity\fP (F32 x, F32 y)"
.br
.ti -1c
.RI "void \fBAddScaledVelocity\fP (const \fBKM::Vector2\fP &vec, F32 scale)"
.br
.ti -1c
.RI "const \fBKM::Vector2\fP & \fBGetAcceleration\fP (void) const"
.br
.ti -1c
.RI "void \fBSetAcceleration\fP (const \fBKM::Vector2\fP &a)"
.br
.ti -1c
.RI "void \fBSetAcceleration\fP (F32 x, F32 y)"
.br
.ti -1c
.RI "void \fBAddScaledAcceleration\fP (const \fBKM::Vector2\fP &vec, F32 scale)"
.br
.ti -1c
.RI "const real \fBGetInverseMass\fP (void) const"
.br
.ti -1c
.RI "void \fBSetInverseMass\fP (real inverseMass)"
.br
.ti -1c
.RI "const real \fBGetMass\fP (void) const"
.br
.ti -1c
.RI "void \fBSetMass\fP (const real mass)"
.br
.ti -1c
.RI "bool \fBHasFiniteMass\fP (void)"
.br
.ti -1c
.RI "const \fBKM::Vector2\fP & \fBGetForces\fP (void) const"
.br
.ti -1c
.RI "const \fBKM::Vector2\fP & \fBGetGravityForce\fP (void) const"
.br
.ti -1c
.RI "void \fBSetGravityForce\fP (const \fBKM::Vector2\fP gravity)"
.br
.ti -1c
.RI "virtual void \fBv_Update\fP (void)"
.br
.ti -1c
.RI "void \fBIntegrate\fP ()"
.br
.ti -1c
.RI "void \fBClearAccumulator\fP (void)"
.br
.ti -1c
.RI "void \fBAddForce\fP (const \fBKM::Vector2\fP &force)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBKM::Vector2\fP \fB_velocity\fP"
.br
.ti -1c
.RI "\fBKM::Vector2\fP \fB_acceleration\fP"
.br
.ti -1c
.RI "\fBKM::Vector2\fP \fB_forceAccum\fP"
.br
.ti -1c
.RI "\fBKM::Vector2\fP \fB_gravityForce\fP"
.br
.ti -1c
.RI "real \fB_inverseMass\fP"
.br
.ti -1c
.RI "real \fB_damping\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Particle2D::v_Update (void)\fC [virtual]\fP"
Pure Virtual fucntion\&. Will be called during Level::UpdateObjects on each object, which will define what needs to happen in the update section of the loop\&. 
.PP
Implements \fBKillerEngine::GameObject2D\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
