.TH "KillerEngine::RenderedText" 3 "Sat Jul 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::RenderedText
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderedText\fP (const \fBFont\fP &font)"
.br
.ti -1c
.RI "\fBRenderedText\fP (string text, const \fBFont\fP &font)"
.br
.ti -1c
.RI "void \fBAddText\fP (string text)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (const \fBKM::Vector2\fP &pos)"
.br
.ti -1c
.RI "void \fBSetWidthScaleFactor\fP (F32 w)"
.br
.ti -1c
.RI "void \fBSetHeightScaleFactor\fP (F32 h)"
.br
.ti -1c
.RI "void \fBSetScaleFactors\fP (const F32 w, const F32 h)"
.br
.ti -1c
.RI "void \fBSetFont\fP (const \fBFont\fP &font)"
.br
.ti -1c
.RI "F32 \fBGetTotalWidth\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGetTotalHeight\fP (void) const"
.br
.ti -1c
.RI "const \fBKM::Vector2\fP & \fBGetCenter\fP (void) const"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBRenderedCharacter\fP > > \fBGetCharacterList\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBKM::Vector2\fP \fB_pos\fP"
.br
.ti -1c
.RI "string \fB_text\fP"
.br
.ti -1c
.RI "\fBFont\fP \fB_font\fP"
.br
.ti -1c
.RI "std::vector< shared_ptr< \fBRenderedCharacter\fP > > \fB_characterList\fP"
.br
.ti -1c
.RI "F32 \fB_widthScaleFactor\fP"
.br
.ti -1c
.RI "F32 \fB_heightScaleFactor\fP"
.br
.ti -1c
.RI "F32 \fB_totalWidth\fP"
.br
.ti -1c
.RI "F32 \fB_totalHeight\fP"
.br
.ti -1c
.RI "\fBKM::Vector2\fP \fB_center\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
