.TH "KillerEngine::TextureManager" 3 "Thu Aug 9 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::TextureManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddTexture\fP (S32 id, const \fBTexture\fP &tex)"
.br
.ti -1c
.RI "void \fBAddTexture\fP (S32 id, shared_ptr< \fBTexture\fP > tex)"
.br
.ti -1c
.RI "const shared_ptr< \fBTexture\fP > \fBGetTexture\fP (U32 id)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBTextureManager\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "map< S32, shared_ptr< \fBTexture\fP > > \fB_loadedTextures\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBTextureManager\fP > \fB_instance\fP = NULL"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
