.TH "KillerEngine::Font" 3 "Mon Feb 11 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::Font
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Font\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFont\fP (void)"
.br
.ti -1c
.RI "\fBFont\fP (const \fBFont\fP &f)"
.br
.ti -1c
.RI "\fBFont\fP (const \fBFont\fP *f)"
.br
.ti -1c
.RI "void \fBInit\fP (string fontName, string filePath, \fBU32\fP fontSize)"
.br
.ti -1c
.RI "\fBFont\fP & \fBoperator=\fP (const \fBFont\fP *font)"
.br
.ti -1c
.RI "\fBFont\fP & \fBoperator=\fP (const \fBFont\fP &font)"
.br
.ti -1c
.RI "void \fBSetNumCharacters\fP (\fBS32\fP num)"
.br
.ti -1c
.RI "\fBS32\fP \fBGetNumCharacters\fP (void) const"
.br
.ti -1c
.RI "void \fBSetSize\fP (\fBU32\fP size)"
.br
.ti -1c
.RI "\fBU32\fP \fBGetSize\fP (void) const"
.br
.ti -1c
.RI "void \fBSetName\fP (string fontName)"
.br
.ti -1c
.RI "const string \fBGetName\fP (void) const"
.br
.ti -1c
.RI "CharacterDataMap \fBGetAllCharacterGlyphs\fP (void) const"
.br
.ti -1c
.RI "\fBCharacterData\fP \fBGetCharacterData\fP (char c)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBS32\fP \fB_numCharacters\fP"
.br
.ti -1c
.RI "\fBU32\fP \fB_fontSize\fP"
.br
.ti -1c
.RI "string \fB_fontName\fP"
.br
.ti -1c
.RI "CharacterDataMap \fB_characterGlyphs\fP"
.br
.RI "All data from \&.fnt file stored in a RenderText can use for placement\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBFont\fP class is used to open a \&.fnt file, extract the needed character data, and then save that for text processing later on\&.
.PP
CreateCharacter is a CharSprite Factory\&. This may be important to know\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Font::Font (void)"
Default Constructor\&. No special actions taken\&. 
.SS "Font::Font (const \fBFont\fP & f)"
Copy Constructor\&. Calls GetTextureID(), GetFile() and \fBGetName()\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIf\fP \fBFont\fP&: \fBFont\fP to be copied\&. 
.RE
.PP

.SS "Font::Font (const \fBFont\fP * f)"
Copy Constructor\&. Calls GetTextureID(), GetFile() and \fBGetName()\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIf\fP Font*: \fBFont\fP to be copied\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "CharacterDataMap KillerEngine::Font::GetAllCharacterGlyphs (void) const\fC [inline]\fP"
Returns the map containing all data for all characters found in the loaded font\&. The ID of each character is found in the \&.fnt file and is the ASCII int value of a char 
.SS "const string KillerEngine::Font::GetName (void) const\fC [inline]\fP"
Returns the current name of the font\&. Not used in any major way\&. 
.SS "\fBFont\fP & Font::operator= (const \fBFont\fP * font)"
Copies \fBFont\fP pointer\&. Calls GetTextureID(), GetFile(), \fBGetName()\fP and GetCharacterData()\&. 
.SS "\fBFont\fP & Font::operator= (const \fBFont\fP & font)"
Copies \fBFont\fP reference\&. Calls GetTextureID(), GetFile(), \fBGetName()\fP and GetCharacterData()\&. 
.SS "void KillerEngine::Font::SetName (string fontName)\fC [inline]\fP"
Set's the name of font\&. Not used actively in any major way\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfontName\fP string: New name of the font\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
