.TH "KillerMath::Quaternion" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerMath::Quaternion
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuaternion\fP (real value)"
.br
.ti -1c
.RI "\fBQuaternion\fP (real wVal, real xVal, real yVal, real zVal)"
.br
.ti -1c
.RI "\fBQuaternion\fP (const \fBQuaternion\fP &q)"
.br
.ti -1c
.RI "const real * \fBGetElems\fP (void) const"
.br
.ti -1c
.RI "const F32 & \fBoperator[]\fP (int i) const"
.br
.ti -1c
.RI "F32 & \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBoperator/\fP (real d)"
.br
.ti -1c
.RI "\fBQuaternion\fP & \fBoperator/=\fP (real d)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBoperator*\fP (real m)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBoperator*\fP (const \fBQuaternion\fP &q2)"
.br
.ti -1c
.RI "\fBQuaternion\fP & \fBoperator*=\fP (real m)"
.br
.ti -1c
.RI "\fBQuaternion\fP & \fBoperator*=\fP (const \fBQuaternion\fP &q2)"
.br
.ti -1c
.RI "real \fBMagnitude\fP (void)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBConjugate\fP (void)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBInverse\fP (void)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBDifference\fP (\fBQuaternion\fP &Q)"
.br
.ti -1c
.RI "real \fBDot\fP (\fBQuaternion\fP &Q)"
.br
.ti -1c
.RI "void \fBNegate\fP (void)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBOpposite\fP (void)"
.br
.ti -1c
.RI "void \fBNormalize\fP (void)"
.br
.ti -1c
.RI "void \fBAddScaledVector\fP (const \fBVector\fP &vec, F32 scale)"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "enum { \fBw\fP = 0, \fBx\fP = 1, \fBy\fP = 2, \fBz\fP = 3 }"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "real \fB_data\fP [4]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
