.TH "KillerEngine::CharacterData" 3 "Mon Jun 11 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::CharacterData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "U32 \fBid\fP"
.br
.ti -1c
.RI "U32 \fBx\fP"
.br
.ti -1c
.RI "U32 \fBy\fP"
.br
.ti -1c
.RI "U32 \fBwidth\fP"
.br
.ti -1c
.RI "U32 \fBheight\fP"
.br
.ti -1c
.RI "U32 \fBxoffset\fP"
.br
.ti -1c
.RI "U32 \fByoffset\fP"
.br
.ti -1c
.RI "U32 \fBxadvance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
