.TH "KillerPhysics::ParticleBuoyantForce" 3 "Tue Jul 10 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ParticleBuoyantForce
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerPhysics::ParticleForceGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticleBuoyantForce::ParticleBuoyantForce\fP (real maxDepth, real objVolume, real liquidHeight, real liquidDensity=1000\&.0f)"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (shared_ptr< \fBParticle2D\fP > particle)"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (shared_ptr< \fBParticle3D\fP > particle)"
.br
.ti -1c
.RI "void \fBSetMaxDepth\fP (real depth)"
.br
.ti -1c
.RI "void \fBSetObjectVolume\fP (real volume)"
.br
.ti -1c
.RI "void \fBSetLiquidHeight\fP (real hieght)"
.br
.ti -1c
.RI "void \fBSetLiquidDensity\fP (real density)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "real \fB_maxDepth\fP"
.br
.ti -1c
.RI "real \fB_objectVolume\fP"
.br
.ti -1c
.RI "real \fB_liquidHeight\fP"
.br
.ti -1c
.RI "real \fB_liquidDensity\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
