.TH "KillerMath" 3 "Wed Jun 6 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerMath
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMatrix\fP"
.br
.ti -1c
.RI "class \fBMatrix4\fP"
.br
.ti -1c
.RI "class \fBQuaternion\fP"
.br
.ti -1c
.RI "class \fBRandom\fP"
.br
.ti -1c
.RI "class \fBTimer\fP"
.br
.ti -1c
.RI "class \fBVector2\fP"
.br
.ti -1c
.RI "class \fBVector3\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
