.TH "KillerEngine::OrbitCamera" 3 "Mon Feb 11 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::OrbitCamera
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerEngine::Camera\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBv_Rotate\fP (void)"
.br
.ti -1c
.RI "virtual void \fBv_Update\fP (void)"
.br
.ti -1c
.RI "void \fBSetRadius\fP (F32 val)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fB_v_UpdateCameraVectors\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "F32 \fB_radius\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
