.TH "KillerEngine::ModelRenderer" 3 "Sat Jul 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::ModelRenderer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const GLuint \fBGetShader\fP (void)"
.br
.ti -1c
.RI "void \fBSetShader\fP (GLuint shader)"
.br
.ti -1c
.RI "void \fBSetBackgroundColor\fP (\fBColor\fP &c)"
.br
.ti -1c
.RI "void \fBAddToBatch\fP (const \fBModel\fP &m)"
.br
.ti -1c
.RI "void \fBDraw\fP (void)"
.br
.ti -1c
.RI "void \fBDrawNow\fP (const \fBModel\fP &m, const \fBKM::Matrix\fP &modelView)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBModelRenderer\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "U32 \fB_maxBatchSize\fP"
.br
.ti -1c
.RI "U32 \fB_currentBatchSize\fP"
.br
.ti -1c
.RI "std::vector< F32 > \fB_vertices\fP"
.br
.ti -1c
.RI "GLuint \fB_VOA\fP [_NUM_VOA]"
.br
.ti -1c
.RI "GLuint \fB_shader\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBModelRenderer\fP > \fB_instance\fP = nullptr"
.br
.ti -1c
.RI "static const U32 \fB_NUM_VOA\fP = 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
