.TH "KillerEngine::FontManager" 3 "Mon Feb 4 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::FontManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoadFont\fP (U32 id, string fontName, string filePath, U32 size)"
.br
.ti -1c
.RI "void \fBAddFont\fP (U32 id, shared_ptr< \fBFont\fP > font)"
.br
.ti -1c
.RI "void \fBAddFont\fP (U32 id, \fBFont\fP &font)"
.br
.ti -1c
.RI "shared_ptr< \fBFont\fP > \fBGetFont\fP (U32 id)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBFontManager\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::map< U32, shared_ptr< \fBFont\fP > > \fB_loadedFonts\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBFontManager\fP > \fB_instance\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
