.TH "KillerMath::Random" 3 "Thu Aug 9 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerMath::Random
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "S32 \fBRandomInt\fP (S32 min, S32 max)"
.br
.ti -1c
.RI "S64 \fBRandomLong\fP (S64 min, S64 max)"
.br
.ti -1c
.RI "F32 \fBRandomFloat\fP (F32 min, F32 max)"
.br
.ti -1c
.RI "F64 \fBRandomDouble\fP (F64 min, F64 max)"
.br
.ti -1c
.RI "\fBVector2\fP \fBRandomVector2\fP (F32 min, F32 max)"
.br
.ti -1c
.RI "\fBVector3\fP \fBRandomVector3\fP (F32 min, F32 max)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBRandomQuaternion\fP (F32 min, F32 max)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBRandom\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::mt19937 \fB_generator\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBRandom\fP > \fB_instance\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
