.TH "KillerPhysics::Contact" 3 "Tue May 14 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::Contact
.SH SYNOPSIS
.br
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBKM::Vector4\fP \fB_contactPoint\fP"
.br
.ti -1c
.RI "\fBKM::Vector4\fP \fB_collissionNormal\fP"
.br
.ti -1c
.RI "\fBreal\fP \fB_penetrationDepth\fP"
.br
.ti -1c
.RI "\fBreal\fP \fB_collissionRestitution\fP"
.br
.ti -1c
.RI "\fBreal\fP \fB_friction\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
