.TH "KillerMath::Timer" 3 "Sun Jan 13 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerMath::Timer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetClamp\fP (bool state)"
.br
.ti -1c
.RI "bool \fBGetClamp\fP (void) const"
.br
.ti -1c
.RI "void \fBSetPaused\fP (bool paused)"
.br
.ti -1c
.RI "bool \fBGetPaused\fP (void) const"
.br
.ti -1c
.RI "void \fBSetTimeScale\fP (F32 scale)"
.br
.ti -1c
.RI "F32 \fBGetTimeScale\fP (void) const"
.br
.ti -1c
.RI "real \fBDeltaTime\fP (void) const"
.br
.ti -1c
.RI "F64 \fBTotalTime\fP (void) const"
.br
.ti -1c
.RI "void \fBUpdate\fP (void)"
.br
.ti -1c
.RI "void \fBSingleStep\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBTimer\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fB_clamp\fP"
.br
.ti -1c
.RI "real \fB_deltaTime\fP"
.br
.ti -1c
.RI "real \fB_timeScale\fP"
.br
.ti -1c
.RI "F64 \fB_totalTime\fP"
.br
.ti -1c
.RI "F64 \fB_pastTime\fP"
.br
.ti -1c
.RI "F64 \fB_currentTime\fP"
.br
.ti -1c
.RI "bool \fB_paused\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBTimer\fP > \fB_instance\fP = NULL"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
