.TH "KillerCollisions::Node< BoundingVolume, PhysicsObject >" 3 "Tue Jun 4 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerCollisions::Node< BoundingVolume, PhysicsObject >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsLeaf\fP (void) const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "BoundingVolume \fB_volume\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fB_children\fP [2]"
.br
.ti -1c
.RI "PhysicsObject * \fB_obj\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
