.TH "KillerMath::Matrix" 3 "Thu Jun 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerMath::Matrix
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrix\fP (F32 val)"
.br
.ti -1c
.RI "\fBMatrix\fP (const F32 mSrc[16])"
.br
.ti -1c
.RI "\fBMatrix\fP (F32 m00, F32 m01, F32 m02, F32 m03, F32 m10, F32 m11, F32 m12, F32 m13, F32 m20, F32 m21, F32 m22, F32 m23, F32 m30, F32 m31, F32 m32, F32 m33)"
.br
.ti -1c
.RI "\fBMatrix\fP (const \fBMatrix\fP &M)"
.br
.ti -1c
.RI "void \fBMakeOrthographic\fP (F32 width, F32 height, F32 depth, bool center=true)"
.br
.ti -1c
.RI "void \fBMakePerspective\fP (F32 width, F32 height, F32 depth, bool center=true)"
.br
.ti -1c
.RI "void \fBMakePerspective\fP (F32 fieldOfView, F32 aspectRatio, F32 nearPlane, F32 farPlane)"
.br
.ti -1c
.RI "void \fBTranslate\fP (F32 x, F32 y)"
.br
.ti -1c
.RI "void \fBTranslate\fP (F32 x, F32 y, F32 z)"
.br
.ti -1c
.RI "void \fBTranslate\fP (const \fBVector2\fP &vec)"
.br
.ti -1c
.RI "void \fBTranslate\fP (const \fBVector3\fP &vec)"
.br
.ti -1c
.RI "void \fBAddTranslate\fP (F32 x, F32 y)"
.br
.ti -1c
.RI "void \fBAddTranslate\fP (F32 x, F32 y, F32 z)"
.br
.ti -1c
.RI "void \fBAddTranslate\fP (const \fBVector2\fP &vec)"
.br
.ti -1c
.RI "void \fBAddTranslate\fP (const \fBVector3\fP &vec)"
.br
.ti -1c
.RI "void \fBScale\fP (F32 x, F32 y)"
.br
.ti -1c
.RI "void \fBScale\fP (F32 x, F32 y, F32 z)"
.br
.ti -1c
.RI "void \fBScale\fP (const \fBVector2\fP &vec)"
.br
.ti -1c
.RI "void \fBScale\fP (const \fBVector3\fP &vec)"
.br
.ti -1c
.RI "void \fBAddScale\fP (F32 x, F32 y)"
.br
.ti -1c
.RI "void \fBAddScale\fP (F32 x, F32 y, F32 z)"
.br
.ti -1c
.RI "void \fBAddScale\fP (const \fBVector2\fP &vec)"
.br
.ti -1c
.RI "void \fBAddScale\fP (const \fBVector3\fP &vec)"
.br
.ti -1c
.RI "void \fBRotateX\fP (F32 x)"
.br
.ti -1c
.RI "void \fBAddRotateX\fP (F32 x)"
.br
.ti -1c
.RI "void \fBRotateY\fP (F32 y)"
.br
.ti -1c
.RI "void \fBAddRotateY\fP (F32 y)"
.br
.ti -1c
.RI "void \fBRotateZ\fP (F32 z)"
.br
.ti -1c
.RI "void \fBAddRotateZ\fP (F32 z)"
.br
.ti -1c
.RI "void \fBRotate\fP (F32 x, F32 y, F32 z)"
.br
.ti -1c
.RI "void \fBAddRotation\fP (F32 x, F32 y, F32 z)"
.br
.ti -1c
.RI "void \fBMakeIdentity\fP (void)"
.br
.ti -1c
.RI "void \fBResetMatrix\fP (F32 val)"
.br
.ti -1c
.RI "void \fBTranspose\fP (void)"
.br
.ti -1c
.RI "void \fBComponentMulti\fP (const \fBMatrix\fP &M)"
.br
.ti -1c
.RI "const F32 * \fBGetElems\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet11\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet12\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet13\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet14\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet21\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet22\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet23\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet24\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet31\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet32\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet33\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet34\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet41\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet42\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet43\fP (void) const"
.br
.ti -1c
.RI "F32 \fBGet44\fP (void) const"
.br
.ti -1c
.RI "\fBMatrix\fP & \fBoperator=\fP (const \fBMatrix\fP &M)"
.br
.ti -1c
.RI "\fBMatrix\fP & \fBoperator*\fP (const \fBMatrix\fP &RightMatrix)"
.br
.ti -1c
.RI "\fBMatrix\fP & \fBoperator*=\fP (\fBMatrix\fP &RHM)"
.br
.ti -1c
.RI "\fBVector2\fP \fBoperator*\fP (const \fBVector2\fP &RHV)"
.br
.ti -1c
.RI "\fBVector3\fP \fBoperator*\fP (const \fBVector3\fP &RHV)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "F32 \fB_m\fP [16]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
