.TH "KillerEngine::Color" 3 "Sun Jun 3 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::Color
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP (F32 col)"
.br
.ti -1c
.RI "\fBColor\fP (F32 red, F32 green, F32 blue)"
.br
.ti -1c
.RI "\fBColor\fP (F32 red, F32 green, F32 blue, F32 alpha)"
.br
.ti -1c
.RI "\fBColor\fP (const \fBColor\fP &c)"
.br
.ti -1c
.RI "\fBColor\fP & \fBoperator=\fP (const \fBColor\fP &c)"
.br
.ti -1c
.RI "const F32 * \fBGet\fP (void) const"
.br
.ti -1c
.RI "const F32 \fBGetRed\fP (void) const"
.br
.ti -1c
.RI "const F32 \fBGetGreen\fP (void) const"
.br
.ti -1c
.RI "const F32 \fBGetBlue\fP (void) const"
.br
.ti -1c
.RI "const F32 \fBGetAlpha\fP (void) const"
.br
.ti -1c
.RI "void \fBSetRed\fP (const F32 r)"
.br
.ti -1c
.RI "void \fBSetGreen\fP (const F32 g)"
.br
.ti -1c
.RI "void \fBSetBlue\fP (const F32 b)"
.br
.ti -1c
.RI "void \fBSetAlpha\fP (const F32 a)"
.br
.ti -1c
.RI "void \fBSet\fP (F32 r, F32 g, F32 b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
