.TH "KillerPhysics::ForceGenerator" 3 "Wed Jan 23 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ForceGenerator
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBKillerPhysics::AnchoredSpring\fP, \fBKillerPhysics::BuoyantForce\fP, \fBKillerPhysics::GravityForce\fP, \fBKillerPhysics::ParticleDragForce\fP, and \fBKillerPhysics::SpringForce\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBv_UpdateForce\fP (shared_ptr< \fBParticle\fP > particle)=0"
.br
.ti -1c
.RI "virtual void \fBv_UpdateForce\fP (shared_ptr< \fBRigidBody\fP > body)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
