.TH "KillerEngine::EnvironmentObject" 3 "Mon Jun 11 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::EnvironmentObject
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EnvironmentObject\&.h>\fP
.PP
Inherits \fBKillerEngine::GameObject2D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnvironmentObject\fP (void)"
.br
.ti -1c
.RI "\fBEnvironmentObject\fP (const \fBKM::Vector2\fP &pos, F32 w, F32 h)"
.br
.ti -1c
.RI "\fBEnvironmentObject\fP (const \fBKM::Vector2\fP &pos, U32 textureID, F32 w, F32 h)"
.br
.ti -1c
.RI "\fB~EnvironmentObject\fP (void)"
.br
.ti -1c
.RI "void \fBv_Update\fP (void) final"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is an implementation of a GameObject which will reprents static, unmoving background objects which the player will not be allowed to pass through\&. These are things like rocks, trees, houses, etc\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EnvironmentObject::EnvironmentObject (void)"
Default Constructor\&. No special actions taken\&. 
.SS "EnvironmentObject::EnvironmentObject (const \fBKM::Vector2\fP & pos, F32 w, F32 h)"
Calls \fBGameObject2D::SetPosition\fP and \fBGameObject2D::SetDimensions\fP\&. 
.SS "EnvironmentObject::EnvironmentObject (const \fBKM::Vector2\fP & pos, U32 textureID, F32 w, F32 h)"
Calls \fBGameObject2D::SetPosition\fP, \fBGameObject2D::SetDimensions\fP and \fBGameObject2D::SetTexture\fP 
.SS "EnvironmentObject::~EnvironmentObject (void)"
Default Destructor\&. No special action taken\&. 
.SH "Member Function Documentation"
.PP 
.SS "void KillerEngine::EnvironmentObject::v_Update (void)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"
Empty function, needed because its a pure virtual function\&. 
.PP
Implements \fBKillerEngine::GameObject2D\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
