.TH "KillerEngine::AudioListener" 3 "Mon Jun 24 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::AudioListener
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AudioListener\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioListener\fP (void)"
.br
.ti -1c
.RI "\fB~AudioListener\fP (void)"
.br
.ti -1c
.RI "const \fBF32\fP * \fBGetOrientation\fP (void) const"
.br
.ti -1c
.RI "void \fBSetOrientation\fP (\fBF32\fP *orientation)"
.br
.ti -1c
.RI "const \fBKM::Vector3\fP & \fBGetPosition\fP (void) const"
.br
.ti -1c
.RI "void \fBSetPosition\fP (const \fBKM::Vector3\fP &pos)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (\fBF32\fP xVal, \fBF32\fP yVal, \fBF32\fP zVal)"
.br
.ti -1c
.RI "const \fBKM::Vector3\fP & \fBGetVelocity\fP (void) const"
.br
.ti -1c
.RI "void \fBSetVelocity\fP (const \fBKM::Vector3\fP vel)"
.br
.ti -1c
.RI "void \fBSetVelocity\fP (\fBF32\fP xVal, \fBF32\fP yVal, \fBF32\fP zVal)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBF32\fP \fB_orientation\fP [6]"
.br
.RI "Orientation of the listener\&. Not sure what the 6 values really mean\&. This can probably be changed\&. "
.ti -1c
.RI "\fBKM::Vector3\fP \fB_position\fP"
.br
.RI "Position of the listener in world space\&. "
.ti -1c
.RI "\fBKM::Vector3\fP \fB_velocity\fP"
.br
.RI "Velocity of the listener in world space\&. "
.in -1c
.SH "Detailed Description"
.PP 
In OpenAL, the listener is the hearer of any playing AudioSources\&. This is how 3D sound is achieved\&. This is a wrapper around OpenAL calls that set the internal state of the listener in OpenAL\&. These should be viewed as in World Coordinate space\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioListener::AudioListener (void)"
Calls AudioManger::Instace to insure that there is an OpenAL device and context already set up\&. 
.SS "AudioListener::~AudioListener (void)"
No implemenatation\&. The listener is not an OpenAL object, it is just a state of the context, since each context can only ever have a single listener\&. 
.SH "Member Function Documentation"
.PP 
.SS "const \fBF32\fP* KillerEngine::AudioListener::GetOrientation (void) const\fC [inline]\fP"
Returns the current orientation of the listener\&. Note, this is the cached version, OpenAL is not queried for these values\&. 
.SS "const \fBKM::Vector3\fP& KillerEngine::AudioListener::GetPosition (void) const\fC [inline]\fP"
Returns the current position of the listenser\&. Note, this is the cached version, OpenAL is not queried for these values\&. 
.SS "const \fBKM::Vector3\fP& KillerEngine::AudioListener::GetVelocity (void) const\fC [inline]\fP"
Returns the current velocity of the listenser\&. Note, this is the cached version, OpenAL is not queried for these values\&. 
.SS "void AudioListener::SetOrientation (\fBF32\fP * orientation)"
Sets a new orientation for the listener\&. This needs to be a 6 value array, or there will be issues\&. 
.PP
\fBParameters:\fP
.RS 4
\fIorienation\fP is the new orientation as an array\&. 
.RE
.PP

.SS "void AudioListener::SetPosition (const \fBKM::Vector3\fP & pos)"
Sets the new position state of the listener\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpos\fP is the new position in world space\&. 
.RE
.PP

.SS "void AudioListener::SetPosition (\fBF32\fP xVal, \fBF32\fP yVal, \fBF32\fP zVal)"
Sets the new position state of the listener\&. 
.PP
\fBParameters:\fP
.RS 4
\fIxVal\fP is the new x position in world space\&. 
.br
\fIyVal\fP is the new y position in world space\&. 
.br
\fIzVal\fP is the new z position in world space\&. 
.RE
.PP

.SS "void AudioListener::SetVelocity (const \fBKM::Vector3\fP vel)"
Sets the new velocity state of the listener\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvel\fP is the new velocity in world space\&. 
.RE
.PP

.SS "void AudioListener::SetVelocity (\fBF32\fP xVal, \fBF32\fP yVal, \fBF32\fP zVal)"
Sets the new velocity state of the listener\&. 
.PP
\fBParameters:\fP
.RS 4
\fIxVal\fP is the new x velocity in world space\&. 
.br
\fIyVal\fP is the new y velocity in world space\&. 
.br
\fIzVal\fP is the new z velocity in world space\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
