.TH "KillerEngine::CharacterData" 3 "Mon Jun 24 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::CharacterData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBS32\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBS32\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBS32\fP \fBbearingX\fP"
.br
.ti -1c
.RI "\fBS32\fP \fBbearingY\fP"
.br
.ti -1c
.RI "\fBS32\fP \fBxAdvance\fP"
.br
.ti -1c
.RI "shared_ptr< \fBTexture\fP > \fBtexture\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
