.TH "KillerPhysics::ParticleSpringForce" 3 "Mon Jun 4 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ParticleSpringForce
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerPhysics::ParticleForceGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticleSpringForce\fP (shared_ptr< \fBParticle2D\fP > otherEnd, real springConstant, real restLength)"
.br
.ti -1c
.RI "\fBParticleSpringForce\fP (shared_ptr< \fBParticle3D\fP > otherEnd, real springConstant, real restLength)"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (shared_ptr< \fBParticle2D\fP > particle) final"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (shared_ptr< \fBParticle3D\fP > particle) final"
.br
.ti -1c
.RI "void \fBMakeBungie\fP (bool state)"
.br
.ti -1c
.RI "void \fBSetOtherEnd\fP (shared_ptr< \fBParticle2D\fP > end)"
.br
.ti -1c
.RI "void \fBSetSpringConstant\fP (real constant)"
.br
.ti -1c
.RI "void \fBSetRestLength\fP (real length)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
