.TH "KillerEngine::Level::TileData" 3 "Wed Jan 30 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::Level::TileData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtileID\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "string \fBtexturePath\fP"
.br
.ti -1c
.RI "ObjectType \fBtype\fP"
.br
.ti -1c
.RI "int \fBtextureID\fP"
.br
.ti -1c
.RI "int \fBposX\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
