.TH "KillerEngine::MenuItem" 3 "Sat Jun 1 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::MenuItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Menu\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKM::Point\fP \fBpos\fP"
.br
.RI "Position of the \fBText\fP\&. Used for quick reference, useful even though its duplicated\&. "
.ti -1c
.RI "shared_ptr< \fBText\fP > \fBtext\fP"
.br
.RI "Pointer a \fBText\fP, used for the look of the item in the \fBMenu\fP\&. Call \fBLevel::AddTextToLevel\fP first\&. "
.ti -1c
.RI "void(* \fBAction\fP )(void) = NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct to hold all the information needed for an item in a \fBMenu\fP\&. 
.SH "Member Data Documentation"
.PP 
.SS "void(* KillerEngine::MenuItem::Action) (void) = NULL"
Callback function used when the item is activated\&. Must use the same signature\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
