.TH "KillerEngine::TexCoord" 3 "Tue May 14 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::TexCoord
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vertex\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTexCoord\fP (void)"
.br
.ti -1c
.RI "\fBTexCoord\fP (\fBF32\fP s, \fBF32\fP t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBF32\fP \fBu\fP"
.br
.RI "U coordinate\&. Should only be between 0 and 1\&. Matches to the x in a texture\&. "
.ti -1c
.RI "\fBF32\fP \fBv\fP"
.br
.RI "V coordinate\&. Should only be between 0 and 1\&. Matches to the y in a texture\&. "
.in -1c
.SH "Detailed Description"
.PP 
Helper struct to keep track of UV coordinates for a texture\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KillerEngine::TexCoord::TexCoord (void)\fC [inline]\fP"
Sets u and v to 0\&. 
.SS "KillerEngine::TexCoord::TexCoord (\fBF32\fP s, \fBF32\fP t)\fC [inline]\fP"
Sets up the start values for the coords\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP is the value for u\&. 
.br
\fIt\fP is the value for v\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
