.TH "KillerEngine::CharacterData" 3 "Mon Feb 11 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::CharacterData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "S32 \fBwidth\fP"
.br
.ti -1c
.RI "S32 \fBheight\fP"
.br
.ti -1c
.RI "S32 \fBbearingX\fP"
.br
.ti -1c
.RI "S32 \fBbearingY\fP"
.br
.ti -1c
.RI "S32 \fBxAdvance\fP"
.br
.ti -1c
.RI "shared_ptr< \fBTexture\fP > \fBtexture\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
