.TH "KillerPhysics::ParticleForceRegistry" 3 "Thu Aug 9 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ParticleForceRegistry
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_ParticleForceRegistration\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (shared_ptr< \fBParticle\fP > particle, shared_ptr< \fBParticleForceGenerator\fP > forceGen)"
.br
.ti -1c
.RI "void \fBRemove\fP (shared_ptr< \fBParticle\fP > particle, shared_ptr< \fBParticleForceGenerator\fP > forceGen)"
.br
.ti -1c
.RI "void \fBClear\fP (void)"
.br
.ti -1c
.RI "void \fBUpdateForces\fP (void)"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef std::vector< \fB_ParticleForceRegistration\fP > \fBRegistry\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Registry \fB_registrations\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
