.TH "KillerEngine::SpriteBatch" 3 "Wed Jun 6 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::SpriteBatch
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpriteBatch\fP (S32 size)"
.br
.ti -1c
.RI "void \fBSetMaxBatchSize\fP (S32 s)"
.br
.ti -1c
.RI "S32 \fBGetMaxBatchSize\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetCurrentBatchSize\fP (void)"
.br
.ti -1c
.RI "void \fBAddToBatch\fP (\fBSprite\fP)"
.br
.ti -1c
.RI "void \fBDrawBatch\fP (void)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
