.TH "KillerPhysics::DragForce" 3 "Tue Mar 12 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::DragForce
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DragForce\&.h>\fP
.PP
Inherits \fBKillerPhysics::ForceGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDragForce\fP (void)"
.br
.ti -1c
.RI "\fBDragForce\fP (\fBreal\fP drag)"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (shared_ptr< \fBParticle\fP > particle) final"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (shared_ptr< \fBRigidBody\fP > body) final"
.br
.ti -1c
.RI "void \fBSetDrag\fP (\fBreal\fP d)"
.br
.ti -1c
.RI "\fBreal\fP \fBGetDrag\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBreal\fP \fB_drag\fP"
.br
.RI "Drag coefficent used to determine how much velocity should be removed\&. "
.ti -1c
.RI "\fBreal\fP \fB_dragSqr\fP"
.br
.RI "Simply the drag coefficient squared\&. Cached to save on some operations\&. "
.in -1c
.SH "Detailed Description"
.PP 
A Drag or friction simulator\&. It takes in a physics object, then will reduce its overall velocity by an ammount each frame to simulate the affect of drag or friction\&.
.PP
The equation used for this is:
.PP
f = v * -d
.PP
where f is the force added to the object, v is the normalized velocity of the object and d is this equation:
.PP
d' = d * m + s * m^2
.PP
where m is the magnitude of the velocity of the object, and s is d * d, and is the coefficient set in the instance\&.
.PP
It is based on the Cyclone engine design found in 'Game Physics Engine Development, second edition' by Ian Millington\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DragForce::DragForce (void)"
Sets all values to 0\&. 
.SS "DragForce::DragForce (\fBreal\fP drag)"
Sets starting values for the \fBDragForce\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdrag\fP is the starting values for the drag cooefficient\&. Drag squared is set to drag * drag\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBreal\fP KillerPhysics::DragForce::GetDrag (void)\fC [inline]\fP"
Returns the current drag coefficient\&. 
.SS "void KillerPhysics::DragForce::SetDrag (\fBreal\fP d)\fC [inline]\fP"
Changes the drag coefficient\&. 
.PP
\fBParameters:\fP
.RS 4
\fId\fP is the new coefficient\&. Drag squared is set to d * d\&. 
.RE
.PP

.SS "void DragForce::v_UpdateForce (shared_ptr< \fBParticle\fP > particle)\fC [final]\fP, \fC [virtual]\fP"
Adds a force to the object based on the drag coefficient and the velocity of the object\&. For details, see the class description\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparticle\fP is the pointer to the object that will have the forced added to it, and will be used to determine what the force is\&. 
.RE
.PP

.PP
Implements \fBKillerPhysics::ForceGenerator\fP\&.
.SS "void DragForce::v_UpdateForce (shared_ptr< \fBRigidBody\fP > body)\fC [final]\fP, \fC [virtual]\fP"
Adds a force to the object based on the drag coefficient and the velocity of the object\&. For details, see the class description\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbody\fP is the pointer to the object that will have the forced added to it, and will be used to determine what the force is\&. 
.RE
.PP

.PP
Implements \fBKillerPhysics::ForceGenerator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
