.TH "KillerEngine::ShaderManager" 3 "Fri Feb 8 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::ShaderManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddShader\fP (U32 id, shared_ptr< \fBShader\fP > shader)"
.br
.ti -1c
.RI "void \fBLoadShader\fP (U32 id, std::vector< \fBShaderData\fP > data)"
.br
.ti -1c
.RI "shared_ptr< \fBShader\fP > \fBGetShader\fP (U32 id)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBShaderManager\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fB_LoadDefaultShaders\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::map< U32, shared_ptr< \fBShader\fP > > \fB_loadedShaders\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBShaderManager\fP > \fB_instance\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
