.TH "KillerMath::Timer" 3 "Sat Jun 15 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerMath::Timer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Timer\fP (void)"
.br
.ti -1c
.RI "void \fBSetClamp\fP (bool state)"
.br
.ti -1c
.RI "bool \fBGetClamp\fP (void) const"
.br
.ti -1c
.RI "void \fBSetPaused\fP (bool paused)"
.br
.ti -1c
.RI "bool \fBGetPaused\fP (void) const"
.br
.ti -1c
.RI "void \fBSetTimeScale\fP (\fBF32\fP scale)"
.br
.ti -1c
.RI "\fBF32\fP \fBGetTimeScale\fP (void) const"
.br
.ti -1c
.RI "\fBreal\fP \fBDeltaTime\fP (void) const"
.br
.ti -1c
.RI "\fBF64\fP \fBTotalTime\fP (void) const"
.br
.ti -1c
.RI "void \fBUpdate\fP (void)"
.br
.ti -1c
.RI "void \fBSingleStep\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBTimer\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTimer\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fB_clamp\fP"
.br
.RI "If clamped, the timer will be forced to lock the framerate at 60 fps\&. "
.ti -1c
.RI "\fBreal\fP \fB_deltaTime\fP"
.br
.RI "The time that the last frame took to run\&. "
.ti -1c
.RI "\fBreal\fP \fB_timeScale\fP"
.br
.RI "A scale factor that is applied to the delta time\&. "
.ti -1c
.RI "\fBF64\fP \fB_totalTime\fP"
.br
.RI "The total time that the program has been running\&. "
.ti -1c
.RI "\fBF64\fP \fB_pastTime\fP"
.br
.RI "The time stamp of the last frame\&. "
.ti -1c
.RI "\fBF64\fP \fB_currentTime\fP"
.br
.RI "The time stamp of this frame\&. "
.ti -1c
.RI "bool \fB_paused\fP"
.br
.RI "If paused, the Update loop will not run, allowing the timer to stop\&. "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBTimer\fP > \fB_instance\fP = NULL"
.br
.RI "Internal reference to self, used in Singleton Pattern\&. "
.in -1c
.SH "Detailed Description"
.PP 
The high precision timer for the Killer1 Engine\&. At the time of writting this the timer is windows specific, but cross platform functionality is planned in the future\&.
.PP
It uses the GLFW function glfwGetTime, located in the GameWindow to get the total time that the glfw window has been open\&. It used to have a customer frequency timer, but this turned out to be too eratic, and was removed\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Timer::~Timer (void)"
Default Destructor\&. Does not do anything\&. 
.SS "Timer::Timer (void)\fC [protected]\fP"
Default Constructor, sets _deltaTime and _totalTime to 0, _timeScale to 1, _pastTime to the current time and _currentTime to _pastTime, and _paused to false\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBreal\fP KillerMath::Timer::DeltaTime (void) const\fC [inline]\fP"
Returns the current _deltaTime\&. 
.SS "bool KillerMath::Timer::GetClamp (void) const\fC [inline]\fP"
Returns the current state of _clamp\&. 
.SS "bool KillerMath::Timer::GetPaused (void) const\fC [inline]\fP"
Returns the state of the _paused flag\&. 
.SS "\fBF32\fP KillerMath::Timer::GetTimeScale (void) const\fC [inline]\fP"
Returns the current value for _timeScale\&. 
.SS "shared_ptr< \fBTimer\fP > Timer::Instance (void)\fC [static]\fP"
Singleton pattern function\&. Returns a pointer to the globabl version of the timer\&. This is the only way to use the timer, ensuring that there will only ever be 1 version of it running\&. 
.SS "void KillerMath::Timer::SetClamp (bool state)\fC [inline]\fP"
Sets the \fBTimer\fP to be clamped\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstate\fP sets the clamp flag\&. 
.RE
.PP

.SS "void KillerMath::Timer::SetPaused (bool paused)\fC [inline]\fP"
Sets the state of the _paused flag\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpaused\fP is the state to set\&. 
.RE
.PP

.SS "void KillerMath::Timer::SetTimeScale (\fBF32\fP scale)\fC [inline]\fP"
Sets the _timeScale variable\&. 
.PP
\fBParameters:\fP
.RS 4
\fIis\fP the new value for _timeScale\&. 
.RE
.PP

.SS "void Timer::SingleStep (void)"
This will attempt to move _deltaTime forward one single frame, at 60 frames per second\&. Note: Maybe this should be updated to be configurable? 
.SS "\fBF64\fP KillerMath::Timer::TotalTime (void) const\fC [inline]\fP"
Returns the total time that the program has been running\&. 
.SS "void Timer::Update (void)"
This updates the _totalTime and _deltaTime values\&. This is where all of the magic happens\&. Should be called once per frame\&. It called GameWindow::GetTime()\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
