.TH "KillerEngine::Sprite" 3 "Sat Jul 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::Sprite
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const U32 \fBGetTextureID\fP (void) const"
.br
.ti -1c
.RI "void \fBSetUVs\fP (const \fBKM::Vector2\fP &bottomTop, const \fBKM::Vector2\fP &leftRight)"
.br
.ti -1c
.RI "const \fBKM::Vector2\fP & \fBGetUVBottomTop\fP (void) const"
.br
.ti -1c
.RI "const \fBKM::Vector2\fP & \fBGetUVLeftRight\fP (void) const"
.br
.ti -1c
.RI "void \fBSetCharData\fP (\fBCharacterData\fP data)"
.br
.ti -1c
.RI "const \fBCharacterData\fP & \fBGetCharData\fP (void) const"
.br
.ti -1c
.RI "const \fBColor\fP & \fBGetColor\fP (void) const"
.br
.ti -1c
.RI "void \fBSetColor\fP (const \fBColor\fP &col)"
.br
.ti -1c
.RI "void \fBSetColor\fP (F32 red, F32 green, F32 blue, F32 alpha=1\&.0f)"
.br
.ti -1c
.RI "const GLuint \fBGetShader\fP (void) const"
.br
.ti -1c
.RI "void \fBInitShader\fP (string filepath)"
.br
.ti -1c
.RI "void \fBSetVAO\fP (GLuint vao)"
.br
.ti -1c
.RI "GLuint \fBGetVAO\fP (void)"
.br
.ti -1c
.RI "U32 \fBGetVertexCount\fP (void)"
.br
.ti -1c
.RI "\fBSprite\fP & \fBoperator=\fP (const \fBSprite\fP &S)"
.br
.ti -1c
.RI "\fBSprite\fP & \fBoperator=\fP (const \fBSprite\fP *S)"
.br
.ti -1c
.RI "\fBSprite\fP & \fBoperator=\fP (shared_ptr< \fBSprite\fP > S)"
.br
.ti -1c
.RI "void \fBSetTexture\fP (U32 tID, const F32 top, const F32 bottom, const F32 right, const F32 left)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fB_InitShader\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBKM::Vector2\fP \fB_bottomTop\fP"
.br
.ti -1c
.RI "\fBKM::Vector2\fP \fB_leftRight\fP"
.br
.ti -1c
.RI "U32 \fB_textureID\fP"
.br
.ti -1c
.RI "\fBCharacterData\fP \fB_characterData\fP"
.br
.ti -1c
.RI "\fBColor\fP \fB_color\fP"
.br
.ti -1c
.RI "GLuint \fB_shaderProgram\fP"
.br
.ti -1c
.RI "GLuint \fB_vao\fP"
.br
.ti -1c
.RI "U32 \fB_vertexCount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
