.TH "KillerMath::Matrix4< T >" 3 "Wed Jan 23 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerMath::Matrix4< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrix4\fP (T val)"
.br
.ti -1c
.RI "\fBMatrix4\fP (const T mSrc[16])"
.br
.ti -1c
.RI "\fBMatrix4\fP (T m00, T m01, T m02, T m03, T m10, T m11, T m12, T m13, T m20, T m21, T m22, T m23, T m30, T m31, T m32, T m33)"
.br
.ti -1c
.RI "void \fBMakeOrthographic\fP (T width, T height, T depth)"
.br
.ti -1c
.RI "const T * \fBGetElems\fP (void) const"
.br
.ti -1c
.RI "T \fBGet11\fP (void) const"
.br
.ti -1c
.RI "T \fBGet12\fP (void) const"
.br
.ti -1c
.RI "T \fBGet13\fP (void) const"
.br
.ti -1c
.RI "T \fBGet14\fP (void) const"
.br
.ti -1c
.RI "T \fBGet21\fP (void) const"
.br
.ti -1c
.RI "T \fBGet22\fP (void) const"
.br
.ti -1c
.RI "T \fBGet23\fP (void) const"
.br
.ti -1c
.RI "T \fBGet24\fP (void) const"
.br
.ti -1c
.RI "T \fBGet31\fP (void) const"
.br
.ti -1c
.RI "T \fBGet32\fP (void) const"
.br
.ti -1c
.RI "T \fBGet33\fP (void) const"
.br
.ti -1c
.RI "T \fBGet34\fP (void) const"
.br
.ti -1c
.RI "T \fBGet41\fP (void) const"
.br
.ti -1c
.RI "T \fBGet42\fP (void) const"
.br
.ti -1c
.RI "T \fBGet43\fP (void) const"
.br
.ti -1c
.RI "T \fBGet44\fP (void) const"
.br
.ti -1c
.RI "\fBMatrix4\fP< T > & \fBoperator=\fP (const \fBMatrix4\fP< T > &M)"
.br
.ti -1c
.RI "\fBMatrix4\fP< T > \fBoperator*\fP (const \fBMatrix4\fP< T > &RHM)"
.br
.ti -1c
.RI "\fBMatrix4\fP< T > & \fBoperator*=\fP (\fBMatrix4\fP< T > &RHM)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "T \fB_m\fP [16]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
