.TH "KillerEngine::SpriteRenderer" 3 "Thu Aug 9 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::SpriteRenderer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetBatchSize\fP (U32 size)"
.br
.ti -1c
.RI "const GLuint \fBGetShader\fP (void)"
.br
.ti -1c
.RI "void \fBSetShader\fP (GLuint shader)"
.br
.ti -1c
.RI "void \fBSetBackgroundColor\fP (\fBColor\fP &c)"
.br
.ti -1c
.RI "void \fBAddToBatch\fP (const \fBKM::Vector2\fP &pos, F32 w, F32 h, const \fBColor\fP &c)"
.br
.ti -1c
.RI "void \fBAddToBatch\fP (const \fBKM::Vector2\fP &pos, F32 w, F32 h, const \fBColor\fP &c, U32 textureID)"
.br
.ti -1c
.RI "void \fBAddToBatch\fP (const \fBKM::Vector2\fP &pos, F32 w, F32 h, const \fBColor\fP &c, U32 textureID, const \fBKM::Vector2\fP &verticalLimit, const \fBKM::Vector2\fP &horizontalLimit)"
.br
.ti -1c
.RI "void \fBAddToBatch\fP (std::vector< F32 > v, std::vector< F32 > c)"
.br
.ti -1c
.RI "void \fBAddTextureToBatch\fP (std::vector< F32 > v, std::vector< F32 > uv)"
.br
.ti -1c
.RI "void \fBDraw\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBSpriteRenderer\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "U32 \fB_maxBatchSize\fP"
.br
.ti -1c
.RI "U32 \fB_currentBatchSize\fP"
.br
.ti -1c
.RI "std::vector< F32 > \fB_vertices\fP"
.br
.ti -1c
.RI "std::vector< F32 > \fB_colors\fP"
.br
.ti -1c
.RI "std::vector< F32 > \fB_dimensions\fP"
.br
.ti -1c
.RI "std::vector< F32 > \fB_bottomTop\fP"
.br
.ti -1c
.RI "std::vector< F32 > \fB_leftRight\fP"
.br
.ti -1c
.RI "GLuint \fB_renderingProgramColor\fP"
.br
.ti -1c
.RI "GLuint \fB_renderingProgramTexture\fP"
.br
.ti -1c
.RI "GLuint \fB_vertexArrayObject\fP [NUM_VOA]"
.br
.ti -1c
.RI "GLuint \fB_shader\fP"
.br
.ti -1c
.RI "U32 \fB_shaderSetCount\fP"
.br
.ti -1c
.RI "U32 \fB_drawCount\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBSpriteRenderer\fP > \fB_instance\fP {NULL}"
.br
.ti -1c
.RI "static const U32 \fBNUM_VOA\fP = 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
