.TH "KillerPhysics::GravityForce" 3 "Sat Jun 15 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::GravityForce
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GravityForce\&.h>\fP
.PP
Inherits \fBKillerPhysics::ForceGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGravityForce\fP (void)"
.br
.ti -1c
.RI "\fBGravityForce\fP (const \fBKM::Vector4\fP &gravity)"
.br
.ti -1c
.RI "\fB~GravityForce\fP (void)"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (p_RigidBody2D body) final"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (p_RigidBody3D body) final"
.br
.ti -1c
.RI "void \fBSet\fP (\fBKM::Vector4\fP &gravity)"
.br
.ti -1c
.RI "void \fBSet\fP (\fBF32\fP xVal, \fBF32\fP yVal, \fBF32\fP zVal)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBKM::Vector4\fP \fB_gravityAcc\fP"
.br
.RI "The acceleration saved for this force\&. "
.in -1c
.SH "Detailed Description"
.PP 
A physics \fBForceGenerator\fP for \fBRigidBody2D\fP and \fBRigidBody3D\fP objects which simulates Gravity\&. By default this is set to -y\&.
.PP
It is based on the Cyclone engine design found in 'Game Physics Engine Development, second edition' by Ian Millington\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GravityForce::GravityForce (void)"
Sets default acceleration to 0, -1, 0\&. 
.SS "GravityForce::GravityForce (const \fBKM::Vector4\fP & gravity)"
Sets acceleration to \fBKillerMath::Vector4\fP sent in\&. 
.PP
\fBParameters:\fP
.RS 4
\fIgravity\fP will be the value set for the acceleration\&. 
.RE
.PP

.SS "GravityForce::~GravityForce (void)"
No implemenation\&. 
.SH "Member Function Documentation"
.PP 
.SS "void KillerPhysics::GravityForce::Set (\fBKM::Vector4\fP & gravity)\fC [inline]\fP"
Changes the acceleration the force will cause on an object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIgravity\fP is the new acceleration\&. 
.RE
.PP

.SS "void KillerPhysics::GravityForce::Set (\fBF32\fP xVal, \fBF32\fP yVal, \fBF32\fP zVal)\fC [inline]\fP"
Changes the acceleration the force will cause on an object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIxVal\fP is the new acceration along the x axis; 
.br
\fIyVal\fP is the new acceration along the y axis; 
.br
\fIzVal\fP is the new acceration along the z axis; 
.RE
.PP

.SS "void GravityForce::v_UpdateForce (p_RigidBody2D body)\fC [final]\fP, \fC [virtual]\fP"
If body does not have infinite mass, the acceleration is added using \fBKillerPhysics::RigidBody2D::AddForce\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbody\fP is the pointer to the object that will have the acceleration added to it\&. 
.RE
.PP

.PP
Implements \fBKillerPhysics::ForceGenerator\fP\&.
.SS "void GravityForce::v_UpdateForce (p_RigidBody3D body)\fC [final]\fP, \fC [virtual]\fP"
If body does not have infinite mass, the acceleration is added using KillerPhysics::RigidBody3D::AddForce\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbody\fP is the pointer to the object that will have the acceleration added to it\&. 
.RE
.PP

.PP
Implements \fBKillerPhysics::ForceGenerator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
