.TH "KillerEngine::Shader" 3 "Tue Jul 10 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::Shader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetVertexPath\fP (string path)"
.br
.ti -1c
.RI "void \fBSetTesselationPath\fP (string path)"
.br
.ti -1c
.RI "void \fBSetGeometryPath\fP (string path)"
.br
.ti -1c
.RI "void \fBSetFragmentPath\fP (string path)"
.br
.ti -1c
.RI "void \fBInitSpriteShader\fP (void)"
.br
.ti -1c
.RI "void \fBInitModelShader\fP (void)"
.br
.ti -1c
.RI "GLuint \fBCreateShader\fP (void)"
.br
.ti -1c
.RI "GLuint \fBGetSpriteShader\fP (void)"
.br
.ti -1c
.RI "GLuint \fBGetModelShader\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBShader\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "string \fB_GetFileString\fP (string path)"
.br
.ti -1c
.RI "bool \fB_CheckCompileErrors\fP (GLuint shader)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "GLuint \fB_spriteShader\fP"
.br
.ti -1c
.RI "GLuint \fB_modelShader\fP"
.br
.ti -1c
.RI "string \fB_vertexPath\fP"
.br
.ti -1c
.RI "string \fB_tessellationPath\fP"
.br
.ti -1c
.RI "string \fB_geometryPath\fP"
.br
.ti -1c
.RI "string \fB_fragmentPath\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBShader\fP > \fB_instance\fP = NULL"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
