.TH "KillerEngine::EnvironmentObject" 3 "Sat Jun 1 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::EnvironmentObject
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EnvironmentObject\&.h>\fP
.PP
Inherits \fBKillerEngine::GameObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnvironmentObject\fP (void)"
.br
.ti -1c
.RI "\fBEnvironmentObject\fP (const \fBKM::Point\fP &pos, \fBF32\fP w, \fBF32\fP h)"
.br
.ti -1c
.RI "\fB~EnvironmentObject\fP (void)"
.br
.ti -1c
.RI "void \fBv_Update\fP (void) final"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is an implementation of a \fBGameObject\fP which will reprents static, unmoving background objects which the player will not be allowed to pass through\&. These are things like rocks, trees, houses, etc\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EnvironmentObject::EnvironmentObject (void)"
Default Constructor\&. No special actions taken\&. 
.SS "EnvironmentObject::EnvironmentObject (const \fBKM::Point\fP & pos, \fBF32\fP w, \fBF32\fP h)"
Calls GameObject::SetPosition and GameObject::SetDimensions\&. 
.SS "EnvironmentObject::~EnvironmentObject (void)"
Default Destructor\&. No special action taken\&. 
.SH "Member Function Documentation"
.PP 
.SS "void KillerEngine::EnvironmentObject::v_Update (void)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"
Empty function, needed because its a pure virtual function\&. 
.PP
Implements \fBKillerEngine::GameObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
