.TH "KillerPhysics::ParticleDragForce" 3 "Mon Feb 11 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ParticleDragForce
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerPhysics::ForceGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticleDragForce\fP (real drag, real dragSqr)"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (shared_ptr< \fBParticle\fP > particle) final"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "real \fB_drag\fP"
.br
.ti -1c
.RI "real \fB_dragSqr\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ParticleDragForce::v_UpdateForce (shared_ptr< \fBParticle\fP > particle)\fC [final]\fP, \fC [virtual]\fP"
Unimplemented virtual function\&. Each force defines what happens during an update\&. This is the part that will make the forces different\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparticle\fP defines this as the \fBParticle\fP object version\&. 
.RE
.PP

.PP
Implements \fBKillerPhysics::ForceGenerator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
