.TH "KillerEngine::RenderedCharacter" 3 "Thu Jun 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::RenderedCharacter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "U32 \fBGetID\fP (void)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (const \fBKM::Vector2\fP &pos)"
.br
.ti -1c
.RI "const \fBKM::Vector2\fP & \fBGetPosition\fP (void) const"
.br
.ti -1c
.RI "void \fBSetWidth\fP (F32 w)"
.br
.ti -1c
.RI "F32 \fBGetWidth\fP (void)"
.br
.ti -1c
.RI "F32 \fBSetPosition\fP (void)"
.br
.ti -1c
.RI "void \fBSetHeight\fP (F32 h)"
.br
.ti -1c
.RI "F32 \fBGetHeight\fP (void)"
.br
.ti -1c
.RI "void \fBSetDimensions\fP (F32 w, F32 h)"
.br
.ti -1c
.RI "void \fBSetSprite\fP (shared_ptr< \fBSprite\fP > sprite)"
.br
.ti -1c
.RI "void \fBSetSprite\fP (const \fBSprite\fP &sprite)"
.br
.ti -1c
.RI "const \fBSprite\fP & \fBGetSprite\fP (void) const"
.br
.ti -1c
.RI "void \fBSetColor\fP (const \fBColor\fP &col)"
.br
.ti -1c
.RI "const \fBColor\fP & \fBGetColor\fP (void) const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "U32 \fB_id\fP"
.br
.ti -1c
.RI "\fBKM::Vector2\fP \fB_pos\fP"
.br
.ti -1c
.RI "F32 \fB_width\fP"
.br
.ti -1c
.RI "F32 \fB_height\fP"
.br
.ti -1c
.RI "\fBSprite\fP \fB_sprite\fP"
.br
.ti -1c
.RI "\fBColor\fP \fB_color\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static U32 \fB_nextId\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
