.TH "KillerEngine::ShaderData" 3 "Sun Jan 13 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::ShaderData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBfilePath\fP"
.br
.ti -1c
.RI "ShaderType \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
