.TH "KillerPhysics::ForceRegistry::_RigidBodyRegistration" 3 "Mon Feb 11 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ForceRegistry::_RigidBodyRegistration
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (\fB_RigidBodyRegistration\fP b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "shared_ptr< \fBRigidBody\fP > \fBbody\fP"
.br
.RI "Pointer to object saved to add force to later\&. "
.ti -1c
.RI "shared_ptr< \fBForceGenerator\fP > \fBforceGen\fP"
.br
.RI "Pointer to force saved to be added to object later\&. "
.in -1c
.SH "Detailed Description"
.PP 
Private struct type that pairs a single \fBRigidBody\fP with a ForceGenerators\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool KillerPhysics::ForceRegistry::_RigidBodyRegistration::operator== (\fB_RigidBodyRegistration\fP b)\fC [inline]\fP"
Returns true if another registration matches this one\&. 
.PP
\fBParameters:\fP
.RS 4
\fIb\fP is the registration to be compared against\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
