.TH "KillerEngine::EngineFactory" 3 "Sat Jun 15 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::EngineFactory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "p_Glyph \fBMakeGlyph\fP (void)"
.br
.ti -1c
.RI "KP::p_RigidBody2D \fBMakeRigidBody2D\fP (void)"
.br
.ti -1c
.RI "KP::p_RigidBody3D \fBMakeRigidBody3D\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBEngineFactory\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBEngineFactory\fP > \fB_instance\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
