.TH "KillerPhysics::ParticleGravityForce" 3 "Sun Jun 3 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ParticleGravityForce
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerPhysics::ParticleForceGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticleGravityForce\fP (const \fBKM::Vector2\fP &gravity)"
.br
.ti -1c
.RI "\fBParticleGravityForce\fP (const \fBKM::Vector3\fP &gravity)"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (shared_ptr< \fBParticle2D\fP > particle) final"
.br
.ti -1c
.RI "void \fBv_UpdateForce\fP (shared_ptr< \fBParticle3D\fP > particle) final"
.br
.ti -1c
.RI "void \fBSetGravityAcceleration\fP (\fBKM::Vector2\fP &gravity)"
.br
.ti -1c
.RI "void \fBSetGravityAcceleration\fP (\fBKM::Vector3\fP &gravity)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
