.TH "KillerPhysics::ParticleContact" 3 "Tue May 14 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::ParticleContact
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetRestitution\fP (\fBreal\fP restitution)"
.br
.ti -1c
.RI "void \fBSetContactNormal\fP (\fBKM::Vector4\fP &normal)"
.br
.ti -1c
.RI "void \fBSetContacts\fP (shared_ptr< \fBParticle\fP > particle1, shared_ptr< \fBParticle\fP > particle2=nullptr)"
.br
.ti -1c
.RI "void \fBSetPenetration\fP (\fBreal\fP penetration)"
.br
.ti -1c
.RI "\fBreal\fP \fBGetPenetration\fP (void)"
.br
.ti -1c
.RI "const shared_ptr< \fBParticle\fP > \fBGetParticleOne\fP (void)"
.br
.ti -1c
.RI "const shared_ptr< \fBParticle\fP > \fBGetParticleTwo\fP (void)"
.br
.ti -1c
.RI "void \fBResolve\fP (void)"
.br
.ti -1c
.RI "\fBreal\fP \fBCalculateSeparatingVelocity\fP (void) const"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fB_ResolveImpulseVelocity\fP (void)"
.br
.ti -1c
.RI "void \fB_ResolveInterpenetration\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "shared_ptr< \fBParticle\fP > \fB_particles\fP [2]"
.br
.ti -1c
.RI "shared_ptr< \fBKM::Vector4\fP > \fB_particleMovements\fP [2]"
.br
.ti -1c
.RI "\fBKM::Vector4\fP \fB_contactNormal\fP"
.br
.ti -1c
.RI "\fBreal\fP \fB_restitution\fP"
.br
.ti -1c
.RI "\fBreal\fP \fB_penetration\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
