.TH "KillerEngine::Vertex2D" 3 "Thu Aug 9 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::Vertex2D
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVertex2D\fP (\fBKM::Vector2\fP pos)"
.br
.ti -1c
.RI "\fBVertex2D\fP (\fBKM::Vector2\fP pos, \fBColor\fP col)"
.br
.ti -1c
.RI "\fBVertex2D\fP (\fBKM::Vector2\fP pos, \fBKM::Vector2\fP uvCoords, \fBColor\fP col)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKM::Vector2\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBKM::Vector2\fP \fBtexCoord\fP"
.br
.ti -1c
.RI "\fBColor\fP \fBcolor\fP"
.br
.ti -1c
.RI "S32 \fBtexID\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
