.TH "KillerEngine::TextureManager" 3 "Wed Jun 6 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::TextureManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "U32 \fBGetCurrentTextureID\fP (void)"
.br
.ti -1c
.RI "void \fBSetCurrentTextureID\fP (U32 textureId)"
.br
.ti -1c
.RI "void \fBLoadTexture\fP (string path, U32 id, S32 width, S32 height)"
.br
.ti -1c
.RI "const shared_ptr< \fBTexture\fP > \fBGetTexture\fP (U32 id)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBTextureManager\fP > \fBInstance\fP (void)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
