.TH "KillerPhysics::Particle" 3 "Mon Jan 14 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerPhysics::Particle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKillerEngine::GameObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticle\fP (const \fBParticle\fP *particle)"
.br
.ti -1c
.RI "\fBParticle\fP (const \fBParticle\fP &particle)"
.br
.ti -1c
.RI "virtual void \fBv_Update\fP ()"
.br
.ti -1c
.RI "void \fBIntegrate\fP (void)"
.br
.ti -1c
.RI "void \fBClearAccumulator\fP (void)"
.br
.ti -1c
.RI "void \fBAddForce\fP (const \fBKM::Vector\fP force)"
.br
.ti -1c
.RI "const \fBKM::Vector\fP & \fBGetVelocity\fP (void) const"
.br
.ti -1c
.RI "void \fBSetVelocity\fP (const \fBKM::Vector\fP &vel)"
.br
.ti -1c
.RI "void \fBSetVelocity\fP (F32 x, F32 y)"
.br
.ti -1c
.RI "void \fBSetVelocity\fP (F32 x, F32 y, F32 z)"
.br
.ti -1c
.RI "void \fBAddScaledVelocity\fP (const \fBKM::Vector\fP &vec, F32 scale)"
.br
.ti -1c
.RI "const \fBKM::Vector\fP & \fBGetAcceleration\fP (void) const"
.br
.ti -1c
.RI "void \fBSetAcceleration\fP (const \fBKM::Vector\fP &acc)"
.br
.ti -1c
.RI "void \fBSetAcceleration\fP (F32 x, F32 y)"
.br
.ti -1c
.RI "void \fBSetAcceleration\fP (F32 x, F32 y, F32 z)"
.br
.ti -1c
.RI "void \fBAddScaledAcceleration\fP (const \fBKM::Vector\fP &acc, F32 scale)"
.br
.ti -1c
.RI "const \fBKM::Vector\fP & \fBGetForces\fP (void) const"
.br
.ti -1c
.RI "const \fBKM::Vector\fP & \fBGetGravityForce\fP (void) const"
.br
.ti -1c
.RI "void \fBSetGravityForce\fP (const \fBKM::Vector\fP &grav)"
.br
.ti -1c
.RI "const real \fBGetInverseMass\fP (void) const"
.br
.ti -1c
.RI "void \fBSetInverseMass\fP (real inverseMass)"
.br
.ti -1c
.RI "bool \fBHasFiniteMass\fP (void)"
.br
.ti -1c
.RI "const real \fBGetMass\fP (void)"
.br
.ti -1c
.RI "void \fBSetMass\fP (real mass)"
.br
.ti -1c
.RI "const real \fBGetDamping\fP (void) const"
.br
.ti -1c
.RI "void \fBSetDamping\fP (real damp)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBKM::Vector\fP \fB_velocity\fP"
.br
.ti -1c
.RI "\fBKM::Vector\fP \fB_acceleration\fP"
.br
.ti -1c
.RI "\fBKM::Vector\fP \fB_forceAccum\fP"
.br
.ti -1c
.RI "\fBKM::Vector\fP \fB_gravityForce\fP"
.br
.ti -1c
.RI "real \fB_inverseMass\fP"
.br
.ti -1c
.RI "real \fB_damping\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
