.TH "KillerEngine::WinProgram" 3 "Mon Jun 4 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KillerEngine::WinProgram
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "HINSTANCE \fBGetHINSTANCE\fP (void)"
.br
.ti -1c
.RI "HWND \fBGetHWND\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetWidth\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetRight\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetLeft\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetHeight\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetTop\fP (void)"
.br
.ti -1c
.RI "S32 \fBGetBottom\fP (void)"
.br
.ti -1c
.RI "void \fBInit\fP (S32 width, S32 height, string wndName, bool isFullScreen)"
.br
.RI "Sets up Windows Program\&. "
.ti -1c
.RI "void \fBProcessWndEvents\fP (void)"
.br
.ti -1c
.RI "Keys \fBConvertKeyCodes\fP (WPARAM wParam)"
.br
.ti -1c
.RI "void \fBBufferSwap\fP (void)"
.br
.ti -1c
.RI "void \fBSetBackgroundColor\fP (const \fBColor\fP &c)"
.br
.ti -1c
.RI "LRESULT CALLBACK \fBWndProc\fP (HWND wnd, UINT msg, WPARAM wParam, LPARAM lParam)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBWinProgram\fP > \fBInstance\fP (void)"
.br
.ti -1c
.RI "static LRESULT CALLBACK \fBStaticWndProc\fP (HWND wnd, UINT msg, WPARAM wParam, LPARAM lParam)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void WinProgram::Init (S32 width, S32 height, string wndName, bool isFullScreen)"

.PP
Sets up Windows Program\&. Makes all calls needed to start up a window\&. This is means to abstract away system specific callls 
.PP
\fBParameters:\fP
.RS 4
\fIwidth\fP S32: width of created window 
.br
\fIheight\fP S32: height of created window 
.br
\fIwndName\fP string: title of window 
.br
\fIisFullScreen\fP bool: Sets if the system makes the window fullscreen 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
