.TH "F:/Projects/Killer_Engine/Headers/Engine/LevelManager.h" 3 "Wed Jun 6 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Projects/Killer_Engine/Headers/Engine/LevelManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <Engine/Atom\&.h>\fP
.br
\fC#include <Engine/Level\&.h>\fP
.br
\fC#include <Engine/GameObject2D\&.h>\fP
.br
\fC#include <Engine/ErrorManager\&.h>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKillerEngine::LevelManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBKillerEngine\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
