.TH "mods" 3 "Thu Aug 9 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mods
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_MOD_SHIFT\fP   0x0001"
.br
.RI "If this bit is set one or more Shift keys were held down\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_CONTROL\fP   0x0002"
.br
.RI "If this bit is set one or more Control keys were held down\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_ALT\fP   0x0004"
.br
.RI "If this bit is set one or more Alt keys were held down\&. "
.ti -1c
.RI "#define \fBGLFW_MOD_SUPER\fP   0x0008"
.br
.RI "If this bit is set one or more Super keys were held down\&. "
.in -1c
.SH "Detailed Description"
.PP 
See \fBkey input\fP for how these are used\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
