.TH "PS_BlendRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_BlendRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBnum_designs\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_axis\fP"
.br
.ti -1c
.RI "FT_String * \fBaxis_names\fP [T1_MAX_MM_AXIS]"
.br
.ti -1c
.RI "FT_Fixed * \fBdesign_pos\fP [T1_MAX_MM_DESIGNS]"
.br
.ti -1c
.RI "\fBPS_DesignMapRec\fP \fBdesign_map\fP [T1_MAX_MM_AXIS]"
.br
.ti -1c
.RI "FT_Fixed * \fBweight_vector\fP"
.br
.ti -1c
.RI "FT_Fixed * \fBdefault_weight_vector\fP"
.br
.ti -1c
.RI "\fBPS_FontInfo\fP \fBfont_infos\fP [T1_MAX_MM_DESIGNS+1]"
.br
.ti -1c
.RI "\fBPS_Private\fP \fBprivates\fP [T1_MAX_MM_DESIGNS+1]"
.br
.ti -1c
.RI "FT_ULong \fBblend_bitflags\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP * \fBbboxes\fP [T1_MAX_MM_DESIGNS+1]"
.br
.ti -1c
.RI "FT_UInt \fBdefault_design_vector\fP [T1_MAX_MM_DESIGNS]"
.br
.ti -1c
.RI "FT_UInt \fBnum_default_design_vector\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
