.TH "PS_DesignMap_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_DesignMap_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBnum_points\fP"
.br
.ti -1c
.RI "FT_Long * \fBdesign_points\fP"
.br
.ti -1c
.RI "FT_Fixed * \fBblend_points\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
