.TH "PS_FontInfoRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_FontInfoRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_String * \fBversion\fP"
.br
.ti -1c
.RI "FT_String * \fBnotice\fP"
.br
.ti -1c
.RI "FT_String * \fBfull_name\fP"
.br
.ti -1c
.RI "FT_String * \fBfamily_name\fP"
.br
.ti -1c
.RI "FT_String * \fBweight\fP"
.br
.ti -1c
.RI "FT_Long \fBitalic_angle\fP"
.br
.ti -1c
.RI "FT_Bool \fBis_fixed_pitch\fP"
.br
.ti -1c
.RI "FT_Short \fBunderline_position\fP"
.br
.ti -1c
.RI "FT_UShort \fBunderline_thickness\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
