.TH "PS_PrivateRec_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_PrivateRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Int \fBunique_id\fP"
.br
.ti -1c
.RI "FT_Int \fBlenIV\fP"
.br
.ti -1c
.RI "FT_Byte \fBnum_blue_values\fP"
.br
.ti -1c
.RI "FT_Byte \fBnum_other_blues\fP"
.br
.ti -1c
.RI "FT_Byte \fBnum_family_blues\fP"
.br
.ti -1c
.RI "FT_Byte \fBnum_family_other_blues\fP"
.br
.ti -1c
.RI "FT_Short \fBblue_values\fP [14]"
.br
.ti -1c
.RI "FT_Short \fBother_blues\fP [10]"
.br
.ti -1c
.RI "FT_Short \fBfamily_blues\fP [14]"
.br
.ti -1c
.RI "FT_Short \fBfamily_other_blues\fP [10]"
.br
.ti -1c
.RI "FT_Fixed \fBblue_scale\fP"
.br
.ti -1c
.RI "FT_Int \fBblue_shift\fP"
.br
.ti -1c
.RI "FT_Int \fBblue_fuzz\fP"
.br
.ti -1c
.RI "FT_UShort \fBstandard_width\fP [1]"
.br
.ti -1c
.RI "FT_UShort \fBstandard_height\fP [1]"
.br
.ti -1c
.RI "FT_Byte \fBnum_snap_widths\fP"
.br
.ti -1c
.RI "FT_Byte \fBnum_snap_heights\fP"
.br
.ti -1c
.RI "FT_Bool \fBforce_bold\fP"
.br
.ti -1c
.RI "FT_Bool \fBround_stem_up\fP"
.br
.ti -1c
.RI "FT_Short \fBsnap_widths\fP [13]"
.br
.ti -1c
.RI "FT_Short \fBsnap_heights\fP [13]"
.br
.ti -1c
.RI "FT_Fixed \fBexpansion_factor\fP"
.br
.ti -1c
.RI "FT_Long \fBlanguage_group\fP"
.br
.ti -1c
.RI "FT_Long \fBpassword\fP"
.br
.ti -1c
.RI "FT_Short \fBmin_feature\fP [2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
