.TH "rapidxml::xml_document< Ch >::attribute_value_pred< Quote >" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rapidxml::xml_document< Ch >::attribute_value_pred< Quote >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned char \fBtest\fP (Ch ch)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
