.TH "rapidxml::xml_document< Ch >" 3 "Mon Mar 2 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rapidxml::xml_document< Ch >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rapidxml\&.hpp>\fP
.PP
Inherits \fBrapidxml::xml_node< Ch >\fP, and \fBrapidxml::memory_pool< Ch >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBattribute_name_pred\fP"
.br
.ti -1c
.RI "struct \fBattribute_value_pred\fP"
.br
.ti -1c
.RI "struct \fBattribute_value_pure_pred\fP"
.br
.ti -1c
.RI "struct \fBnode_name_pred\fP"
.br
.ti -1c
.RI "struct \fBtext_pred\fP"
.br
.ti -1c
.RI "struct \fBtext_pure_no_ws_pred\fP"
.br
.ti -1c
.RI "struct \fBtext_pure_with_ws_pred\fP"
.br
.ti -1c
.RI "struct \fBwhitespace_pred\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBxml_document\fP ()"
.br
.RI "Constructs empty XML document\&. "
.ti -1c
.RI "template<int Flags> void \fBparse\fP (Ch *text)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<int Flags> void \fBparse_bom\fP (Ch *&text)"
.br
.ti -1c
.RI "template<int Flags> \fBxml_node\fP< Ch > * \fBparse_xml_declaration\fP (Ch *&text)"
.br
.ti -1c
.RI "template<int Flags> \fBxml_node\fP< Ch > * \fBparse_comment\fP (Ch *&text)"
.br
.ti -1c
.RI "template<int Flags> \fBxml_node\fP< Ch > * \fBparse_doctype\fP (Ch *&text)"
.br
.ti -1c
.RI "template<int Flags> \fBxml_node\fP< Ch > * \fBparse_pi\fP (Ch *&text)"
.br
.ti -1c
.RI "template<int Flags> Ch \fBparse_and_append_data\fP (\fBxml_node\fP< Ch > *node, Ch *&text, Ch *contents_start)"
.br
.ti -1c
.RI "template<int Flags> \fBxml_node\fP< Ch > * \fBparse_cdata\fP (Ch *&text)"
.br
.ti -1c
.RI "template<int Flags> \fBxml_node\fP< Ch > * \fBparse_element\fP (Ch *&text)"
.br
.ti -1c
.RI "template<int Flags> \fBxml_node\fP< Ch > * \fBparse_node\fP (Ch *&text)"
.br
.ti -1c
.RI "template<int Flags> void \fBparse_node_contents\fP (Ch *&text, \fBxml_node\fP< Ch > *node)"
.br
.ti -1c
.RI "template<int Flags> void \fBparse_node_attributes\fP (Ch *&text, \fBxml_node\fP< Ch > *node)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "template<int Flags> static void \fBinsert_coded_character\fP (Ch *&text, unsigned long code)"
.br
.ti -1c
.RI "template<class StopPred , int Flags> static void \fBskip\fP (Ch *&text)"
.br
.ti -1c
.RI "template<class StopPred , class StopPredPure , int Flags> static Ch * \fBskip_and_expand_character_refs\fP (Ch *&text)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<class Ch = char>
.br
class rapidxml::xml_document< Ch >"
This class represents root of the DOM hierarchy\&. It is also an \fBxml_node\fP and a \fBmemory_pool\fP through public inheritance\&. Use \fBparse()\fP function to build a DOM tree from a zero-terminated XML text string\&. \fBparse()\fP function allocates memory for nodes and attributes by using functions of \fBxml_document\fP, which are inherited from \fBmemory_pool\fP\&. To access root node of the document, use the document itself, as if it was an \fBxml_node\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fICh\fP Character type to use\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class Ch  = char> void \fBrapidxml::xml_document\fP< Ch >::clear ()\fC [inline]\fP"
Clears the document by deleting all nodes and clearing the memory pool\&. All nodes owned by document pool are destroyed\&. 
.SS "template<class Ch  = char> template<int Flags> void \fBrapidxml::xml_document\fP< Ch >::parse (Ch * text)\fC [inline]\fP"
Parses zero-terminated XML string according to given flags\&. Passed string will be modified by the parser, unless rapidxml::parse_non_destructive flag is used\&. The string must persist for the lifetime of the document\&. In case of error, \fBrapidxml::parse_error\fP exception will be thrown\&. 
.br

.br
 If you want to parse contents of a file, you must first load the file into the memory, and pass pointer to its beginning\&. Make sure that data is zero-terminated\&. 
.br

.br
 Document can be parsed into multiple times\&. Each new call to parse removes previous nodes and attributes (if any), but does not clear memory pool\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP XML data to parse; pointer is non-const to denote fact that this data may be modified by the parser\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
