.TH "rapidxml::xml_document< Ch >::attribute_name_pred" 3 "Tue Jan 7 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rapidxml::xml_document< Ch >::attribute_name_pred
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned char \fBtest\fP (Ch ch)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
