.TH "F:/Projects/Killer_Engine/Implementations/RenderedCharacter.cpp" 3 "Wed Jun 6 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Projects/Killer_Engine/Implementations/RenderedCharacter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <Engine/RenderedCharacter\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static \fBU32\fP \fB_nextID\fP = 1"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBU32\fP _nextID = 1\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
