.TH "shapes" 3 "Sat Jul 7 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shapes
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_ARROW_CURSOR\fP   0x00036001"
.br
.RI "The regular arrow cursor shape\&. "
.ti -1c
.RI "#define \fBGLFW_IBEAM_CURSOR\fP   0x00036002"
.br
.RI "The text input I-beam cursor shape\&. "
.ti -1c
.RI "#define \fBGLFW_CROSSHAIR_CURSOR\fP   0x00036003"
.br
.RI "The crosshair shape\&. "
.ti -1c
.RI "#define \fBGLFW_HAND_CURSOR\fP   0x00036004"
.br
.RI "The hand shape\&. "
.ti -1c
.RI "#define \fBGLFW_HRESIZE_CURSOR\fP   0x00036005"
.br
.RI "The horizontal resize arrow shape\&. "
.ti -1c
.RI "#define \fBGLFW_VRESIZE_CURSOR\fP   0x00036006"
.br
.RI "The vertical resize arrow shape\&. "
.in -1c
.SH "Detailed Description"
.PP 
See \fBstandard cursor creation\fP for how these are used\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLFW_ARROW_CURSOR   0x00036001"

.PP
The regular arrow cursor shape\&. The regular arrow cursor\&. 
.SS "#define GLFW_CROSSHAIR_CURSOR   0x00036003"

.PP
The crosshair shape\&. The crosshair shape\&. 
.SS "#define GLFW_HAND_CURSOR   0x00036004"

.PP
The hand shape\&. The hand shape\&. 
.SS "#define GLFW_HRESIZE_CURSOR   0x00036005"

.PP
The horizontal resize arrow shape\&. The horizontal resize arrow shape\&. 
.SS "#define GLFW_IBEAM_CURSOR   0x00036002"

.PP
The text input I-beam cursor shape\&. The text input I-beam cursor shape\&. 
.SS "#define GLFW_VRESIZE_CURSOR   0x00036006"

.PP
The vertical resize arrow shape\&. The vertical resize arrow shape\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
