.TH "Tempest::Glyph" 3 "Wed Jan 8 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::Glyph
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Glyph\&.h>\fP
.PP
Inherits \fBTempest::GameObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "TEMPEST_API \fBGlyph\fP (void)"
.br
.RI "No special behavior\&. "
.ti -1c
.RI "TEMPEST_API \fBGlyph\fP (const \fBGlyph\fP &glyph)"
.br
.RI "Copies data from getters\&. "
.ti -1c
.RI "TEMPEST_API \fB~Glyph\fP (void)"
.br
.RI "No special behavior\&. "
.ti -1c
.RI "void \fBv_Update\fP (void) final"
.br
.RI "Needed virtual function from \fBGameObject\fP\&. Empty implementation\&. "
.ti -1c
.RI "TEMPEST_API void \fBv_Render\fP (void) final"
.br
.ti -1c
.RI "TEMPEST_API void \fBInit\fP (void)"
.br
.RI "Initializes the \fBGlyph\fP as a sprite, sets \fBGlyph\fP shader\&. "
.ti -1c
.RI "void \fBSetCharacter\fP (char character, shared_ptr< \fBTexture\fP > tex, const \fBCharacterData\fP &characterData)"
.br
.ti -1c
.RI "void \fBSetCharacter\fP (char character, const \fBCharacterData\fP &characterData)"
.br
.ti -1c
.RI "char \fBGetCharacter\fP (void) const"
.br
.RI "Returns the raw character\&. "
.ti -1c
.RI "\fBCharacterData\fP \fBGetCharacterData\fP (void) const"
.br
.RI "Returns the \fBCharacterData\fP for the \fBGlyph\fP\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "char \fB_character\fP"
.br
.RI "Raw character that the \fBGlyph\fP represents on screen\&. "
.ti -1c
.RI "\fBCharacterData\fP \fB_characterData\fP"
.br
.RI "Various data needed to render and position the \fBGlyph\fP\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A sprite based UI character to be rendered at run time\&. It gets its data from a \fBFont\fP, which informs it of its size and its texture\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Tempest::Glyph::SetCharacter (char character, shared_ptr< \fBTexture\fP > tex, const \fBCharacterData\fP & characterData)\fC [inline]\fP"
Sets up the \fBCharacterData\fP that the \fBGlyph\fP will represent\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcharacter\fP is the raw character this \fBGlyph\fP is\&. 
.br
\fItex\fP is the \fBTexture\fP from the \fBFont\fP used to draw the character \fBGlyph\fP\&. 
.br
\fIcharacterData\fP comes from the \fBFont\fP and stores various data the character need\&. 
.RE
.PP

.SS "void Tempest::Glyph::SetCharacter (char character, const \fBCharacterData\fP & characterData)\fC [inline]\fP"
Partial set up of the \fBGlyph\fP \fBCharacterData\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcharacter\fP is the raw character this \fBGlyph\fP is\&. 
.br
\fIcharacterData\fP comes from the \fBFont\fP and stores various data the character needs\&. 
.RE
.PP

.SS "void Glyph::v_Render (void)\fC [final]\fP, \fC [virtual]\fP"
Provides specific Rendering calls\&. This sets a \fBGlyph\fP specific uniform called sprite_color\&. No special behavior other than that\&. 
.PP
Reimplemented from \fBTempest::GameObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
