.TH "Tempest::AudioClip::FormatInfo" 3 "Wed Jan 8 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::AudioClip::FormatInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBS16\fP \fBformat\fP"
.br
.ti -1c
.RI "\fBS16\fP \fBnumChannels\fP"
.br
.ti -1c
.RI "\fBS32\fP \fBsampleRate\fP"
.br
.ti -1c
.RI "\fBS32\fP \fBbyteRate\fP"
.br
.ti -1c
.RI "\fBS16\fP \fBblockAllign\fP"
.br
.ti -1c
.RI "\fBS16\fP \fBbitsPerSample\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
