.TH "Tempest::EnvironmentObject" 3 "Wed Jan 8 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::EnvironmentObject
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EnvironmentObject\&.h>\fP
.PP
Inherits \fBTempest::GameObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "TEMPEST_API \fBEnvironmentObject\fP (void)"
.br
.RI "Default Constructor\&. No special actions taken\&. "
.ti -1c
.RI "TEMPEST_API \fBEnvironmentObject\fP (const \fBTM::Point\fP &pos, \fBF32\fP w, \fBF32\fP h)"
.br
.RI "Calls \fBGameObject::SetPosition\fP and GameObject::SetDimensions\&. "
.ti -1c
.RI "TEMPEST_API \fB~EnvironmentObject\fP (void)"
.br
.RI "Default Destructor\&. No special action taken\&. "
.ti -1c
.RI "void \fBv_Update\fP (void) final"
.br
.RI "Empty function, needed because its a pure virtual function\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is an implementation of a \fBGameObject\fP which will reprents static, unmoving background objects which the player will not be allowed to pass through\&. These are things like rocks, trees, houses, etc\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
