.TH "Tempest::Level::TileData" 3 "Mon Mar 2 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::Level::TileData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBU32\fP \fBid\fP"
.br
.ti -1c
.RI "\fBU32\fP \fBimageWidth\fP"
.br
.ti -1c
.RI "\fBU32\fP \fBimageHeight\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBimageFilePath\fP"
.br
.ti -1c
.RI "\fBTM::Point\fP \fBpos\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
