.TH "Tempest::CharacterData" 3 "Mon Mar 2 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::CharacterData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBS32\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBS32\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBS32\fP \fBbearingX\fP"
.br
.ti -1c
.RI "\fBS32\fP \fBbearingY\fP"
.br
.ti -1c
.RI "\fBS32\fP \fBxAdvance\fP"
.br
.ti -1c
.RI "shared_ptr< \fBTexture\fP > \fBtexture\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
