.TH "Tempest::MenuItem" 3 "Wed Jan 8 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::MenuItem \- A struct to hold all the information needed for an item in a \fBMenu\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Menu\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTM::Point\fP \fBpos\fP"
.br
.RI "Position of the \fBText\fP\&. Used for quick reference, useful even though its duplicated\&. "
.ti -1c
.RI "shared_ptr< \fBText\fP > \fBtext\fP"
.br
.RI "Pointer a \fBText\fP, used for the look of the item in the \fBMenu\fP\&. Call \fBLevel::AddTextToLevel\fP first\&. "
.ti -1c
.RI "void(* \fBAction\fP )(void) = NULL"
.br
.RI "Callback function used when the item is activated\&. Must use the same signature\&. "
.in -1c
.SH "Detailed Description"
.PP 
A struct to hold all the information needed for an item in a \fBMenu\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
