.TH "TempestPhysics::Contact" 3 "Tue Jan 7 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TempestPhysics::Contact
.SH SYNOPSIS
.br
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBTM::Vector4\fP \fB_contactPoint\fP"
.br
.ti -1c
.RI "\fBTM::Vector4\fP \fB_collissionNormal\fP"
.br
.ti -1c
.RI "\fBreal\fP \fB_penetrationDepth\fP"
.br
.ti -1c
.RI "\fBreal\fP \fB_collissionRestitution\fP"
.br
.ti -1c
.RI "\fBreal\fP \fB_friction\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
