.TH "TempestPhysics::ForceRegistry::_RigidBody3DRegistration" 3 "Mon Mar 2 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TempestPhysics::ForceRegistry::_RigidBody3DRegistration \- Private struct type that pairs a single \fBRigidBody3D\fP with a ForceGenerators\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (\fB_RigidBody3DRegistration\fP b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "p_RigidBody3D \fBbody\fP"
.br
.RI "Pointer to object saved to add force to later\&. "
.ti -1c
.RI "p_ForceGenerator \fBforceGen\fP"
.br
.RI "Pointer to force saved to be added to object later\&. "
.in -1c
.SH "Detailed Description"
.PP 
Private struct type that pairs a single \fBRigidBody3D\fP with a ForceGenerators\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool TempestPhysics::ForceRegistry::_RigidBody3DRegistration::operator== (\fB_RigidBody3DRegistration\fP b)\fC [inline]\fP"
Returns true if another registration matches this one\&. 
.PP
\fBParameters\fP
.RS 4
\fIb\fP is the registration to be compared against\&. 
.br
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
