.TH "Tempest::ErrorManager" 3 "Mon Dec 9 2019" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::ErrorManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ErrorManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "TEMPEST_API \fB~ErrorManager\fP (void)"
.br
.RI "Default destructor\&. No special actions taken 
.br
 "
.ti -1c
.RI "TEMPEST_API void \fBSetError\fP (ErrorCode code, string message)"
.br
.ti -1c
.RI "TEMPEST_API bool \fBDisplayErrors\fP (void)"
.br
.ti -1c
.RI "void \fBSetConsoleOut\fP (bool state)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static TEMPEST_API shared_ptr< \fBErrorManager\fP > \fBInstance\fP (void)"
.br
.RI "Singlton function\&. Returns pointer to global \fBErrorManager\fP instance\&. 
.br
 "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBErrorManager\fP (void)"
.br
.RI "Default constructor\&. No special actions are taken\&. Protected because this class follows the singleton pattern 
.br
 "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fB_MessageBox\fP (string errorMessage, string errorCode)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fB_consoleOut\fP"
.br
.RI "Flag that sets if errors should be read out to the console as well\&. "
.ti -1c
.RI "\fBU32\fP \fB_numErrors\fP"
.br
.RI "Total count of errors\&. "
.ti -1c
.RI "std::vector< ErrorCode > \fB_errorCodes\fP"
.br
.RI "List of active error codes\&. "
.ti -1c
.RI "std::vector< string > \fB_errorMessages\fP"
.br
.RI "List of active error messages\&. "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static TEMPEST_API shared_ptr< \fBErrorManager\fP > \fB_instance\fP = NULL"
.br
.RI "Global singleton instance\&. "
.in -1c
.SH "Detailed Description"
.PP 
A singleton class that will display any errors that can happen during the initialization of any of the components of the engine\&. It will be flushed out later to include more details\&. 
.br
 
.SH "Member Function Documentation"
.PP 
.SS "bool ErrorManager::_MessageBox (string errorMessage, string errorCode)\fC [private]\fP"
Helper functions\&. Displays the MessageBox, and returns true if Yes is clicked, false if No is clicked\&. 
.PP
\fBParameters\fP
.RS 4
\fIerrorMessage\fP is the string that will display in the box\&. 
.br
\fIerrorCode\fP is a string version of the ErrorCode that was submited for this error\&. 
.RE
.PP

.SS "bool ErrorManager::DisplayErrors (void)"
Displays any errors that have been added to the manager\&. This function loops over all the errors that have been added and displayed them one by one\&. Messages are never removed once they are thrown\&. 
.br
 
.SS "void Tempest::ErrorManager::SetConsoleOut (bool state)\fC [inline]\fP"
Sets if errors should be displayed on the console as well as a MessageBox 
.PP
\fBParameters\fP
.RS 4
\fIstate\fP sets the new console state\&. True to pump errors to console 
.RE
.PP

.SS "void ErrorManager::SetError (ErrorCode code, string message)"
Adds an error into the Manager's map of errors\&. Any number of message can be in the Manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIcode\fP ErrorCode: Displayed to hint where the error happened\&. 
.br
\fImessage\fP string: A string that will be displayed to the user giving additional details about the nature of the error\&. 
.br
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
