.TH "Tempest::LevelManager" 3 "Mon Mar 2 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::LevelManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LevelManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "TEMPEST_API \fB~LevelManager\fP (void)"
.br
.RI "No implementation\&. "
.ti -1c
.RI "TEMPEST_API void \fBAdd\fP (p_Level level)"
.br
.ti -1c
.RI "TEMPEST_API void \fBRemove\fP (\fBU32\fP levelID)"
.br
.ti -1c
.RI "TEMPEST_API p_Level \fBGetLevel\fP (\fBU32\fP levelID)"
.br
.RI "Returns a pointer to \fBLevel\fP with\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static TEMPEST_API \fBLevelManager\fP * \fBInstance\fP ()"
.br
.RI "Singleton fucntion\&. Returns the global pointer used to access the manager\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelManager\fP (void)"
.br
.RI "Singleton constructor\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::map< \fBU32\fP, p_Level > \fB_levels\fP"
.br
.RI "Database of Levels that can be activated\&. "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBLevelManager\fP * \fB_instance\fP = NULL"
.br
.RI "Singletone pointer to global version of \fBLevelManager\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
A lazy loader for Levels\&. If there is a need to cache a \fBLevel\fP in memory, it can be registered with the \fBLevelManager\fP and recalled later\&. This is far more simple then it used to be\&. For histories sake, at one point this class was used to control the rendering and updating of objects\&. 
.br
 
.SH "Member Function Documentation"
.PP 
.SS "void LevelManager::Add (p_Level level)"
Register a \fBLevel\fP with the manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIlevel\fP is added into the database, with \fBLevel::GetID\fP used to index\&. 
.br
 
.RE
.PP

.SS "p_Level LevelManager::GetLevel (\fBU32\fP levelID)"

.PP
Returns a pointer to \fBLevel\fP with\&. 
.PP
\fBParameters\fP
.RS 4
\fIlevelID\fP if it exists\&. 
.RE
.PP

.SS "void LevelManager::Remove (\fBU32\fP levelID)"
Removes \fBLevel\fP from database\&. 
.PP
\fBParameters\fP
.RS 4
\fIlevelID\fP is the index to delete\&. 
.br
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
