.TH "TempestPhysics::PhysicsFactory" 3 "Mon Dec 9 2019" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TempestPhysics::PhysicsFactory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "p_RigidBody2D \fBMakeRigidBody2D\fP (void)"
.br
.ti -1c
.RI "p_RigidBody3D \fBMakeRigidBody3D\fP (void)"
.br
.ti -1c
.RI "p_GravityForce \fBMakeGravityForce\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static TEMPEST_API shared_ptr< \fBPhysicsFactory\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBPhysicsFactory\fP > \fB_instance\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
