.TH "Tempest::EventManager::ListenerRegistration" 3 "Mon Mar 2 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::EventManager::ListenerRegistration \- Helper struct to keep track of which GameObjects are interested in what types of Events\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBListenerRegistration\fP (p_GameObject l, string t)"
.br
.RI "Basic constructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBinterestType\fP"
.br
.RI "Type of \fBEvent\fP to recieve\&. "
.ti -1c
.RI "p_GameObject \fBlistener\fP"
.br
.RI "\fBGameObject\fP to receive the type of \fBEvent\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Helper struct to keep track of which GameObjects are interested in what types of Events\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
