.TH "Tempest::Text" 3 "Wed Jan 8 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::Text
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Text\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "TEMPEST_API \fBText\fP (void)"
.br
.RI "Default constructor\&. Sets scale and color to 1\&.0f, everything else to 0 or null\&. "
.ti -1c
.RI "TEMPEST_API \fBText\fP (string text)"
.br
.ti -1c
.RI "TEMPEST_API \fBText\fP (string text, p_Font font)"
.br
.ti -1c
.RI "TEMPEST_API \fBText\fP (string text, \fBFont\fP &font)"
.br
.ti -1c
.RI "TEMPEST_API \fB~Text\fP (void)"
.br
.RI "Default destructor\&. No function\&. "
.ti -1c
.RI "void \fBSetPosition\fP (const \fBTM::Point\fP &pos)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (\fBF32\fP x, \fBF32\fP y)"
.br
.ti -1c
.RI "TEMPEST_API void \fBAddText\fP (string text)"
.br
.ti -1c
.RI "TEMPEST_API void \fBSetTextColor\fP (const \fBColor\fP &col)"
.br
.ti -1c
.RI "TEMPEST_API void \fBSetUniforms\fP (string name, const \fBTM::Matrix4\fP &Matrix4)"
.br
.ti -1c
.RI "string \fBGetText\fP (void)"
.br
.RI "Returns a string version of the current text represented by Glyphs (if the Glyphs have been generated with a font)\&. "
.ti -1c
.RI "void \fBSetActive\fP (bool state)"
.br
.ti -1c
.RI "void \fBSetActive\fP (void)"
.br
.RI "Sets each \fBGlyph\fP to active state\&. "
.ti -1c
.RI "void \fBSetInactive\fP (void)"
.br
.RI "Sets each \fBGlyph\fP to not active state\&. "
.ti -1c
.RI "bool \fBGetActive\fP (void) const"
.br
.RI "Returns the active state of the \fBText\fP, and by inference, each \fBGlyph\fP\&. "
.ti -1c
.RI "\fBF32\fP \fBGetWidth\fP (void)"
.br
.ti -1c
.RI "TEMPEST_API void \fBSetFont\fP (p_Font font)"
.br
.ti -1c
.RI "void \fBSetFont\fP (\fBFont\fP &font)"
.br
.ti -1c
.RI "const p_Font \fBGetFont\fP (void)"
.br
.RI "Returns the font \fBText\fP is using\&. "
.ti -1c
.RI "std::vector< shared_ptr< \fBGlyph\fP > > \fBGetCharacterList\fP (void) const"
.br
.RI "Returns all the Glyphs in the \fBText\fP\&. Used for copying\&. "
.ti -1c
.RI "void \fBSetScale\fP (const \fBTM::Vector3\fP &s)"
.br
.ti -1c
.RI "void \fBSetScale\fP (\fBF32\fP xScale, \fBF32\fP yScale)"
.br
.ti -1c
.RI "const \fBTM::Vector3\fP & \fBGetScale\fP (void)"
.br
.RI "Returns the current scale of the \fBText\fP\&. "
.ti -1c
.RI "void \fBSetColor\fP (const \fBColor\fP &c)"
.br
.ti -1c
.RI "void \fBSetColor\fP (\fBF32\fP r, \fBF32\fP g, \fBF32\fP b)"
.br
.ti -1c
.RI "const \fBColor\fP & \fBGetColor\fP (void)"
.br
.RI "Returns the current \fBColor\fP of the \fBText\fP\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "TEMPEST_API void \fB_UpdatePositions\fP (void)"
.br
.RI "Iterates over each \fBGlyph\fP calling \fBGameObject::SetPosition()\fP for each \fBGlyph\fP, updating the position, including the xAdvnace\&. "
.ti -1c
.RI "TEMPEST_API void \fB_UpdateActive\fP (void)"
.br
.RI "Iterates over each \fBGlyph\fP calling \fBGameObject::SetActive()\fP for each, using _active\&. "
.ti -1c
.RI "TEMPEST_API void \fB_UpdateScales\fP (void)"
.br
.RI "Iterates over each \fBGlyph\fP calling \fBGameObject::SetScale()\fP for each, using _scale\&. "
.ti -1c
.RI "TEMPEST_API void \fB_UpdateColors\fP (void)"
.br
.RI "Iterates over each \fBGlyph\fP calling \fBGameObject::SetColor()\fP for each, using _color\&. "
.ti -1c
.RI "TEMPEST_API void \fB_UpdateGlyphData\fP (\fBU32\fP index)"
.br
.ti -1c
.RI "void \fB_CreateCharacterList\fP (void)"
.br
.RI "Creates or Recreates the character list, forcing it to match with the text\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fB_active\fP"
.br
.RI "Active state of \fBText\fP and each \fBGlyph\fP\&. "
.ti -1c
.RI "\fBF32\fP \fB_totalWidth\fP"
.br
.RI "Total space the \fBText\fP will take up on screen\&. "
.ti -1c
.RI "\fBTM::Point\fP \fB_pos\fP"
.br
.RI "Position of the first \fBGlyph\fP in the \fBText\fP\&. "
.ti -1c
.RI "string \fB_text\fP"
.br
.RI "The string used to generate each \fBGlyph\fP\&. "
.ti -1c
.RI "p_Font \fB_font\fP"
.br
.RI "The \fBFont\fP used to generate each \fBGlyph\fP\&. "
.ti -1c
.RI "std::vector< shared_ptr< \fBGlyph\fP > > \fB_characterList\fP"
.br
.RI "List of all generated Glyphs\&. Should match _text\&. "
.ti -1c
.RI "\fBTM::Vector3\fP \fB_scale\fP"
.br
.RI "The scaling factor used for each \fBGlyph\fP\&. "
.ti -1c
.RI "\fBColor\fP \fB_color\fP"
.br
.RI "The \fBColor\fP used for each \fBGlyph\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class will hold all the data for a string of text that will be drawn to the screen\&. It will use the font class and the texture manager to keep track of all the character data and the texture for the font\&. There are a lot of things that can be done to optimize this class and these ideas\&. It probably needs a second pass very badly\&. For example, \fBAddText()\fP creates as many \fBGlyph\fP characters as there are characters in the string that is passed in\&. This means that there is no shared re-use of the \fBGlyph\fP\&. This is because each one needs a unique position\&. There could be some clever wasy to get around this using instancing, but this will require more work, and I wanted to just get the class working\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Text::Text (string text)\fC [explicit]\fP"
String to \fBText\fP conversion function\&. Calls \fBText::AddText\fP to set up the class\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP is the string that will be used to create the \fBText\fP\&. 
.RE
.PP

.SS "Text::Text (string text, p_Font font)"
Creates a \fBText\fP with Glyphs for each character in a string with a given \fBFont\fP\&. Calls \fBText::AddText\fP to set up everything\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP are the desires characters\&. 
.br
\fIfont\fP is the given \fBFont\fP\&. Should come from the \fBFontManager\fP\&. 
.RE
.PP

.SS "Text::Text (string text, \fBFont\fP & font)"
Creates a \fBText\fP with Glyphs for each character in a string with a given \fBFont\fP\&. Calls \fBText::AddText\fP to set up everything\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP are the desires characters\&. 
.br
\fIfont\fP is the given \fBFont\fP\&. Should come from the \fBFontManager\fP\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Text::_UpdateGlyphData (\fBU32\fP index)\fC [private]\fP"
Updates a \fBGlyph\fP\&. This sets the data, the sprite, color, scale and other values based on the font\&. If the \fBGlyph\fP has been added to the characterList already, it will update and edit the existing \fBGlyph\fP, other wise a new one will be created and added to the list\&. 
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP is the character number in the _text\&. This should coorespond the index in _characterList\&. 
.RE
.PP

.SS "void Text::AddText (string text)"
This does not so much add additional text to the \fBText\fP as set's what string of Glpyhs will be set\&. This does incure the cost of creating all of the \fBGlyph\fP characters in the \fBText\fP\&. This creates a unique \fBGlyph\fP for each character in the \fBText\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP is the string that will be turned into Glyphs\&. 
.RE
.PP

.SS "\fBF32\fP Tempest::Text::GetWidth (void)\fC [inline]\fP"
Returns the total width of all the Glyphs including the xAdvance values\&. This means that this width represents how much screen space the \fBText\fP is going to take up on the x axis\&. 
.SS "void Tempest::Text::SetActive (bool state)\fC [inline]\fP"
Sets the active state of each \fBGlyph\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstate\fP is the new state each \fBGlyph\fP will get\&. 
.RE
.PP

.SS "void Tempest::Text::SetColor (const \fBColor\fP & c)\fC [inline]\fP"
Sets the \fBColor\fP for the \fBText\fP and each \fBGlyph\fP that has been added\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP is the \fBColor\fP that will be used\&. 
.RE
.PP

.SS "void Tempest::Text::SetColor (\fBF32\fP r, \fBF32\fP g, \fBF32\fP b)\fC [inline]\fP"
Sets the \fBColor\fP for the \fBText\fP and each \fBGlyph\fP that has been added\&. 
.PP
\fBParameters:\fP
.RS 4
\fIr\fP is the Red value that will be used\&. 
.br
\fIg\fP is the Green value that will be used\&. 
.br
\fIb\fP is the Blue value that will be used\&. 
.RE
.PP

.SS "void Text::SetFont (p_Font font)"
Sets the font for the \fBText\fP and all of the Glyphs, if there are any\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfont\fP is the new \fBFont\fP that will be saved in this \fBText\fP\&. 
.RE
.PP

.SS "void Tempest::Text::SetFont (\fBFont\fP & font)\fC [inline]\fP"
Sets the font for the \fBText\fP and all of the Glyphs, if there are any\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfont\fP is the new \fBFont\fP that will be saved in this \fBText\fP\&. 
.RE
.PP

.SS "void Tempest::Text::SetPosition (const \fBTM::Point\fP & pos)\fC [inline]\fP"
Updates the position of each \fBGlyph\fP in the \fBText\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpos\fP is the new position that will be used to start the update of each \fBGlyph\fP\&. 
.RE
.PP

.SS "void Tempest::Text::SetPosition (\fBF32\fP x, \fBF32\fP y)\fC [inline]\fP"
Updates the position of each \fBGlyph\fP in the \fBText\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP sets the first coordinate\&. 
.br
\fIy\fP sets the second coordinate\&. 
.RE
.PP

.SS "void Tempest::Text::SetScale (const \fBTM::Vector3\fP & s)\fC [inline]\fP"
Sets the scale of the \fBText\fP and updates any Glyphs\&. Calls \fBGameObject::SetScale()\fP 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP is the Vector4 used as the scale\&. 
.RE
.PP

.SS "void Tempest::Text::SetScale (\fBF32\fP xScale, \fBF32\fP yScale)\fC [inline]\fP"
Sets the scale of the \fBText\fP and updates any Glyphs\&. Calls \fBGameObject::SetScale()\fP 
.PP
\fBParameters:\fP
.RS 4
\fIxScale\fP is the scale to set on the x axis\&. 
.br
\fIyScale\fP is the scale to set on the y axis\&. 
.RE
.PP

.SS "void Text::SetTextColor (const \fBColor\fP & col)"
Sets the color of each \fBGlyph\fP in the \fBText\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcol\fP is the \fBColor\fP each \fBGlyph\fP is set to\&. 
.RE
.PP

.SS "void Text::SetUniforms (string name, const \fBTM::Matrix4\fP & Matrix4)"
A wrapper function that calls \fBGameObject::SetUniform\fP on each \fBGlyph\fP using the input\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP is the name of the uniform that will be set\&. 
.br
\fIMatrix4\fP is the transformation Matrix4 to be used by each \fBGlyph\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
