.TH "Tempest::EngineFactory" 3 "Mon Mar 2 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::EngineFactory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "p_Glyph \fBMakeGlyph\fP (void)"
.br
.ti -1c
.RI "TP::p_RigidBody2D \fBMakeRigidBody2D\fP (void)"
.br
.ti -1c
.RI "TP::p_RigidBody3D \fBMakeRigidBody3D\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static TEMPEST_API shared_ptr< \fBEngineFactory\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBEngineFactory\fP > \fB_instance\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
