.TH "Tempest::FontManager" 3 "Mon Mar 2 2020" "Tempest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tempest::FontManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "TEMPEST_API void \fBLoadFont\fP (\fBU32\fP id, string fontName, string filePath, \fBU32\fP size)"
.br
.ti -1c
.RI "TEMPEST_API void \fBAddFont\fP (\fBU32\fP id, shared_ptr< \fBFont\fP > font)"
.br
.ti -1c
.RI "TEMPEST_API void \fBAddFont\fP (\fBU32\fP id, \fBFont\fP &font)"
.br
.ti -1c
.RI "TEMPEST_API shared_ptr< \fBFont\fP > \fBGetFont\fP (\fBU32\fP id)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static TEMPEST_API shared_ptr< \fBFontManager\fP > \fBInstance\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::map< \fBU32\fP, shared_ptr< \fBFont\fP > > \fB_loadedFonts\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static shared_ptr< \fBFontManager\fP > \fB_instance\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tempest from the source code\&.
