.TH "tinyxml2" 3 "Wed Jun 6 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyxml2
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDynArray\fP"
.br
.ti -1c
.RI "class \fBMemPool\fP"
.br
.ti -1c
.RI "class \fBMemPoolT\fP"
.br
.ti -1c
.RI "class \fBStrPair\fP"
.br
.ti -1c
.RI "class \fBXMLAttribute\fP"
.br
.ti -1c
.RI "class \fBXMLComment\fP"
.br
.ti -1c
.RI "class \fBXMLConstHandle\fP"
.br
.ti -1c
.RI "class \fBXMLDeclaration\fP"
.br
.ti -1c
.RI "class \fBXMLDocument\fP"
.br
.ti -1c
.RI "class \fBXMLElement\fP"
.br
.ti -1c
.RI "class \fBXMLHandle\fP"
.br
.ti -1c
.RI "class \fBXMLNode\fP"
.br
.ti -1c
.RI "class \fBXMLPrinter\fP"
.br
.ti -1c
.RI "class \fBXMLText\fP"
.br
.ti -1c
.RI "class \fBXMLUnknown\fP"
.br
.ti -1c
.RI "class \fBXMLUtil\fP"
.br
.ti -1c
.RI "class \fBXMLVisitor\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBXMLError\fP { \fBXML_SUCCESS\fP = 0, \fBXML_NO_ATTRIBUTE\fP, \fBXML_WRONG_ATTRIBUTE_TYPE\fP, \fBXML_ERROR_FILE_NOT_FOUND\fP, \fBXML_ERROR_FILE_COULD_NOT_BE_OPENED\fP, \fBXML_ERROR_FILE_READ_ERROR\fP, \fBXML_ERROR_ELEMENT_MISMATCH\fP, \fBXML_ERROR_PARSING_ELEMENT\fP, \fBXML_ERROR_PARSING_ATTRIBUTE\fP, \fBXML_ERROR_IDENTIFYING_TAG\fP, \fBXML_ERROR_PARSING_TEXT\fP, \fBXML_ERROR_PARSING_CDATA\fP, \fBXML_ERROR_PARSING_COMMENT\fP, \fBXML_ERROR_PARSING_DECLARATION\fP, \fBXML_ERROR_PARSING_UNKNOWN\fP, \fBXML_ERROR_EMPTY_DOCUMENT\fP, \fBXML_ERROR_MISMATCHED_ELEMENT\fP, \fBXML_ERROR_PARSING\fP, \fBXML_CAN_NOT_CONVERT_TEXT\fP, \fBXML_NO_TEXT_NODE\fP, \fBXML_ERROR_COUNT\fP }"
.br
.ti -1c
.RI "enum \fBWhitespace\fP { \fBPRESERVE_WHITESPACE\fP, \fBCOLLAPSE_WHITESPACE\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBtinyxml2::Whitespace\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPRESERVE_WHITESPACE \fP\fP
.TP
\fB\fICOLLAPSE_WHITESPACE \fP\fP
.SS "enum \fBtinyxml2::XMLError\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIXML_SUCCESS \fP\fP
.TP
\fB\fIXML_NO_ATTRIBUTE \fP\fP
.TP
\fB\fIXML_WRONG_ATTRIBUTE_TYPE \fP\fP
.TP
\fB\fIXML_ERROR_FILE_NOT_FOUND \fP\fP
.TP
\fB\fIXML_ERROR_FILE_COULD_NOT_BE_OPENED \fP\fP
.TP
\fB\fIXML_ERROR_FILE_READ_ERROR \fP\fP
.TP
\fB\fIXML_ERROR_ELEMENT_MISMATCH \fP\fP
.TP
\fB\fIXML_ERROR_PARSING_ELEMENT \fP\fP
.TP
\fB\fIXML_ERROR_PARSING_ATTRIBUTE \fP\fP
.TP
\fB\fIXML_ERROR_IDENTIFYING_TAG \fP\fP
.TP
\fB\fIXML_ERROR_PARSING_TEXT \fP\fP
.TP
\fB\fIXML_ERROR_PARSING_CDATA \fP\fP
.TP
\fB\fIXML_ERROR_PARSING_COMMENT \fP\fP
.TP
\fB\fIXML_ERROR_PARSING_DECLARATION \fP\fP
.TP
\fB\fIXML_ERROR_PARSING_UNKNOWN \fP\fP
.TP
\fB\fIXML_ERROR_EMPTY_DOCUMENT \fP\fP
.TP
\fB\fIXML_ERROR_MISMATCHED_ELEMENT \fP\fP
.TP
\fB\fIXML_ERROR_PARSING \fP\fP
.TP
\fB\fIXML_CAN_NOT_CONVERT_TEXT \fP\fP
.TP
\fB\fIXML_NO_TEXT_NODE \fP\fP
.TP
\fB\fIXML_ERROR_COUNT \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
