.TH "tinyxml2::DynArray< T, INITIAL_SIZE >" 3 "Sun Jun 3 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyxml2::DynArray< T, INITIAL_SIZE >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBPush\fP (T t)"
.br
.ti -1c
.RI "T * \fBPushArr\fP (int count)"
.br
.ti -1c
.RI "T \fBPop\fP ()"
.br
.ti -1c
.RI "void \fBPopArr\fP (int count)"
.br
.ti -1c
.RI "bool \fBEmpty\fP () const"
.br
.ti -1c
.RI "T & \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "const T & \fBoperator[]\fP (int i) const"
.br
.ti -1c
.RI "const T & \fBPeekTop\fP () const"
.br
.ti -1c
.RI "int \fBSize\fP () const"
.br
.ti -1c
.RI "int \fBCapacity\fP () const"
.br
.ti -1c
.RI "const T * \fBMem\fP () const"
.br
.ti -1c
.RI "T * \fBMem\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
