.TH "F:/Projects/Killer_Engine/Headers/TinyXML/tinyxml2.h" 3 "Wed Jun 6 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Projects/Killer_Engine/Headers/TinyXML/tinyxml2.h
.SH SYNOPSIS
.br
.PP
\fC#include <cctype>\fP
.br
\fC#include <climits>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtinyxml2::StrPair\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::DynArray< T, INITIAL_SIZE >\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::MemPool\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::MemPoolT< ITEM_SIZE >\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLVisitor\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLUtil\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLNode\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLText\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLComment\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLDeclaration\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLUnknown\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLAttribute\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLElement\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLDocument\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLHandle\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLConstHandle\fP"
.br
.ti -1c
.RI "class \fBtinyxml2::XMLPrinter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtinyxml2\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTINYXML2_LIB\fP"
.br
.ti -1c
.RI "#define \fBTIXMLASSERT\fP(\fBx\fP)   {}"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtinyxml2::XMLError\fP { \fBtinyxml2::XML_SUCCESS\fP = 0, \fBtinyxml2::XML_NO_ATTRIBUTE\fP, \fBtinyxml2::XML_WRONG_ATTRIBUTE_TYPE\fP, \fBtinyxml2::XML_ERROR_FILE_NOT_FOUND\fP, \fBtinyxml2::XML_ERROR_FILE_COULD_NOT_BE_OPENED\fP, \fBtinyxml2::XML_ERROR_FILE_READ_ERROR\fP, \fBtinyxml2::XML_ERROR_ELEMENT_MISMATCH\fP, \fBtinyxml2::XML_ERROR_PARSING_ELEMENT\fP, \fBtinyxml2::XML_ERROR_PARSING_ATTRIBUTE\fP, \fBtinyxml2::XML_ERROR_IDENTIFYING_TAG\fP, \fBtinyxml2::XML_ERROR_PARSING_TEXT\fP, \fBtinyxml2::XML_ERROR_PARSING_CDATA\fP, \fBtinyxml2::XML_ERROR_PARSING_COMMENT\fP, \fBtinyxml2::XML_ERROR_PARSING_DECLARATION\fP, \fBtinyxml2::XML_ERROR_PARSING_UNKNOWN\fP, \fBtinyxml2::XML_ERROR_EMPTY_DOCUMENT\fP, \fBtinyxml2::XML_ERROR_MISMATCHED_ELEMENT\fP, \fBtinyxml2::XML_ERROR_PARSING\fP, \fBtinyxml2::XML_CAN_NOT_CONVERT_TEXT\fP, \fBtinyxml2::XML_NO_TEXT_NODE\fP, \fBtinyxml2::XML_ERROR_COUNT\fP }"
.br
.ti -1c
.RI "enum \fBtinyxml2::Whitespace\fP { \fBtinyxml2::PRESERVE_WHITESPACE\fP, \fBtinyxml2::COLLAPSE_WHITESPACE\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const int \fBTIXML2_MAJOR_VERSION\fP = 4"
.br
.ti -1c
.RI "static const int \fBTIXML2_MINOR_VERSION\fP = 0"
.br
.ti -1c
.RI "static const int \fBTIXML2_PATCH_VERSION\fP = 1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TINYXML2_LIB"

.SS "#define TIXMLASSERT(\fBx\fP)   {}"

.SH "Variable Documentation"
.PP 
.SS "const int TIXML2_MAJOR_VERSION = 4\fC [static]\fP"

.SS "const int TIXML2_MINOR_VERSION = 0\fC [static]\fP"

.SS "const int TIXML2_PATCH_VERSION = 1\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
