.TH "TT_Header_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_Header_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Fixed \fBTable_Version\fP"
.br
.ti -1c
.RI "FT_Fixed \fBFont_Revision\fP"
.br
.ti -1c
.RI "FT_Long \fBCheckSum_Adjust\fP"
.br
.ti -1c
.RI "FT_Long \fBMagic_Number\fP"
.br
.ti -1c
.RI "FT_UShort \fBFlags\fP"
.br
.ti -1c
.RI "FT_UShort \fBUnits_Per_EM\fP"
.br
.ti -1c
.RI "FT_Long \fBCreated\fP [2]"
.br
.ti -1c
.RI "FT_Long \fBModified\fP [2]"
.br
.ti -1c
.RI "FT_Short \fBxMin\fP"
.br
.ti -1c
.RI "FT_Short \fByMin\fP"
.br
.ti -1c
.RI "FT_Short \fBxMax\fP"
.br
.ti -1c
.RI "FT_Short \fByMax\fP"
.br
.ti -1c
.RI "FT_UShort \fBMac_Style\fP"
.br
.ti -1c
.RI "FT_UShort \fBLowest_Rec_PPEM\fP"
.br
.ti -1c
.RI "FT_Short \fBFont_Direction\fP"
.br
.ti -1c
.RI "FT_Short \fBIndex_To_Loc_Format\fP"
.br
.ti -1c
.RI "FT_Short \fBGlyph_Data_Format\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
