.TH "TT_MaxProfile_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_MaxProfile_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Fixed \fBversion\fP"
.br
.ti -1c
.RI "FT_UShort \fBnumGlyphs\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxPoints\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxContours\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxCompositePoints\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxCompositeContours\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxZones\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxTwilightPoints\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxStorage\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxFunctionDefs\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxInstructionDefs\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxStackElements\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxSizeOfInstructions\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxComponentElements\fP"
.br
.ti -1c
.RI "FT_UShort \fBmaxComponentDepth\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
