.TH "TT_OS2_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_OS2_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBversion\fP"
.br
.ti -1c
.RI "FT_Short \fBxAvgCharWidth\fP"
.br
.ti -1c
.RI "FT_UShort \fBusWeightClass\fP"
.br
.ti -1c
.RI "FT_UShort \fBusWidthClass\fP"
.br
.ti -1c
.RI "FT_UShort \fBfsType\fP"
.br
.ti -1c
.RI "FT_Short \fBySubscriptXSize\fP"
.br
.ti -1c
.RI "FT_Short \fBySubscriptYSize\fP"
.br
.ti -1c
.RI "FT_Short \fBySubscriptXOffset\fP"
.br
.ti -1c
.RI "FT_Short \fBySubscriptYOffset\fP"
.br
.ti -1c
.RI "FT_Short \fBySuperscriptXSize\fP"
.br
.ti -1c
.RI "FT_Short \fBySuperscriptYSize\fP"
.br
.ti -1c
.RI "FT_Short \fBySuperscriptXOffset\fP"
.br
.ti -1c
.RI "FT_Short \fBySuperscriptYOffset\fP"
.br
.ti -1c
.RI "FT_Short \fByStrikeoutSize\fP"
.br
.ti -1c
.RI "FT_Short \fByStrikeoutPosition\fP"
.br
.ti -1c
.RI "FT_Short \fBsFamilyClass\fP"
.br
.ti -1c
.RI "FT_Byte \fBpanose\fP [10]"
.br
.ti -1c
.RI "FT_ULong \fBulUnicodeRange1\fP"
.br
.ti -1c
.RI "FT_ULong \fBulUnicodeRange2\fP"
.br
.ti -1c
.RI "FT_ULong \fBulUnicodeRange3\fP"
.br
.ti -1c
.RI "FT_ULong \fBulUnicodeRange4\fP"
.br
.ti -1c
.RI "FT_Char \fBachVendID\fP [4]"
.br
.ti -1c
.RI "FT_UShort \fBfsSelection\fP"
.br
.ti -1c
.RI "FT_UShort \fBusFirstCharIndex\fP"
.br
.ti -1c
.RI "FT_UShort \fBusLastCharIndex\fP"
.br
.ti -1c
.RI "FT_Short \fBsTypoAscender\fP"
.br
.ti -1c
.RI "FT_Short \fBsTypoDescender\fP"
.br
.ti -1c
.RI "FT_Short \fBsTypoLineGap\fP"
.br
.ti -1c
.RI "FT_UShort \fBusWinAscent\fP"
.br
.ti -1c
.RI "FT_UShort \fBusWinDescent\fP"
.br
.ti -1c
.RI "FT_ULong \fBulCodePageRange1\fP"
.br
.ti -1c
.RI "FT_ULong \fBulCodePageRange2\fP"
.br
.ti -1c
.RI "FT_Short \fBsxHeight\fP"
.br
.ti -1c
.RI "FT_Short \fBsCapHeight\fP"
.br
.ti -1c
.RI "FT_UShort \fBusDefaultChar\fP"
.br
.ti -1c
.RI "FT_UShort \fBusBreakChar\fP"
.br
.ti -1c
.RI "FT_UShort \fBusMaxContext\fP"
.br
.ti -1c
.RI "FT_UShort \fBusLowerOpticalPointSize\fP"
.br
.ti -1c
.RI "FT_UShort \fBusUpperOpticalPointSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
