.TH "TT_Postscript_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_Postscript_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Fixed \fBFormatType\fP"
.br
.ti -1c
.RI "FT_Fixed \fBitalicAngle\fP"
.br
.ti -1c
.RI "FT_Short \fBunderlinePosition\fP"
.br
.ti -1c
.RI "FT_Short \fBunderlineThickness\fP"
.br
.ti -1c
.RI "FT_ULong \fBisFixedPitch\fP"
.br
.ti -1c
.RI "FT_ULong \fBminMemType42\fP"
.br
.ti -1c
.RI "FT_ULong \fBmaxMemType42\fP"
.br
.ti -1c
.RI "FT_ULong \fBminMemType1\fP"
.br
.ti -1c
.RI "FT_ULong \fBmaxMemType1\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
