.TH "TT_PCLT_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_PCLT_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Fixed \fBVersion\fP"
.br
.ti -1c
.RI "FT_ULong \fBFontNumber\fP"
.br
.ti -1c
.RI "FT_UShort \fBPitch\fP"
.br
.ti -1c
.RI "FT_UShort \fBxHeight\fP"
.br
.ti -1c
.RI "FT_UShort \fBStyle\fP"
.br
.ti -1c
.RI "FT_UShort \fBTypeFamily\fP"
.br
.ti -1c
.RI "FT_UShort \fBCapHeight\fP"
.br
.ti -1c
.RI "FT_UShort \fBSymbolSet\fP"
.br
.ti -1c
.RI "FT_Char \fBTypeFace\fP [16]"
.br
.ti -1c
.RI "FT_Char \fBCharacterComplement\fP [8]"
.br
.ti -1c
.RI "FT_Char \fBFileName\fP [6]"
.br
.ti -1c
.RI "FT_Char \fBStrokeWeight\fP"
.br
.ti -1c
.RI "FT_Char \fBWidthType\fP"
.br
.ti -1c
.RI "FT_Byte \fBSerifStyle\fP"
.br
.ti -1c
.RI "FT_Byte \fBReserved\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
