.TH "TT_VertHeader_" 3 "Thu Jan 10 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_VertHeader_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Fixed \fBVersion\fP"
.br
.ti -1c
.RI "FT_Short \fBAscender\fP"
.br
.ti -1c
.RI "FT_Short \fBDescender\fP"
.br
.ti -1c
.RI "FT_Short \fBLine_Gap\fP"
.br
.ti -1c
.RI "FT_UShort \fBadvance_Height_Max\fP"
.br
.ti -1c
.RI "FT_Short \fBmin_Top_Side_Bearing\fP"
.br
.ti -1c
.RI "FT_Short \fBmin_Bottom_Side_Bearing\fP"
.br
.ti -1c
.RI "FT_Short \fByMax_Extent\fP"
.br
.ti -1c
.RI "FT_Short \fBcaret_Slope_Rise\fP"
.br
.ti -1c
.RI "FT_Short \fBcaret_Slope_Run\fP"
.br
.ti -1c
.RI "FT_Short \fBcaret_Offset\fP"
.br
.ti -1c
.RI "FT_Short \fBReserved\fP [4]"
.br
.ti -1c
.RI "FT_Short \fBmetric_Data_Format\fP"
.br
.ti -1c
.RI "FT_UShort \fBnumber_Of_VMetrics\fP"
.br
.ti -1c
.RI "void * \fBlong_metrics\fP"
.br
.ti -1c
.RI "void * \fBshort_metrics\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
