.TH "Vector" 3 "Tue Feb 19 2019" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The \fBVector\fP class, like the \fBKillerEngine::Color\fP class, is based on 4 elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
