.TH "F:/Projects/Killer_Engine/Headers/GL/wglext.h" 3 "Wed Jun 6 2018" "Killer Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Projects/Killer_Engine/Headers/GL/wglext.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_GPU_DEVICE\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWGL_WGLEXT_VERSION\fP   20140810"
.br
.ti -1c
.RI "#define \fBWGL_ARB_buffer_region\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_FRONT_COLOR_BUFFER_BIT_ARB\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBWGL_BACK_COLOR_BUFFER_BIT_ARB\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBWGL_DEPTH_BUFFER_BIT_ARB\fP   0x00000004"
.br
.ti -1c
.RI "#define \fBWGL_STENCIL_BUFFER_BIT_ARB\fP   0x00000008"
.br
.ti -1c
.RI "#define \fBWGL_ARB_context_flush_control\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_RELEASE_BEHAVIOR_ARB\fP   0x2097"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB\fP   0"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB\fP   0x2098"
.br
.ti -1c
.RI "#define \fBWGL_ARB_create_context\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_DEBUG_BIT_ARB\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_MAJOR_VERSION_ARB\fP   0x2091"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_MINOR_VERSION_ARB\fP   0x2092"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_LAYER_PLANE_ARB\fP   0x2093"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_FLAGS_ARB\fP   0x2094"
.br
.ti -1c
.RI "#define \fBERROR_INVALID_VERSION_ARB\fP   0x2095"
.br
.ti -1c
.RI "#define \fBWGL_ARB_create_context_profile\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_PROFILE_MASK_ARB\fP   0x9126"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_CORE_PROFILE_BIT_ARB\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBERROR_INVALID_PROFILE_ARB\fP   0x2096"
.br
.ti -1c
.RI "#define \fBWGL_ARB_create_context_robustness\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_ROBUST_ACCESS_BIT_ARB\fP   0x00000004"
.br
.ti -1c
.RI "#define \fBWGL_LOSE_CONTEXT_ON_RESET_ARB\fP   0x8252"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB\fP   0x8256"
.br
.ti -1c
.RI "#define \fBWGL_NO_RESET_NOTIFICATION_ARB\fP   0x8261"
.br
.ti -1c
.RI "#define \fBWGL_ARB_extensions_string\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_ARB_framebuffer_sRGB\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_FRAMEBUFFER_SRGB_CAPABLE_ARB\fP   0x20A9"
.br
.ti -1c
.RI "#define \fBWGL_ARB_make_current_read\fP   1"
.br
.ti -1c
.RI "#define \fBERROR_INVALID_PIXEL_TYPE_ARB\fP   0x2043"
.br
.ti -1c
.RI "#define \fBERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB\fP   0x2054"
.br
.ti -1c
.RI "#define \fBWGL_ARB_multisample\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_SAMPLE_BUFFERS_ARB\fP   0x2041"
.br
.ti -1c
.RI "#define \fBWGL_SAMPLES_ARB\fP   0x2042"
.br
.ti -1c
.RI "#define \fBWGL_ARB_pbuffer\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_DRAW_TO_PBUFFER_ARB\fP   0x202D"
.br
.ti -1c
.RI "#define \fBWGL_MAX_PBUFFER_PIXELS_ARB\fP   0x202E"
.br
.ti -1c
.RI "#define \fBWGL_MAX_PBUFFER_WIDTH_ARB\fP   0x202F"
.br
.ti -1c
.RI "#define \fBWGL_MAX_PBUFFER_HEIGHT_ARB\fP   0x2030"
.br
.ti -1c
.RI "#define \fBWGL_PBUFFER_LARGEST_ARB\fP   0x2033"
.br
.ti -1c
.RI "#define \fBWGL_PBUFFER_WIDTH_ARB\fP   0x2034"
.br
.ti -1c
.RI "#define \fBWGL_PBUFFER_HEIGHT_ARB\fP   0x2035"
.br
.ti -1c
.RI "#define \fBWGL_PBUFFER_LOST_ARB\fP   0x2036"
.br
.ti -1c
.RI "#define \fBWGL_ARB_pixel_format\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_NUMBER_PIXEL_FORMATS_ARB\fP   0x2000"
.br
.ti -1c
.RI "#define \fBWGL_DRAW_TO_WINDOW_ARB\fP   0x2001"
.br
.ti -1c
.RI "#define \fBWGL_DRAW_TO_BITMAP_ARB\fP   0x2002"
.br
.ti -1c
.RI "#define \fBWGL_ACCELERATION_ARB\fP   0x2003"
.br
.ti -1c
.RI "#define \fBWGL_NEED_PALETTE_ARB\fP   0x2004"
.br
.ti -1c
.RI "#define \fBWGL_NEED_SYSTEM_PALETTE_ARB\fP   0x2005"
.br
.ti -1c
.RI "#define \fBWGL_SWAP_LAYER_BUFFERS_ARB\fP   0x2006"
.br
.ti -1c
.RI "#define \fBWGL_SWAP_METHOD_ARB\fP   0x2007"
.br
.ti -1c
.RI "#define \fBWGL_NUMBER_OVERLAYS_ARB\fP   0x2008"
.br
.ti -1c
.RI "#define \fBWGL_NUMBER_UNDERLAYS_ARB\fP   0x2009"
.br
.ti -1c
.RI "#define \fBWGL_TRANSPARENT_ARB\fP   0x200A"
.br
.ti -1c
.RI "#define \fBWGL_TRANSPARENT_RED_VALUE_ARB\fP   0x2037"
.br
.ti -1c
.RI "#define \fBWGL_TRANSPARENT_GREEN_VALUE_ARB\fP   0x2038"
.br
.ti -1c
.RI "#define \fBWGL_TRANSPARENT_BLUE_VALUE_ARB\fP   0x2039"
.br
.ti -1c
.RI "#define \fBWGL_TRANSPARENT_ALPHA_VALUE_ARB\fP   0x203A"
.br
.ti -1c
.RI "#define \fBWGL_TRANSPARENT_INDEX_VALUE_ARB\fP   0x203B"
.br
.ti -1c
.RI "#define \fBWGL_SHARE_DEPTH_ARB\fP   0x200C"
.br
.ti -1c
.RI "#define \fBWGL_SHARE_STENCIL_ARB\fP   0x200D"
.br
.ti -1c
.RI "#define \fBWGL_SHARE_ACCUM_ARB\fP   0x200E"
.br
.ti -1c
.RI "#define \fBWGL_SUPPORT_GDI_ARB\fP   0x200F"
.br
.ti -1c
.RI "#define \fBWGL_SUPPORT_OPENGL_ARB\fP   0x2010"
.br
.ti -1c
.RI "#define \fBWGL_DOUBLE_BUFFER_ARB\fP   0x2011"
.br
.ti -1c
.RI "#define \fBWGL_STEREO_ARB\fP   0x2012"
.br
.ti -1c
.RI "#define \fBWGL_PIXEL_TYPE_ARB\fP   0x2013"
.br
.ti -1c
.RI "#define \fBWGL_COLOR_BITS_ARB\fP   0x2014"
.br
.ti -1c
.RI "#define \fBWGL_RED_BITS_ARB\fP   0x2015"
.br
.ti -1c
.RI "#define \fBWGL_RED_SHIFT_ARB\fP   0x2016"
.br
.ti -1c
.RI "#define \fBWGL_GREEN_BITS_ARB\fP   0x2017"
.br
.ti -1c
.RI "#define \fBWGL_GREEN_SHIFT_ARB\fP   0x2018"
.br
.ti -1c
.RI "#define \fBWGL_BLUE_BITS_ARB\fP   0x2019"
.br
.ti -1c
.RI "#define \fBWGL_BLUE_SHIFT_ARB\fP   0x201A"
.br
.ti -1c
.RI "#define \fBWGL_ALPHA_BITS_ARB\fP   0x201B"
.br
.ti -1c
.RI "#define \fBWGL_ALPHA_SHIFT_ARB\fP   0x201C"
.br
.ti -1c
.RI "#define \fBWGL_ACCUM_BITS_ARB\fP   0x201D"
.br
.ti -1c
.RI "#define \fBWGL_ACCUM_RED_BITS_ARB\fP   0x201E"
.br
.ti -1c
.RI "#define \fBWGL_ACCUM_GREEN_BITS_ARB\fP   0x201F"
.br
.ti -1c
.RI "#define \fBWGL_ACCUM_BLUE_BITS_ARB\fP   0x2020"
.br
.ti -1c
.RI "#define \fBWGL_ACCUM_ALPHA_BITS_ARB\fP   0x2021"
.br
.ti -1c
.RI "#define \fBWGL_DEPTH_BITS_ARB\fP   0x2022"
.br
.ti -1c
.RI "#define \fBWGL_STENCIL_BITS_ARB\fP   0x2023"
.br
.ti -1c
.RI "#define \fBWGL_AUX_BUFFERS_ARB\fP   0x2024"
.br
.ti -1c
.RI "#define \fBWGL_NO_ACCELERATION_ARB\fP   0x2025"
.br
.ti -1c
.RI "#define \fBWGL_GENERIC_ACCELERATION_ARB\fP   0x2026"
.br
.ti -1c
.RI "#define \fBWGL_FULL_ACCELERATION_ARB\fP   0x2027"
.br
.ti -1c
.RI "#define \fBWGL_SWAP_EXCHANGE_ARB\fP   0x2028"
.br
.ti -1c
.RI "#define \fBWGL_SWAP_COPY_ARB\fP   0x2029"
.br
.ti -1c
.RI "#define \fBWGL_SWAP_UNDEFINED_ARB\fP   0x202A"
.br
.ti -1c
.RI "#define \fBWGL_TYPE_RGBA_ARB\fP   0x202B"
.br
.ti -1c
.RI "#define \fBWGL_TYPE_COLORINDEX_ARB\fP   0x202C"
.br
.ti -1c
.RI "#define \fBWGL_ARB_pixel_format_float\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_TYPE_RGBA_FLOAT_ARB\fP   0x21A0"
.br
.ti -1c
.RI "#define \fBWGL_ARB_render_texture\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_TEXTURE_RGB_ARB\fP   0x2070"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_TEXTURE_RGBA_ARB\fP   0x2071"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_FORMAT_ARB\fP   0x2072"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_TARGET_ARB\fP   0x2073"
.br
.ti -1c
.RI "#define \fBWGL_MIPMAP_TEXTURE_ARB\fP   0x2074"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_RGB_ARB\fP   0x2075"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_RGBA_ARB\fP   0x2076"
.br
.ti -1c
.RI "#define \fBWGL_NO_TEXTURE_ARB\fP   0x2077"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_CUBE_MAP_ARB\fP   0x2078"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_1D_ARB\fP   0x2079"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_2D_ARB\fP   0x207A"
.br
.ti -1c
.RI "#define \fBWGL_MIPMAP_LEVEL_ARB\fP   0x207B"
.br
.ti -1c
.RI "#define \fBWGL_CUBE_MAP_FACE_ARB\fP   0x207C"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB\fP   0x207D"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB\fP   0x207E"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB\fP   0x207F"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB\fP   0x2080"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB\fP   0x2081"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB\fP   0x2082"
.br
.ti -1c
.RI "#define \fBWGL_FRONT_LEFT_ARB\fP   0x2083"
.br
.ti -1c
.RI "#define \fBWGL_FRONT_RIGHT_ARB\fP   0x2084"
.br
.ti -1c
.RI "#define \fBWGL_BACK_LEFT_ARB\fP   0x2085"
.br
.ti -1c
.RI "#define \fBWGL_BACK_RIGHT_ARB\fP   0x2086"
.br
.ti -1c
.RI "#define \fBWGL_AUX0_ARB\fP   0x2087"
.br
.ti -1c
.RI "#define \fBWGL_AUX1_ARB\fP   0x2088"
.br
.ti -1c
.RI "#define \fBWGL_AUX2_ARB\fP   0x2089"
.br
.ti -1c
.RI "#define \fBWGL_AUX3_ARB\fP   0x208A"
.br
.ti -1c
.RI "#define \fBWGL_AUX4_ARB\fP   0x208B"
.br
.ti -1c
.RI "#define \fBWGL_AUX5_ARB\fP   0x208C"
.br
.ti -1c
.RI "#define \fBWGL_AUX6_ARB\fP   0x208D"
.br
.ti -1c
.RI "#define \fBWGL_AUX7_ARB\fP   0x208E"
.br
.ti -1c
.RI "#define \fBWGL_AUX8_ARB\fP   0x208F"
.br
.ti -1c
.RI "#define \fBWGL_AUX9_ARB\fP   0x2090"
.br
.ti -1c
.RI "#define \fBWGL_ARB_robustness_application_isolation\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_RESET_ISOLATION_BIT_ARB\fP   0x00000008"
.br
.ti -1c
.RI "#define \fBWGL_ARB_robustness_share_group_isolation\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_3DFX_multisample\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_SAMPLE_BUFFERS_3DFX\fP   0x2060"
.br
.ti -1c
.RI "#define \fBWGL_SAMPLES_3DFX\fP   0x2061"
.br
.ti -1c
.RI "#define \fBWGL_3DL_stereo_control\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_STEREO_EMITTER_ENABLE_3DL\fP   0x2055"
.br
.ti -1c
.RI "#define \fBWGL_STEREO_EMITTER_DISABLE_3DL\fP   0x2056"
.br
.ti -1c
.RI "#define \fBWGL_STEREO_POLARITY_NORMAL_3DL\fP   0x2057"
.br
.ti -1c
.RI "#define \fBWGL_STEREO_POLARITY_INVERT_3DL\fP   0x2058"
.br
.ti -1c
.RI "#define \fBWGL_AMD_gpu_association\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_GPU_VENDOR_AMD\fP   0x1F00"
.br
.ti -1c
.RI "#define \fBWGL_GPU_RENDERER_STRING_AMD\fP   0x1F01"
.br
.ti -1c
.RI "#define \fBWGL_GPU_OPENGL_VERSION_STRING_AMD\fP   0x1F02"
.br
.ti -1c
.RI "#define \fBWGL_GPU_FASTEST_TARGET_GPUS_AMD\fP   0x21A2"
.br
.ti -1c
.RI "#define \fBWGL_GPU_RAM_AMD\fP   0x21A3"
.br
.ti -1c
.RI "#define \fBWGL_GPU_CLOCK_AMD\fP   0x21A4"
.br
.ti -1c
.RI "#define \fBWGL_GPU_NUM_PIPES_AMD\fP   0x21A5"
.br
.ti -1c
.RI "#define \fBWGL_GPU_NUM_SIMD_AMD\fP   0x21A6"
.br
.ti -1c
.RI "#define \fBWGL_GPU_NUM_RB_AMD\fP   0x21A7"
.br
.ti -1c
.RI "#define \fBWGL_GPU_NUM_SPI_AMD\fP   0x21A8"
.br
.ti -1c
.RI "#define \fBWGL_ATI_pixel_format_float\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_TYPE_RGBA_FLOAT_ATI\fP   0x21A0"
.br
.ti -1c
.RI "#define \fBWGL_EXT_create_context_es2_profile\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_ES2_PROFILE_BIT_EXT\fP   0x00000004"
.br
.ti -1c
.RI "#define \fBWGL_EXT_create_context_es_profile\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_CONTEXT_ES_PROFILE_BIT_EXT\fP   0x00000004"
.br
.ti -1c
.RI "#define \fBWGL_EXT_depth_float\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_DEPTH_FLOAT_EXT\fP   0x2040"
.br
.ti -1c
.RI "#define \fBWGL_EXT_display_color_table\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_EXT_extensions_string\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_EXT_framebuffer_sRGB\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_FRAMEBUFFER_SRGB_CAPABLE_EXT\fP   0x20A9"
.br
.ti -1c
.RI "#define \fBWGL_EXT_make_current_read\fP   1"
.br
.ti -1c
.RI "#define \fBERROR_INVALID_PIXEL_TYPE_EXT\fP   0x2043"
.br
.ti -1c
.RI "#define \fBWGL_EXT_multisample\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_SAMPLE_BUFFERS_EXT\fP   0x2041"
.br
.ti -1c
.RI "#define \fBWGL_SAMPLES_EXT\fP   0x2042"
.br
.ti -1c
.RI "#define \fBWGL_EXT_pbuffer\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_DRAW_TO_PBUFFER_EXT\fP   0x202D"
.br
.ti -1c
.RI "#define \fBWGL_MAX_PBUFFER_PIXELS_EXT\fP   0x202E"
.br
.ti -1c
.RI "#define \fBWGL_MAX_PBUFFER_WIDTH_EXT\fP   0x202F"
.br
.ti -1c
.RI "#define \fBWGL_MAX_PBUFFER_HEIGHT_EXT\fP   0x2030"
.br
.ti -1c
.RI "#define \fBWGL_OPTIMAL_PBUFFER_WIDTH_EXT\fP   0x2031"
.br
.ti -1c
.RI "#define \fBWGL_OPTIMAL_PBUFFER_HEIGHT_EXT\fP   0x2032"
.br
.ti -1c
.RI "#define \fBWGL_PBUFFER_LARGEST_EXT\fP   0x2033"
.br
.ti -1c
.RI "#define \fBWGL_PBUFFER_WIDTH_EXT\fP   0x2034"
.br
.ti -1c
.RI "#define \fBWGL_PBUFFER_HEIGHT_EXT\fP   0x2035"
.br
.ti -1c
.RI "#define \fBWGL_EXT_pixel_format\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_NUMBER_PIXEL_FORMATS_EXT\fP   0x2000"
.br
.ti -1c
.RI "#define \fBWGL_DRAW_TO_WINDOW_EXT\fP   0x2001"
.br
.ti -1c
.RI "#define \fBWGL_DRAW_TO_BITMAP_EXT\fP   0x2002"
.br
.ti -1c
.RI "#define \fBWGL_ACCELERATION_EXT\fP   0x2003"
.br
.ti -1c
.RI "#define \fBWGL_NEED_PALETTE_EXT\fP   0x2004"
.br
.ti -1c
.RI "#define \fBWGL_NEED_SYSTEM_PALETTE_EXT\fP   0x2005"
.br
.ti -1c
.RI "#define \fBWGL_SWAP_LAYER_BUFFERS_EXT\fP   0x2006"
.br
.ti -1c
.RI "#define \fBWGL_SWAP_METHOD_EXT\fP   0x2007"
.br
.ti -1c
.RI "#define \fBWGL_NUMBER_OVERLAYS_EXT\fP   0x2008"
.br
.ti -1c
.RI "#define \fBWGL_NUMBER_UNDERLAYS_EXT\fP   0x2009"
.br
.ti -1c
.RI "#define \fBWGL_TRANSPARENT_EXT\fP   0x200A"
.br
.ti -1c
.RI "#define \fBWGL_TRANSPARENT_VALUE_EXT\fP   0x200B"
.br
.ti -1c
.RI "#define \fBWGL_SHARE_DEPTH_EXT\fP   0x200C"
.br
.ti -1c
.RI "#define \fBWGL_SHARE_STENCIL_EXT\fP   0x200D"
.br
.ti -1c
.RI "#define \fBWGL_SHARE_ACCUM_EXT\fP   0x200E"
.br
.ti -1c
.RI "#define \fBWGL_SUPPORT_GDI_EXT\fP   0x200F"
.br
.ti -1c
.RI "#define \fBWGL_SUPPORT_OPENGL_EXT\fP   0x2010"
.br
.ti -1c
.RI "#define \fBWGL_DOUBLE_BUFFER_EXT\fP   0x2011"
.br
.ti -1c
.RI "#define \fBWGL_STEREO_EXT\fP   0x2012"
.br
.ti -1c
.RI "#define \fBWGL_PIXEL_TYPE_EXT\fP   0x2013"
.br
.ti -1c
.RI "#define \fBWGL_COLOR_BITS_EXT\fP   0x2014"
.br
.ti -1c
.RI "#define \fBWGL_RED_BITS_EXT\fP   0x2015"
.br
.ti -1c
.RI "#define \fBWGL_RED_SHIFT_EXT\fP   0x2016"
.br
.ti -1c
.RI "#define \fBWGL_GREEN_BITS_EXT\fP   0x2017"
.br
.ti -1c
.RI "#define \fBWGL_GREEN_SHIFT_EXT\fP   0x2018"
.br
.ti -1c
.RI "#define \fBWGL_BLUE_BITS_EXT\fP   0x2019"
.br
.ti -1c
.RI "#define \fBWGL_BLUE_SHIFT_EXT\fP   0x201A"
.br
.ti -1c
.RI "#define \fBWGL_ALPHA_BITS_EXT\fP   0x201B"
.br
.ti -1c
.RI "#define \fBWGL_ALPHA_SHIFT_EXT\fP   0x201C"
.br
.ti -1c
.RI "#define \fBWGL_ACCUM_BITS_EXT\fP   0x201D"
.br
.ti -1c
.RI "#define \fBWGL_ACCUM_RED_BITS_EXT\fP   0x201E"
.br
.ti -1c
.RI "#define \fBWGL_ACCUM_GREEN_BITS_EXT\fP   0x201F"
.br
.ti -1c
.RI "#define \fBWGL_ACCUM_BLUE_BITS_EXT\fP   0x2020"
.br
.ti -1c
.RI "#define \fBWGL_ACCUM_ALPHA_BITS_EXT\fP   0x2021"
.br
.ti -1c
.RI "#define \fBWGL_DEPTH_BITS_EXT\fP   0x2022"
.br
.ti -1c
.RI "#define \fBWGL_STENCIL_BITS_EXT\fP   0x2023"
.br
.ti -1c
.RI "#define \fBWGL_AUX_BUFFERS_EXT\fP   0x2024"
.br
.ti -1c
.RI "#define \fBWGL_NO_ACCELERATION_EXT\fP   0x2025"
.br
.ti -1c
.RI "#define \fBWGL_GENERIC_ACCELERATION_EXT\fP   0x2026"
.br
.ti -1c
.RI "#define \fBWGL_FULL_ACCELERATION_EXT\fP   0x2027"
.br
.ti -1c
.RI "#define \fBWGL_SWAP_EXCHANGE_EXT\fP   0x2028"
.br
.ti -1c
.RI "#define \fBWGL_SWAP_COPY_EXT\fP   0x2029"
.br
.ti -1c
.RI "#define \fBWGL_SWAP_UNDEFINED_EXT\fP   0x202A"
.br
.ti -1c
.RI "#define \fBWGL_TYPE_RGBA_EXT\fP   0x202B"
.br
.ti -1c
.RI "#define \fBWGL_TYPE_COLORINDEX_EXT\fP   0x202C"
.br
.ti -1c
.RI "#define \fBWGL_EXT_pixel_format_packed_float\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT\fP   0x20A8"
.br
.ti -1c
.RI "#define \fBWGL_EXT_swap_control\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_EXT_swap_control_tear\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_I3D_digital_video_control\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D\fP   0x2050"
.br
.ti -1c
.RI "#define \fBWGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D\fP   0x2051"
.br
.ti -1c
.RI "#define \fBWGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D\fP   0x2052"
.br
.ti -1c
.RI "#define \fBWGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D\fP   0x2053"
.br
.ti -1c
.RI "#define \fBWGL_I3D_gamma\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_GAMMA_TABLE_SIZE_I3D\fP   0x204E"
.br
.ti -1c
.RI "#define \fBWGL_GAMMA_EXCLUDE_DESKTOP_I3D\fP   0x204F"
.br
.ti -1c
.RI "#define \fBWGL_I3D_genlock\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_GENLOCK_SOURCE_MULTIVIEW_I3D\fP   0x2044"
.br
.ti -1c
.RI "#define \fBWGL_GENLOCK_SOURCE_EXTERNAL_SYNC_I3D\fP   0x2045"
.br
.ti -1c
.RI "#define \fBWGL_GENLOCK_SOURCE_EXTERNAL_FIELD_I3D\fP   0x2046"
.br
.ti -1c
.RI "#define \fBWGL_GENLOCK_SOURCE_EXTERNAL_TTL_I3D\fP   0x2047"
.br
.ti -1c
.RI "#define \fBWGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D\fP   0x2048"
.br
.ti -1c
.RI "#define \fBWGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D\fP   0x2049"
.br
.ti -1c
.RI "#define \fBWGL_GENLOCK_SOURCE_EDGE_FALLING_I3D\fP   0x204A"
.br
.ti -1c
.RI "#define \fBWGL_GENLOCK_SOURCE_EDGE_RISING_I3D\fP   0x204B"
.br
.ti -1c
.RI "#define \fBWGL_GENLOCK_SOURCE_EDGE_BOTH_I3D\fP   0x204C"
.br
.ti -1c
.RI "#define \fBWGL_I3D_image_buffer\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_IMAGE_BUFFER_MIN_ACCESS_I3D\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBWGL_IMAGE_BUFFER_LOCK_I3D\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBWGL_I3D_swap_frame_lock\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_I3D_swap_frame_usage\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_NV_DX_interop\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_ACCESS_READ_ONLY_NV\fP   0x00000000"
.br
.ti -1c
.RI "#define \fBWGL_ACCESS_READ_WRITE_NV\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBWGL_ACCESS_WRITE_DISCARD_NV\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBWGL_NV_DX_interop2\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_NV_copy_image\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_NV_delay_before_swap\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_NV_float_buffer\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_FLOAT_COMPONENTS_NV\fP   0x20B0"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV\fP   0x20B1"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV\fP   0x20B2"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV\fP   0x20B3"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV\fP   0x20B4"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_FLOAT_R_NV\fP   0x20B5"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_FLOAT_RG_NV\fP   0x20B6"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_FLOAT_RGB_NV\fP   0x20B7"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_FLOAT_RGBA_NV\fP   0x20B8"
.br
.ti -1c
.RI "#define \fBWGL_NV_gpu_affinity\fP   1"
.br
.ti -1c
.RI "#define \fBERROR_INCOMPATIBLE_AFFINITY_MASKS_NV\fP   0x20D0"
.br
.ti -1c
.RI "#define \fBERROR_MISSING_AFFINITY_MASK_NV\fP   0x20D1"
.br
.ti -1c
.RI "#define \fBWGL_NV_multisample_coverage\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_COVERAGE_SAMPLES_NV\fP   0x2042"
.br
.ti -1c
.RI "#define \fBWGL_COLOR_SAMPLES_NV\fP   0x20B9"
.br
.ti -1c
.RI "#define \fBWGL_NV_present_video\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_NUM_VIDEO_SLOTS_NV\fP   0x20F0"
.br
.ti -1c
.RI "#define \fBWGL_NV_render_depth_texture\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_TEXTURE_DEPTH_NV\fP   0x20A3"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV\fP   0x20A4"
.br
.ti -1c
.RI "#define \fBWGL_DEPTH_TEXTURE_FORMAT_NV\fP   0x20A5"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_DEPTH_COMPONENT_NV\fP   0x20A6"
.br
.ti -1c
.RI "#define \fBWGL_DEPTH_COMPONENT_NV\fP   0x20A7"
.br
.ti -1c
.RI "#define \fBWGL_NV_render_texture_rectangle\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_TEXTURE_RECTANGLE_RGB_NV\fP   0x20A0"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_TEXTURE_RECTANGLE_RGBA_NV\fP   0x20A1"
.br
.ti -1c
.RI "#define \fBWGL_TEXTURE_RECTANGLE_NV\fP   0x20A2"
.br
.ti -1c
.RI "#define \fBWGL_NV_swap_group\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_NV_vertex_array_range\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_NV_video_capture\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_UNIQUE_ID_NV\fP   0x20CE"
.br
.ti -1c
.RI "#define \fBWGL_NUM_VIDEO_CAPTURE_SLOTS_NV\fP   0x20CF"
.br
.ti -1c
.RI "#define \fBWGL_NV_video_output\fP   1"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_VIDEO_RGB_NV\fP   0x20C0"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_VIDEO_RGBA_NV\fP   0x20C1"
.br
.ti -1c
.RI "#define \fBWGL_BIND_TO_VIDEO_RGB_AND_DEPTH_NV\fP   0x20C2"
.br
.ti -1c
.RI "#define \fBWGL_VIDEO_OUT_COLOR_NV\fP   0x20C3"
.br
.ti -1c
.RI "#define \fBWGL_VIDEO_OUT_ALPHA_NV\fP   0x20C4"
.br
.ti -1c
.RI "#define \fBWGL_VIDEO_OUT_DEPTH_NV\fP   0x20C5"
.br
.ti -1c
.RI "#define \fBWGL_VIDEO_OUT_COLOR_AND_ALPHA_NV\fP   0x20C6"
.br
.ti -1c
.RI "#define \fBWGL_VIDEO_OUT_COLOR_AND_DEPTH_NV\fP   0x20C7"
.br
.ti -1c
.RI "#define \fBWGL_VIDEO_OUT_FRAME\fP   0x20C8"
.br
.ti -1c
.RI "#define \fBWGL_VIDEO_OUT_FIELD_1\fP   0x20C9"
.br
.ti -1c
.RI "#define \fBWGL_VIDEO_OUT_FIELD_2\fP   0x20CA"
.br
.ti -1c
.RI "#define \fBWGL_VIDEO_OUT_STACKED_FIELDS_1_2\fP   0x20CB"
.br
.ti -1c
.RI "#define \fBWGL_VIDEO_OUT_STACKED_FIELDS_2_1\fP   0x20CC"
.br
.ti -1c
.RI "#define \fBWGL_OML_sync_control\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef HANDLE(WINAPI * \fBPFNWGLCREATEBUFFERREGIONARBPROC\fP) (HDC hDC, int iLayerPlane, UINT uType)"
.br
.ti -1c
.RI "typedef VOID(WINAPI * \fBPFNWGLDELETEBUFFERREGIONARBPROC\fP) (HANDLE hRegion)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLSAVEBUFFERREGIONARBPROC\fP) (HANDLE hRegion, int \fBx\fP, int \fBy\fP, int \fBwidth\fP, int \fBheight\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLRESTOREBUFFERREGIONARBPROC\fP) (HANDLE hRegion, int \fBx\fP, int \fBy\fP, int \fBwidth\fP, int \fBheight\fP, int xSrc, int ySrc)"
.br
.ti -1c
.RI "typedef HGLRC(WINAPI * \fBPFNWGLCREATECONTEXTATTRIBSARBPROC\fP) (HDC hDC, HGLRC hShareContext, const int *attribList)"
.br
.ti -1c
.RI "typedef const char *(WINAPI * \fBPFNWGLGETEXTENSIONSSTRINGARBPROC\fP) (HDC hdc)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLMAKECONTEXTCURRENTARBPROC\fP) (HDC hDrawDC, HDC hReadDC, HGLRC hglrc)"
.br
.ti -1c
.RI "typedef HDC(WINAPI * \fBPFNWGLGETCURRENTREADDCARBPROC\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef HPBUFFERARB(WINAPI * \fBPFNWGLCREATEPBUFFERARBPROC\fP) (HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int *piAttribList)"
.br
.ti -1c
.RI "typedef HDC(WINAPI * \fBPFNWGLGETPBUFFERDCARBPROC\fP) (HPBUFFERARB hPbuffer)"
.br
.ti -1c
.RI "typedef int(WINAPI * \fBPFNWGLRELEASEPBUFFERDCARBPROC\fP) (HPBUFFERARB hPbuffer, HDC hDC)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDESTROYPBUFFERARBPROC\fP) (HPBUFFERARB hPbuffer)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLQUERYPBUFFERARBPROC\fP) (HPBUFFERARB hPbuffer, int iAttribute, int *piValue)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETPIXELFORMATATTRIBIVARBPROC\fP) (HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int *piAttributes, int *piValues)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETPIXELFORMATATTRIBFVARBPROC\fP) (HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int *piAttributes, FLOAT *pfValues)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLCHOOSEPIXELFORMATARBPROC\fP) (HDC hdc, const int *piAttribIList, const FLOAT *pfAttribFList, UINT nMaxFormats, int *piFormats, UINT *nNumFormats)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLBINDTEXIMAGEARBPROC\fP) (HPBUFFERARB hPbuffer, int iBuffer)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLRELEASETEXIMAGEARBPROC\fP) (HPBUFFERARB hPbuffer, int iBuffer)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLSETPBUFFERATTRIBARBPROC\fP) (HPBUFFERARB hPbuffer, const int *piAttribList)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLSETSTEREOEMITTERSTATE3DLPROC\fP) (HDC hDC, UINT uState)"
.br
.ti -1c
.RI "typedef UINT(WINAPI * \fBPFNWGLGETGPUIDSAMDPROC\fP) (UINT \fBmaxCount\fP, UINT *\fBids\fP)"
.br
.ti -1c
.RI "typedef INT(WINAPI * \fBPFNWGLGETGPUINFOAMDPROC\fP) (UINT \fBid\fP, int property, \fBGLenum\fP dataType, UINT \fBsize\fP, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "typedef UINT(WINAPI * \fBPFNWGLGETCONTEXTGPUIDAMDPROC\fP) (HGLRC hglrc)"
.br
.ti -1c
.RI "typedef HGLRC(WINAPI * \fBPFNWGLCREATEASSOCIATEDCONTEXTAMDPROC\fP) (UINT \fBid\fP)"
.br
.ti -1c
.RI "typedef HGLRC(WINAPI * \fBPFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC\fP) (UINT \fBid\fP, HGLRC hShareContext, const int *attribList)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDELETEASSOCIATEDCONTEXTAMDPROC\fP) (HGLRC hglrc)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC\fP) (HGLRC hglrc)"
.br
.ti -1c
.RI "typedef HGLRC(WINAPI * \fBPFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef VOID(WINAPI * \fBPFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC\fP) (HGLRC dstCtx, \fBGLint\fP \fBsrcX0\fP, \fBGLint\fP \fBsrcY0\fP, \fBGLint\fP \fBsrcX1\fP, \fBGLint\fP \fBsrcY1\fP, \fBGLint\fP \fBdstX0\fP, \fBGLint\fP \fBdstY0\fP, \fBGLint\fP \fBdstX1\fP, \fBGLint\fP \fBdstY1\fP, \fBGLbitfield\fP \fBmask\fP, \fBGLenum\fP \fBfilter\fP)"
.br
.ti -1c
.RI "typedef \fBGLboolean\fP(WINAPI * \fBPFNWGLCREATEDISPLAYCOLORTABLEEXTPROC\fP) (\fBGLushort\fP \fBid\fP)"
.br
.ti -1c
.RI "typedef \fBGLboolean\fP(WINAPI * \fBPFNWGLLOADDISPLAYCOLORTABLEEXTPROC\fP) (const \fBGLushort\fP *table, \fBGLuint\fP \fBlength\fP)"
.br
.ti -1c
.RI "typedef \fBGLboolean\fP(WINAPI * \fBPFNWGLBINDDISPLAYCOLORTABLEEXTPROC\fP) (\fBGLushort\fP \fBid\fP)"
.br
.ti -1c
.RI "typedef VOID(WINAPI * \fBPFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC\fP) (\fBGLushort\fP \fBid\fP)"
.br
.ti -1c
.RI "typedef const char *(WINAPI * \fBPFNWGLGETEXTENSIONSSTRINGEXTPROC\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLMAKECONTEXTCURRENTEXTPROC\fP) (HDC hDrawDC, HDC hReadDC, HGLRC hglrc)"
.br
.ti -1c
.RI "typedef HDC(WINAPI * \fBPFNWGLGETCURRENTREADDCEXTPROC\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef HPBUFFEREXT(WINAPI * \fBPFNWGLCREATEPBUFFEREXTPROC\fP) (HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int *piAttribList)"
.br
.ti -1c
.RI "typedef HDC(WINAPI * \fBPFNWGLGETPBUFFERDCEXTPROC\fP) (HPBUFFEREXT hPbuffer)"
.br
.ti -1c
.RI "typedef int(WINAPI * \fBPFNWGLRELEASEPBUFFERDCEXTPROC\fP) (HPBUFFEREXT hPbuffer, HDC hDC)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDESTROYPBUFFEREXTPROC\fP) (HPBUFFEREXT hPbuffer)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLQUERYPBUFFEREXTPROC\fP) (HPBUFFEREXT hPbuffer, int iAttribute, int *piValue)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETPIXELFORMATATTRIBIVEXTPROC\fP) (HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int *piAttributes, int *piValues)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETPIXELFORMATATTRIBFVEXTPROC\fP) (HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int *piAttributes, FLOAT *pfValues)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLCHOOSEPIXELFORMATEXTPROC\fP) (HDC hdc, const int *piAttribIList, const FLOAT *pfAttribFList, UINT nMaxFormats, int *piFormats, UINT *nNumFormats)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLSWAPINTERVALEXTPROC\fP) (int interval)"
.br
.ti -1c
.RI "typedef int(WINAPI * \fBPFNWGLGETSWAPINTERVALEXTPROC\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC\fP) (HDC hDC, int iAttribute, int *piValue)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC\fP) (HDC hDC, int iAttribute, const int *piValue)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETGAMMATABLEPARAMETERSI3DPROC\fP) (HDC hDC, int iAttribute, int *piValue)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLSETGAMMATABLEPARAMETERSI3DPROC\fP) (HDC hDC, int iAttribute, const int *piValue)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETGAMMATABLEI3DPROC\fP) (HDC hDC, int iEntries, USHORT *puRed, USHORT *puGreen, USHORT *puBlue)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLSETGAMMATABLEI3DPROC\fP) (HDC hDC, int iEntries, const USHORT *puRed, const USHORT *puGreen, const USHORT *puBlue)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLENABLEGENLOCKI3DPROC\fP) (HDC hDC)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDISABLEGENLOCKI3DPROC\fP) (HDC hDC)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLISENABLEDGENLOCKI3DPROC\fP) (HDC hDC, BOOL *pFlag)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGENLOCKSOURCEI3DPROC\fP) (HDC hDC, UINT uSource)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETGENLOCKSOURCEI3DPROC\fP) (HDC hDC, UINT *uSource)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGENLOCKSOURCEEDGEI3DPROC\fP) (HDC hDC, UINT uEdge)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETGENLOCKSOURCEEDGEI3DPROC\fP) (HDC hDC, UINT *uEdge)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGENLOCKSAMPLERATEI3DPROC\fP) (HDC hDC, UINT uRate)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETGENLOCKSAMPLERATEI3DPROC\fP) (HDC hDC, UINT *uRate)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGENLOCKSOURCEDELAYI3DPROC\fP) (HDC hDC, UINT uDelay)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETGENLOCKSOURCEDELAYI3DPROC\fP) (HDC hDC, UINT *uDelay)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC\fP) (HDC hDC, UINT *uMaxLineDelay, UINT *uMaxPixelDelay)"
.br
.ti -1c
.RI "typedef LPVOID(WINAPI * \fBPFNWGLCREATEIMAGEBUFFERI3DPROC\fP) (HDC hDC, DWORD dwSize, UINT uFlags)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDESTROYIMAGEBUFFERI3DPROC\fP) (HDC hDC, LPVOID pAddress)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC\fP) (HDC hDC, const HANDLE *pEvent, const LPVOID *pAddress, const DWORD *pSize, UINT \fBcount\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC\fP) (HDC hDC, const LPVOID *pAddress, UINT \fBcount\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLENABLEFRAMELOCKI3DPROC\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDISABLEFRAMELOCKI3DPROC\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLISENABLEDFRAMELOCKI3DPROC\fP) (BOOL *pFlag)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLQUERYFRAMELOCKMASTERI3DPROC\fP) (BOOL *pFlag)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETFRAMEUSAGEI3DPROC\fP) (float *pUsage)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLBEGINFRAMETRACKINGI3DPROC\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLENDFRAMETRACKINGI3DPROC\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLQUERYFRAMETRACKINGI3DPROC\fP) (DWORD *pFrameCount, DWORD *pMissedFrames, float *pLastMissedUsage)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDXSETRESOURCESHAREHANDLENVPROC\fP) (\fBvoid\fP *dxObject, HANDLE shareHandle)"
.br
.ti -1c
.RI "typedef HANDLE(WINAPI * \fBPFNWGLDXOPENDEVICENVPROC\fP) (\fBvoid\fP *dxDevice)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDXCLOSEDEVICENVPROC\fP) (HANDLE hDevice)"
.br
.ti -1c
.RI "typedef HANDLE(WINAPI * \fBPFNWGLDXREGISTEROBJECTNVPROC\fP) (HANDLE hDevice, \fBvoid\fP *dxObject, \fBGLuint\fP \fBname\fP, \fBGLenum\fP \fBtype\fP, \fBGLenum\fP \fBaccess\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDXUNREGISTEROBJECTNVPROC\fP) (HANDLE hDevice, HANDLE hObject)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDXOBJECTACCESSNVPROC\fP) (HANDLE hObject, \fBGLenum\fP \fBaccess\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDXLOCKOBJECTSNVPROC\fP) (HANDLE hDevice, \fBGLint\fP \fBcount\fP, HANDLE *hObjects)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDXUNLOCKOBJECTSNVPROC\fP) (HANDLE hDevice, \fBGLint\fP \fBcount\fP, HANDLE *hObjects)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLCOPYIMAGESUBDATANVPROC\fP) (HGLRC hSrcRC, \fBGLuint\fP srcName, \fBGLenum\fP \fBsrcTarget\fP, \fBGLint\fP \fBsrcLevel\fP, \fBGLint\fP \fBsrcX\fP, \fBGLint\fP \fBsrcY\fP, \fBGLint\fP \fBsrcZ\fP, HGLRC hDstRC, \fBGLuint\fP \fBdstName\fP, \fBGLenum\fP \fBdstTarget\fP, \fBGLint\fP \fBdstLevel\fP, \fBGLint\fP \fBdstX\fP, \fBGLint\fP \fBdstY\fP, \fBGLint\fP \fBdstZ\fP, \fBGLsizei\fP \fBwidth\fP, \fBGLsizei\fP \fBheight\fP, \fBGLsizei\fP \fBdepth\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDELAYBEFORESWAPNVPROC\fP) (HDC hDC, \fBGLfloat\fP seconds)"
.br
.ti -1c
.RI "typedef struct \fB_GPU_DEVICE\fP * \fBPGPU_DEVICE\fP"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLENUMGPUSNVPROC\fP) (UINT iGpuIndex, HGPUNV *phGpu)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLENUMGPUDEVICESNVPROC\fP) (HGPUNV hGpu, UINT iDeviceIndex, \fBPGPU_DEVICE\fP lpGpuDevice)"
.br
.ti -1c
.RI "typedef HDC(WINAPI * \fBPFNWGLCREATEAFFINITYDCNVPROC\fP) (const HGPUNV *phGpuList)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLENUMGPUSFROMAFFINITYDCNVPROC\fP) (HDC hAffinityDC, UINT iGpuIndex, HGPUNV *hGpu)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLDELETEDCNVPROC\fP) (HDC hdc)"
.br
.ti -1c
.RI "typedef int(WINAPI * \fBPFNWGLENUMERATEVIDEODEVICESNVPROC\fP) (HDC hDC, HVIDEOOUTPUTDEVICENV *phDeviceList)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLBINDVIDEODEVICENVPROC\fP) (HDC hDC, unsigned int uVideoSlot, HVIDEOOUTPUTDEVICENV hVideoDevice, const int *piAttribList)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLQUERYCURRENTCONTEXTNVPROC\fP) (int iAttribute, int *piValue)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLJOINSWAPGROUPNVPROC\fP) (HDC hDC, \fBGLuint\fP group)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLBINDSWAPBARRIERNVPROC\fP) (\fBGLuint\fP group, \fBGLuint\fP barrier)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLQUERYSWAPGROUPNVPROC\fP) (HDC hDC, \fBGLuint\fP *group, \fBGLuint\fP *barrier)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLQUERYMAXSWAPGROUPSNVPROC\fP) (HDC hDC, \fBGLuint\fP *maxGroups, \fBGLuint\fP *maxBarriers)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLQUERYFRAMECOUNTNVPROC\fP) (HDC hDC, \fBGLuint\fP *\fBcount\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLRESETFRAMECOUNTNVPROC\fP) (HDC hDC)"
.br
.ti -1c
.RI "typedef \fBvoid\fP *(WINAPI * \fBPFNWGLALLOCATEMEMORYNVPROC\fP) (\fBGLsizei\fP \fBsize\fP, \fBGLfloat\fP readfreq, \fBGLfloat\fP writefreq, \fBGLfloat\fP priority)"
.br
.ti -1c
.RI "typedef \fBvoid\fP(WINAPI * \fBPFNWGLFREEMEMORYNVPROC\fP) (\fBvoid\fP *\fBpointer\fP)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLBINDVIDEOCAPTUREDEVICENVPROC\fP) (UINT uVideoSlot, HVIDEOINPUTDEVICENV hDevice)"
.br
.ti -1c
.RI "typedef UINT(WINAPI * \fBPFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC\fP) (HDC hDc, HVIDEOINPUTDEVICENV *phDeviceList)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLLOCKVIDEOCAPTUREDEVICENVPROC\fP) (HDC hDc, HVIDEOINPUTDEVICENV hDevice)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLQUERYVIDEOCAPTUREDEVICENVPROC\fP) (HDC hDc, HVIDEOINPUTDEVICENV hDevice, int iAttribute, int *piValue)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC\fP) (HDC hDc, HVIDEOINPUTDEVICENV hDevice)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETVIDEODEVICENVPROC\fP) (HDC hDC, int numDevices, HPVIDEODEV *hVideoDevice)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLRELEASEVIDEODEVICENVPROC\fP) (HPVIDEODEV hVideoDevice)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLBINDVIDEOIMAGENVPROC\fP) (HPVIDEODEV hVideoDevice, HPBUFFERARB hPbuffer, int iVideoBuffer)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLRELEASEVIDEOIMAGENVPROC\fP) (HPBUFFERARB hPbuffer, int iVideoBuffer)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLSENDPBUFFERTOVIDEONVPROC\fP) (HPBUFFERARB hPbuffer, int iBufferType, unsigned long *pulCounterPbuffer, BOOL bBlock)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETVIDEOINFONVPROC\fP) (HPVIDEODEV hpVideoDevice, unsigned long *pulCounterOutputPbuffer, unsigned long *pulCounterOutputVideo)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETSYNCVALUESOMLPROC\fP) (HDC hdc, INT64 *ust, INT64 *msc, INT64 *sbc)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLGETMSCRATEOMLPROC\fP) (HDC hdc, INT32 *numerator, INT32 *denominator)"
.br
.ti -1c
.RI "typedef INT64(WINAPI * \fBPFNWGLSWAPBUFFERSMSCOMLPROC\fP) (HDC hdc, INT64 target_msc, INT64 \fBdivisor\fP, INT64 remainder)"
.br
.ti -1c
.RI "typedef INT64(WINAPI * \fBPFNWGLSWAPLAYERBUFFERSMSCOMLPROC\fP) (HDC hdc, int fuPlanes, INT64 target_msc, INT64 \fBdivisor\fP, INT64 remainder)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLWAITFORMSCOMLPROC\fP) (HDC hdc, INT64 target_msc, INT64 \fBdivisor\fP, INT64 remainder, INT64 *ust, INT64 *msc, INT64 *sbc)"
.br
.ti -1c
.RI "typedef BOOL(WINAPI * \fBPFNWGLWAITFORSBCOMLPROC\fP) (HDC hdc, INT64 target_sbc, INT64 *ust, INT64 *msc, INT64 *sbc)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDECLARE_HANDLE\fP (HPBUFFERARB)"
.br
.ti -1c
.RI "\fBDECLARE_HANDLE\fP (HPBUFFEREXT)"
.br
.ti -1c
.RI "\fBDECLARE_HANDLE\fP (HGPUNV)"
.br
.ti -1c
.RI "\fBDECLARE_HANDLE\fP (HVIDEOOUTPUTDEVICENV)"
.br
.ti -1c
.RI "\fBDECLARE_HANDLE\fP (HVIDEOINPUTDEVICENV)"
.br
.ti -1c
.RI "\fBDECLARE_HANDLE\fP (HPVIDEODEV)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV   0x20D0"

.SS "#define ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB   0x2054"

.SS "#define ERROR_INVALID_PIXEL_TYPE_ARB   0x2043"

.SS "#define ERROR_INVALID_PIXEL_TYPE_EXT   0x2043"

.SS "#define ERROR_INVALID_PROFILE_ARB   0x2096"

.SS "#define ERROR_INVALID_VERSION_ARB   0x2095"

.SS "#define ERROR_MISSING_AFFINITY_MASK_NV   0x20D1"

.SS "#define WGL_3DFX_multisample   1"

.SS "#define WGL_3DL_stereo_control   1"

.SS "#define WGL_ACCELERATION_ARB   0x2003"

.SS "#define WGL_ACCELERATION_EXT   0x2003"

.SS "#define WGL_ACCESS_READ_ONLY_NV   0x00000000"

.SS "#define WGL_ACCESS_READ_WRITE_NV   0x00000001"

.SS "#define WGL_ACCESS_WRITE_DISCARD_NV   0x00000002"

.SS "#define WGL_ACCUM_ALPHA_BITS_ARB   0x2021"

.SS "#define WGL_ACCUM_ALPHA_BITS_EXT   0x2021"

.SS "#define WGL_ACCUM_BITS_ARB   0x201D"

.SS "#define WGL_ACCUM_BITS_EXT   0x201D"

.SS "#define WGL_ACCUM_BLUE_BITS_ARB   0x2020"

.SS "#define WGL_ACCUM_BLUE_BITS_EXT   0x2020"

.SS "#define WGL_ACCUM_GREEN_BITS_ARB   0x201F"

.SS "#define WGL_ACCUM_GREEN_BITS_EXT   0x201F"

.SS "#define WGL_ACCUM_RED_BITS_ARB   0x201E"

.SS "#define WGL_ACCUM_RED_BITS_EXT   0x201E"

.SS "#define WGL_ALPHA_BITS_ARB   0x201B"

.SS "#define WGL_ALPHA_BITS_EXT   0x201B"

.SS "#define WGL_ALPHA_SHIFT_ARB   0x201C"

.SS "#define WGL_ALPHA_SHIFT_EXT   0x201C"

.SS "#define WGL_AMD_gpu_association   1"

.SS "#define WGL_ARB_buffer_region   1"

.SS "#define WGL_ARB_context_flush_control   1"

.SS "#define WGL_ARB_create_context   1"

.SS "#define WGL_ARB_create_context_profile   1"

.SS "#define WGL_ARB_create_context_robustness   1"

.SS "#define WGL_ARB_extensions_string   1"

.SS "#define WGL_ARB_framebuffer_sRGB   1"

.SS "#define WGL_ARB_make_current_read   1"

.SS "#define WGL_ARB_multisample   1"

.SS "#define WGL_ARB_pbuffer   1"

.SS "#define WGL_ARB_pixel_format   1"

.SS "#define WGL_ARB_pixel_format_float   1"

.SS "#define WGL_ARB_render_texture   1"

.SS "#define WGL_ARB_robustness_application_isolation   1"

.SS "#define WGL_ARB_robustness_share_group_isolation   1"

.SS "#define WGL_ATI_pixel_format_float   1"

.SS "#define WGL_AUX0_ARB   0x2087"

.SS "#define WGL_AUX1_ARB   0x2088"

.SS "#define WGL_AUX2_ARB   0x2089"

.SS "#define WGL_AUX3_ARB   0x208A"

.SS "#define WGL_AUX4_ARB   0x208B"

.SS "#define WGL_AUX5_ARB   0x208C"

.SS "#define WGL_AUX6_ARB   0x208D"

.SS "#define WGL_AUX7_ARB   0x208E"

.SS "#define WGL_AUX8_ARB   0x208F"

.SS "#define WGL_AUX9_ARB   0x2090"

.SS "#define WGL_AUX_BUFFERS_ARB   0x2024"

.SS "#define WGL_AUX_BUFFERS_EXT   0x2024"

.SS "#define WGL_BACK_COLOR_BUFFER_BIT_ARB   0x00000002"

.SS "#define WGL_BACK_LEFT_ARB   0x2085"

.SS "#define WGL_BACK_RIGHT_ARB   0x2086"

.SS "#define WGL_BIND_TO_TEXTURE_DEPTH_NV   0x20A3"

.SS "#define WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV   0x20A4"

.SS "#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV   0x20B1"

.SS "#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV   0x20B2"

.SS "#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV   0x20B3"

.SS "#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV   0x20B4"

.SS "#define WGL_BIND_TO_TEXTURE_RECTANGLE_RGB_NV   0x20A0"

.SS "#define WGL_BIND_TO_TEXTURE_RECTANGLE_RGBA_NV   0x20A1"

.SS "#define WGL_BIND_TO_TEXTURE_RGB_ARB   0x2070"

.SS "#define WGL_BIND_TO_TEXTURE_RGBA_ARB   0x2071"

.SS "#define WGL_BIND_TO_VIDEO_RGB_AND_DEPTH_NV   0x20C2"

.SS "#define WGL_BIND_TO_VIDEO_RGB_NV   0x20C0"

.SS "#define WGL_BIND_TO_VIDEO_RGBA_NV   0x20C1"

.SS "#define WGL_BLUE_BITS_ARB   0x2019"

.SS "#define WGL_BLUE_BITS_EXT   0x2019"

.SS "#define WGL_BLUE_SHIFT_ARB   0x201A"

.SS "#define WGL_BLUE_SHIFT_EXT   0x201A"

.SS "#define WGL_COLOR_BITS_ARB   0x2014"

.SS "#define WGL_COLOR_BITS_EXT   0x2014"

.SS "#define WGL_COLOR_SAMPLES_NV   0x20B9"

.SS "#define WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB   0x00000002"

.SS "#define WGL_CONTEXT_CORE_PROFILE_BIT_ARB   0x00000001"

.SS "#define WGL_CONTEXT_DEBUG_BIT_ARB   0x00000001"

.SS "#define WGL_CONTEXT_ES2_PROFILE_BIT_EXT   0x00000004"

.SS "#define WGL_CONTEXT_ES_PROFILE_BIT_EXT   0x00000004"

.SS "#define WGL_CONTEXT_FLAGS_ARB   0x2094"

.SS "#define WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB   0x00000002"

.SS "#define WGL_CONTEXT_LAYER_PLANE_ARB   0x2093"

.SS "#define WGL_CONTEXT_MAJOR_VERSION_ARB   0x2091"

.SS "#define WGL_CONTEXT_MINOR_VERSION_ARB   0x2092"

.SS "#define WGL_CONTEXT_PROFILE_MASK_ARB   0x9126"

.SS "#define WGL_CONTEXT_RELEASE_BEHAVIOR_ARB   0x2097"

.SS "#define WGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB   0x2098"

.SS "#define WGL_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB   0"

.SS "#define WGL_CONTEXT_RESET_ISOLATION_BIT_ARB   0x00000008"

.SS "#define WGL_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB   0x8256"

.SS "#define WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB   0x00000004"

.SS "#define WGL_COVERAGE_SAMPLES_NV   0x2042"

.SS "#define WGL_CUBE_MAP_FACE_ARB   0x207C"

.SS "#define WGL_DEPTH_BITS_ARB   0x2022"

.SS "#define WGL_DEPTH_BITS_EXT   0x2022"

.SS "#define WGL_DEPTH_BUFFER_BIT_ARB   0x00000004"

.SS "#define WGL_DEPTH_COMPONENT_NV   0x20A7"

.SS "#define WGL_DEPTH_FLOAT_EXT   0x2040"

.SS "#define WGL_DEPTH_TEXTURE_FORMAT_NV   0x20A5"

.SS "#define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D   0x2050"

.SS "#define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D   0x2051"

.SS "#define WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D   0x2052"

.SS "#define WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D   0x2053"

.SS "#define WGL_DOUBLE_BUFFER_ARB   0x2011"

.SS "#define WGL_DOUBLE_BUFFER_EXT   0x2011"

.SS "#define WGL_DRAW_TO_BITMAP_ARB   0x2002"

.SS "#define WGL_DRAW_TO_BITMAP_EXT   0x2002"

.SS "#define WGL_DRAW_TO_PBUFFER_ARB   0x202D"

.SS "#define WGL_DRAW_TO_PBUFFER_EXT   0x202D"

.SS "#define WGL_DRAW_TO_WINDOW_ARB   0x2001"

.SS "#define WGL_DRAW_TO_WINDOW_EXT   0x2001"

.SS "#define WGL_EXT_create_context_es2_profile   1"

.SS "#define WGL_EXT_create_context_es_profile   1"

.SS "#define WGL_EXT_depth_float   1"

.SS "#define WGL_EXT_display_color_table   1"

.SS "#define WGL_EXT_extensions_string   1"

.SS "#define WGL_EXT_framebuffer_sRGB   1"

.SS "#define WGL_EXT_make_current_read   1"

.SS "#define WGL_EXT_multisample   1"

.SS "#define WGL_EXT_pbuffer   1"

.SS "#define WGL_EXT_pixel_format   1"

.SS "#define WGL_EXT_pixel_format_packed_float   1"

.SS "#define WGL_EXT_swap_control   1"

.SS "#define WGL_EXT_swap_control_tear   1"

.SS "#define WGL_FLOAT_COMPONENTS_NV   0x20B0"

.SS "#define WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB   0x20A9"

.SS "#define WGL_FRAMEBUFFER_SRGB_CAPABLE_EXT   0x20A9"

.SS "#define WGL_FRONT_COLOR_BUFFER_BIT_ARB   0x00000001"

.SS "#define WGL_FRONT_LEFT_ARB   0x2083"

.SS "#define WGL_FRONT_RIGHT_ARB   0x2084"

.SS "#define WGL_FULL_ACCELERATION_ARB   0x2027"

.SS "#define WGL_FULL_ACCELERATION_EXT   0x2027"

.SS "#define WGL_GAMMA_EXCLUDE_DESKTOP_I3D   0x204F"

.SS "#define WGL_GAMMA_TABLE_SIZE_I3D   0x204E"

.SS "#define WGL_GENERIC_ACCELERATION_ARB   0x2026"

.SS "#define WGL_GENERIC_ACCELERATION_EXT   0x2026"

.SS "#define WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D   0x2049"

.SS "#define WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D   0x2048"

.SS "#define WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D   0x204C"

.SS "#define WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D   0x204A"

.SS "#define WGL_GENLOCK_SOURCE_EDGE_RISING_I3D   0x204B"

.SS "#define WGL_GENLOCK_SOURCE_EXTERNAL_FIELD_I3D   0x2046"

.SS "#define WGL_GENLOCK_SOURCE_EXTERNAL_SYNC_I3D   0x2045"

.SS "#define WGL_GENLOCK_SOURCE_EXTERNAL_TTL_I3D   0x2047"

.SS "#define WGL_GENLOCK_SOURCE_MULTIVIEW_I3D   0x2044"

.SS "#define WGL_GPU_CLOCK_AMD   0x21A4"

.SS "#define WGL_GPU_FASTEST_TARGET_GPUS_AMD   0x21A2"

.SS "#define WGL_GPU_NUM_PIPES_AMD   0x21A5"

.SS "#define WGL_GPU_NUM_RB_AMD   0x21A7"

.SS "#define WGL_GPU_NUM_SIMD_AMD   0x21A6"

.SS "#define WGL_GPU_NUM_SPI_AMD   0x21A8"

.SS "#define WGL_GPU_OPENGL_VERSION_STRING_AMD   0x1F02"

.SS "#define WGL_GPU_RAM_AMD   0x21A3"

.SS "#define WGL_GPU_RENDERER_STRING_AMD   0x1F01"

.SS "#define WGL_GPU_VENDOR_AMD   0x1F00"

.SS "#define WGL_GREEN_BITS_ARB   0x2017"

.SS "#define WGL_GREEN_BITS_EXT   0x2017"

.SS "#define WGL_GREEN_SHIFT_ARB   0x2018"

.SS "#define WGL_GREEN_SHIFT_EXT   0x2018"

.SS "#define WGL_I3D_digital_video_control   1"

.SS "#define WGL_I3D_gamma   1"

.SS "#define WGL_I3D_genlock   1"

.SS "#define WGL_I3D_image_buffer   1"

.SS "#define WGL_I3D_swap_frame_lock   1"

.SS "#define WGL_I3D_swap_frame_usage   1"

.SS "#define WGL_IMAGE_BUFFER_LOCK_I3D   0x00000002"

.SS "#define WGL_IMAGE_BUFFER_MIN_ACCESS_I3D   0x00000001"

.SS "#define WGL_LOSE_CONTEXT_ON_RESET_ARB   0x8252"

.SS "#define WGL_MAX_PBUFFER_HEIGHT_ARB   0x2030"

.SS "#define WGL_MAX_PBUFFER_HEIGHT_EXT   0x2030"

.SS "#define WGL_MAX_PBUFFER_PIXELS_ARB   0x202E"

.SS "#define WGL_MAX_PBUFFER_PIXELS_EXT   0x202E"

.SS "#define WGL_MAX_PBUFFER_WIDTH_ARB   0x202F"

.SS "#define WGL_MAX_PBUFFER_WIDTH_EXT   0x202F"

.SS "#define WGL_MIPMAP_LEVEL_ARB   0x207B"

.SS "#define WGL_MIPMAP_TEXTURE_ARB   0x2074"

.SS "#define WGL_NEED_PALETTE_ARB   0x2004"

.SS "#define WGL_NEED_PALETTE_EXT   0x2004"

.SS "#define WGL_NEED_SYSTEM_PALETTE_ARB   0x2005"

.SS "#define WGL_NEED_SYSTEM_PALETTE_EXT   0x2005"

.SS "#define WGL_NO_ACCELERATION_ARB   0x2025"

.SS "#define WGL_NO_ACCELERATION_EXT   0x2025"

.SS "#define WGL_NO_RESET_NOTIFICATION_ARB   0x8261"

.SS "#define WGL_NO_TEXTURE_ARB   0x2077"

.SS "#define WGL_NUM_VIDEO_CAPTURE_SLOTS_NV   0x20CF"

.SS "#define WGL_NUM_VIDEO_SLOTS_NV   0x20F0"

.SS "#define WGL_NUMBER_OVERLAYS_ARB   0x2008"

.SS "#define WGL_NUMBER_OVERLAYS_EXT   0x2008"

.SS "#define WGL_NUMBER_PIXEL_FORMATS_ARB   0x2000"

.SS "#define WGL_NUMBER_PIXEL_FORMATS_EXT   0x2000"

.SS "#define WGL_NUMBER_UNDERLAYS_ARB   0x2009"

.SS "#define WGL_NUMBER_UNDERLAYS_EXT   0x2009"

.SS "#define WGL_NV_copy_image   1"

.SS "#define WGL_NV_delay_before_swap   1"

.SS "#define WGL_NV_DX_interop   1"

.SS "#define WGL_NV_DX_interop2   1"

.SS "#define WGL_NV_float_buffer   1"

.SS "#define WGL_NV_gpu_affinity   1"

.SS "#define WGL_NV_multisample_coverage   1"

.SS "#define WGL_NV_present_video   1"

.SS "#define WGL_NV_render_depth_texture   1"

.SS "#define WGL_NV_render_texture_rectangle   1"

.SS "#define WGL_NV_swap_group   1"

.SS "#define WGL_NV_vertex_array_range   1"

.SS "#define WGL_NV_video_capture   1"

.SS "#define WGL_NV_video_output   1"

.SS "#define WGL_OML_sync_control   1"

.SS "#define WGL_OPTIMAL_PBUFFER_HEIGHT_EXT   0x2032"

.SS "#define WGL_OPTIMAL_PBUFFER_WIDTH_EXT   0x2031"

.SS "#define WGL_PBUFFER_HEIGHT_ARB   0x2035"

.SS "#define WGL_PBUFFER_HEIGHT_EXT   0x2035"

.SS "#define WGL_PBUFFER_LARGEST_ARB   0x2033"

.SS "#define WGL_PBUFFER_LARGEST_EXT   0x2033"

.SS "#define WGL_PBUFFER_LOST_ARB   0x2036"

.SS "#define WGL_PBUFFER_WIDTH_ARB   0x2034"

.SS "#define WGL_PBUFFER_WIDTH_EXT   0x2034"

.SS "#define WGL_PIXEL_TYPE_ARB   0x2013"

.SS "#define WGL_PIXEL_TYPE_EXT   0x2013"

.SS "#define WGL_RED_BITS_ARB   0x2015"

.SS "#define WGL_RED_BITS_EXT   0x2015"

.SS "#define WGL_RED_SHIFT_ARB   0x2016"

.SS "#define WGL_RED_SHIFT_EXT   0x2016"

.SS "#define WGL_SAMPLE_BUFFERS_3DFX   0x2060"

.SS "#define WGL_SAMPLE_BUFFERS_ARB   0x2041"

.SS "#define WGL_SAMPLE_BUFFERS_EXT   0x2041"

.SS "#define WGL_SAMPLES_3DFX   0x2061"

.SS "#define WGL_SAMPLES_ARB   0x2042"

.SS "#define WGL_SAMPLES_EXT   0x2042"

.SS "#define WGL_SHARE_ACCUM_ARB   0x200E"

.SS "#define WGL_SHARE_ACCUM_EXT   0x200E"

.SS "#define WGL_SHARE_DEPTH_ARB   0x200C"

.SS "#define WGL_SHARE_DEPTH_EXT   0x200C"

.SS "#define WGL_SHARE_STENCIL_ARB   0x200D"

.SS "#define WGL_SHARE_STENCIL_EXT   0x200D"

.SS "#define WGL_STENCIL_BITS_ARB   0x2023"

.SS "#define WGL_STENCIL_BITS_EXT   0x2023"

.SS "#define WGL_STENCIL_BUFFER_BIT_ARB   0x00000008"

.SS "#define WGL_STEREO_ARB   0x2012"

.SS "#define WGL_STEREO_EMITTER_DISABLE_3DL   0x2056"

.SS "#define WGL_STEREO_EMITTER_ENABLE_3DL   0x2055"

.SS "#define WGL_STEREO_EXT   0x2012"

.SS "#define WGL_STEREO_POLARITY_INVERT_3DL   0x2058"

.SS "#define WGL_STEREO_POLARITY_NORMAL_3DL   0x2057"

.SS "#define WGL_SUPPORT_GDI_ARB   0x200F"

.SS "#define WGL_SUPPORT_GDI_EXT   0x200F"

.SS "#define WGL_SUPPORT_OPENGL_ARB   0x2010"

.SS "#define WGL_SUPPORT_OPENGL_EXT   0x2010"

.SS "#define WGL_SWAP_COPY_ARB   0x2029"

.SS "#define WGL_SWAP_COPY_EXT   0x2029"

.SS "#define WGL_SWAP_EXCHANGE_ARB   0x2028"

.SS "#define WGL_SWAP_EXCHANGE_EXT   0x2028"

.SS "#define WGL_SWAP_LAYER_BUFFERS_ARB   0x2006"

.SS "#define WGL_SWAP_LAYER_BUFFERS_EXT   0x2006"

.SS "#define WGL_SWAP_METHOD_ARB   0x2007"

.SS "#define WGL_SWAP_METHOD_EXT   0x2007"

.SS "#define WGL_SWAP_UNDEFINED_ARB   0x202A"

.SS "#define WGL_SWAP_UNDEFINED_EXT   0x202A"

.SS "#define WGL_TEXTURE_1D_ARB   0x2079"

.SS "#define WGL_TEXTURE_2D_ARB   0x207A"

.SS "#define WGL_TEXTURE_CUBE_MAP_ARB   0x2078"

.SS "#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB   0x207E"

.SS "#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB   0x2080"

.SS "#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB   0x2082"

.SS "#define WGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB   0x207D"

.SS "#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB   0x207F"

.SS "#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB   0x2081"

.SS "#define WGL_TEXTURE_DEPTH_COMPONENT_NV   0x20A6"

.SS "#define WGL_TEXTURE_FLOAT_R_NV   0x20B5"

.SS "#define WGL_TEXTURE_FLOAT_RG_NV   0x20B6"

.SS "#define WGL_TEXTURE_FLOAT_RGB_NV   0x20B7"

.SS "#define WGL_TEXTURE_FLOAT_RGBA_NV   0x20B8"

.SS "#define WGL_TEXTURE_FORMAT_ARB   0x2072"

.SS "#define WGL_TEXTURE_RECTANGLE_NV   0x20A2"

.SS "#define WGL_TEXTURE_RGB_ARB   0x2075"

.SS "#define WGL_TEXTURE_RGBA_ARB   0x2076"

.SS "#define WGL_TEXTURE_TARGET_ARB   0x2073"

.SS "#define WGL_TRANSPARENT_ALPHA_VALUE_ARB   0x203A"

.SS "#define WGL_TRANSPARENT_ARB   0x200A"

.SS "#define WGL_TRANSPARENT_BLUE_VALUE_ARB   0x2039"

.SS "#define WGL_TRANSPARENT_EXT   0x200A"

.SS "#define WGL_TRANSPARENT_GREEN_VALUE_ARB   0x2038"

.SS "#define WGL_TRANSPARENT_INDEX_VALUE_ARB   0x203B"

.SS "#define WGL_TRANSPARENT_RED_VALUE_ARB   0x2037"

.SS "#define WGL_TRANSPARENT_VALUE_EXT   0x200B"

.SS "#define WGL_TYPE_COLORINDEX_ARB   0x202C"

.SS "#define WGL_TYPE_COLORINDEX_EXT   0x202C"

.SS "#define WGL_TYPE_RGBA_ARB   0x202B"

.SS "#define WGL_TYPE_RGBA_EXT   0x202B"

.SS "#define WGL_TYPE_RGBA_FLOAT_ARB   0x21A0"

.SS "#define WGL_TYPE_RGBA_FLOAT_ATI   0x21A0"

.SS "#define WGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT   0x20A8"

.SS "#define WGL_UNIQUE_ID_NV   0x20CE"

.SS "#define WGL_VIDEO_OUT_ALPHA_NV   0x20C4"

.SS "#define WGL_VIDEO_OUT_COLOR_AND_ALPHA_NV   0x20C6"

.SS "#define WGL_VIDEO_OUT_COLOR_AND_DEPTH_NV   0x20C7"

.SS "#define WGL_VIDEO_OUT_COLOR_NV   0x20C3"

.SS "#define WGL_VIDEO_OUT_DEPTH_NV   0x20C5"

.SS "#define WGL_VIDEO_OUT_FIELD_1   0x20C9"

.SS "#define WGL_VIDEO_OUT_FIELD_2   0x20CA"

.SS "#define WGL_VIDEO_OUT_FRAME   0x20C8"

.SS "#define WGL_VIDEO_OUT_STACKED_FIELDS_1_2   0x20CB"

.SS "#define WGL_VIDEO_OUT_STACKED_FIELDS_2_1   0x20CC"

.SS "#define WGL_WGLEXT_VERSION   20140810"

.SH "Typedef Documentation"
.PP 
.SS "typedef \fBvoid\fP*(WINAPI * PFNWGLALLOCATEMEMORYNVPROC) (\fBGLsizei\fP \fBsize\fP, \fBGLfloat\fP readfreq, \fBGLfloat\fP writefreq, \fBGLfloat\fP priority)"

.SS "typedef BOOL(WINAPI * PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC) (HDC hDC, const HANDLE *pEvent, const LPVOID *pAddress, const DWORD *pSize, UINT \fBcount\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLBEGINFRAMETRACKINGI3DPROC) (\fBvoid\fP)"

.SS "typedef \fBGLboolean\fP(WINAPI * PFNWGLBINDDISPLAYCOLORTABLEEXTPROC) (\fBGLushort\fP \fBid\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLBINDSWAPBARRIERNVPROC) (\fBGLuint\fP group, \fBGLuint\fP barrier)"

.SS "typedef BOOL(WINAPI * PFNWGLBINDTEXIMAGEARBPROC) (HPBUFFERARB hPbuffer, int iBuffer)"

.SS "typedef BOOL(WINAPI * PFNWGLBINDVIDEOCAPTUREDEVICENVPROC) (UINT uVideoSlot, HVIDEOINPUTDEVICENV hDevice)"

.SS "typedef BOOL(WINAPI * PFNWGLBINDVIDEODEVICENVPROC) (HDC hDC, unsigned int uVideoSlot, HVIDEOOUTPUTDEVICENV hVideoDevice, const int *piAttribList)"

.SS "typedef BOOL(WINAPI * PFNWGLBINDVIDEOIMAGENVPROC) (HPVIDEODEV hVideoDevice, HPBUFFERARB hPbuffer, int iVideoBuffer)"

.SS "typedef VOID(WINAPI * PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC) (HGLRC dstCtx, \fBGLint\fP \fBsrcX0\fP, \fBGLint\fP \fBsrcY0\fP, \fBGLint\fP \fBsrcX1\fP, \fBGLint\fP \fBsrcY1\fP, \fBGLint\fP \fBdstX0\fP, \fBGLint\fP \fBdstY0\fP, \fBGLint\fP \fBdstX1\fP, \fBGLint\fP \fBdstY1\fP, \fBGLbitfield\fP \fBmask\fP, \fBGLenum\fP \fBfilter\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLCHOOSEPIXELFORMATARBPROC) (HDC hdc, const int *piAttribIList, const FLOAT *pfAttribFList, UINT nMaxFormats, int *piFormats, UINT *nNumFormats)"

.SS "typedef BOOL(WINAPI * PFNWGLCHOOSEPIXELFORMATEXTPROC) (HDC hdc, const int *piAttribIList, const FLOAT *pfAttribFList, UINT nMaxFormats, int *piFormats, UINT *nNumFormats)"

.SS "typedef BOOL(WINAPI * PFNWGLCOPYIMAGESUBDATANVPROC) (HGLRC hSrcRC, \fBGLuint\fP srcName, \fBGLenum\fP \fBsrcTarget\fP, \fBGLint\fP \fBsrcLevel\fP, \fBGLint\fP \fBsrcX\fP, \fBGLint\fP \fBsrcY\fP, \fBGLint\fP \fBsrcZ\fP, HGLRC hDstRC, \fBGLuint\fP \fBdstName\fP, \fBGLenum\fP \fBdstTarget\fP, \fBGLint\fP \fBdstLevel\fP, \fBGLint\fP \fBdstX\fP, \fBGLint\fP \fBdstY\fP, \fBGLint\fP \fBdstZ\fP, \fBGLsizei\fP \fBwidth\fP, \fBGLsizei\fP \fBheight\fP, \fBGLsizei\fP \fBdepth\fP)"

.SS "typedef HDC(WINAPI * PFNWGLCREATEAFFINITYDCNVPROC) (const HGPUNV *phGpuList)"

.SS "typedef HGLRC(WINAPI * PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC) (UINT \fBid\fP)"

.SS "typedef HGLRC(WINAPI * PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC) (UINT \fBid\fP, HGLRC hShareContext, const int *attribList)"

.SS "typedef HANDLE(WINAPI * PFNWGLCREATEBUFFERREGIONARBPROC) (HDC hDC, int iLayerPlane, UINT uType)"

.SS "typedef HGLRC(WINAPI * PFNWGLCREATECONTEXTATTRIBSARBPROC) (HDC hDC, HGLRC hShareContext, const int *attribList)"

.SS "typedef \fBGLboolean\fP(WINAPI * PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC) (\fBGLushort\fP \fBid\fP)"

.SS "typedef LPVOID(WINAPI * PFNWGLCREATEIMAGEBUFFERI3DPROC) (HDC hDC, DWORD dwSize, UINT uFlags)"

.SS "typedef HPBUFFERARB(WINAPI * PFNWGLCREATEPBUFFERARBPROC) (HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int *piAttribList)"

.SS "typedef HPBUFFEREXT(WINAPI * PFNWGLCREATEPBUFFEREXTPROC) (HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int *piAttribList)"

.SS "typedef BOOL(WINAPI * PFNWGLDELAYBEFORESWAPNVPROC) (HDC hDC, \fBGLfloat\fP seconds)"

.SS "typedef BOOL(WINAPI * PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC) (HGLRC hglrc)"

.SS "typedef VOID(WINAPI * PFNWGLDELETEBUFFERREGIONARBPROC) (HANDLE hRegion)"

.SS "typedef BOOL(WINAPI * PFNWGLDELETEDCNVPROC) (HDC hdc)"

.SS "typedef VOID(WINAPI * PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC) (\fBGLushort\fP \fBid\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLDESTROYIMAGEBUFFERI3DPROC) (HDC hDC, LPVOID pAddress)"

.SS "typedef BOOL(WINAPI * PFNWGLDESTROYPBUFFERARBPROC) (HPBUFFERARB hPbuffer)"

.SS "typedef BOOL(WINAPI * PFNWGLDESTROYPBUFFEREXTPROC) (HPBUFFEREXT hPbuffer)"

.SS "typedef BOOL(WINAPI * PFNWGLDISABLEFRAMELOCKI3DPROC) (\fBvoid\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLDISABLEGENLOCKI3DPROC) (HDC hDC)"

.SS "typedef BOOL(WINAPI * PFNWGLDXCLOSEDEVICENVPROC) (HANDLE hDevice)"

.SS "typedef BOOL(WINAPI * PFNWGLDXLOCKOBJECTSNVPROC) (HANDLE hDevice, \fBGLint\fP \fBcount\fP, HANDLE *hObjects)"

.SS "typedef BOOL(WINAPI * PFNWGLDXOBJECTACCESSNVPROC) (HANDLE hObject, \fBGLenum\fP \fBaccess\fP)"

.SS "typedef HANDLE(WINAPI * PFNWGLDXOPENDEVICENVPROC) (\fBvoid\fP *dxDevice)"

.SS "typedef HANDLE(WINAPI * PFNWGLDXREGISTEROBJECTNVPROC) (HANDLE hDevice, \fBvoid\fP *dxObject, \fBGLuint\fP \fBname\fP, \fBGLenum\fP \fBtype\fP, \fBGLenum\fP \fBaccess\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLDXSETRESOURCESHAREHANDLENVPROC) (\fBvoid\fP *dxObject, HANDLE shareHandle)"

.SS "typedef BOOL(WINAPI * PFNWGLDXUNLOCKOBJECTSNVPROC) (HANDLE hDevice, \fBGLint\fP \fBcount\fP, HANDLE *hObjects)"

.SS "typedef BOOL(WINAPI * PFNWGLDXUNREGISTEROBJECTNVPROC) (HANDLE hDevice, HANDLE hObject)"

.SS "typedef BOOL(WINAPI * PFNWGLENABLEFRAMELOCKI3DPROC) (\fBvoid\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLENABLEGENLOCKI3DPROC) (HDC hDC)"

.SS "typedef BOOL(WINAPI * PFNWGLENDFRAMETRACKINGI3DPROC) (\fBvoid\fP)"

.SS "typedef UINT(WINAPI * PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC) (HDC hDc, HVIDEOINPUTDEVICENV *phDeviceList)"

.SS "typedef int(WINAPI * PFNWGLENUMERATEVIDEODEVICESNVPROC) (HDC hDC, HVIDEOOUTPUTDEVICENV *phDeviceList)"

.SS "typedef BOOL(WINAPI * PFNWGLENUMGPUDEVICESNVPROC) (HGPUNV hGpu, UINT iDeviceIndex, \fBPGPU_DEVICE\fP lpGpuDevice)"

.SS "typedef BOOL(WINAPI * PFNWGLENUMGPUSFROMAFFINITYDCNVPROC) (HDC hAffinityDC, UINT iGpuIndex, HGPUNV *hGpu)"

.SS "typedef BOOL(WINAPI * PFNWGLENUMGPUSNVPROC) (UINT iGpuIndex, HGPUNV *phGpu)"

.SS "typedef \fBvoid\fP(WINAPI * PFNWGLFREEMEMORYNVPROC) (\fBvoid\fP *\fBpointer\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLGENLOCKSAMPLERATEI3DPROC) (HDC hDC, UINT uRate)"

.SS "typedef BOOL(WINAPI * PFNWGLGENLOCKSOURCEDELAYI3DPROC) (HDC hDC, UINT uDelay)"

.SS "typedef BOOL(WINAPI * PFNWGLGENLOCKSOURCEEDGEI3DPROC) (HDC hDC, UINT uEdge)"

.SS "typedef BOOL(WINAPI * PFNWGLGENLOCKSOURCEI3DPROC) (HDC hDC, UINT uSource)"

.SS "typedef UINT(WINAPI * PFNWGLGETCONTEXTGPUIDAMDPROC) (HGLRC hglrc)"

.SS "typedef HGLRC(WINAPI * PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC) (\fBvoid\fP)"

.SS "typedef HDC(WINAPI * PFNWGLGETCURRENTREADDCARBPROC) (\fBvoid\fP)"

.SS "typedef HDC(WINAPI * PFNWGLGETCURRENTREADDCEXTPROC) (\fBvoid\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC) (HDC hDC, int iAttribute, int *piValue)"

.SS "typedef const char*(WINAPI * PFNWGLGETEXTENSIONSSTRINGARBPROC) (HDC hdc)"

.SS "typedef const char*(WINAPI * PFNWGLGETEXTENSIONSSTRINGEXTPROC) (\fBvoid\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLGETFRAMEUSAGEI3DPROC) (float *pUsage)"

.SS "typedef BOOL(WINAPI * PFNWGLGETGAMMATABLEI3DPROC) (HDC hDC, int iEntries, USHORT *puRed, USHORT *puGreen, USHORT *puBlue)"

.SS "typedef BOOL(WINAPI * PFNWGLGETGAMMATABLEPARAMETERSI3DPROC) (HDC hDC, int iAttribute, int *piValue)"

.SS "typedef BOOL(WINAPI * PFNWGLGETGENLOCKSAMPLERATEI3DPROC) (HDC hDC, UINT *uRate)"

.SS "typedef BOOL(WINAPI * PFNWGLGETGENLOCKSOURCEDELAYI3DPROC) (HDC hDC, UINT *uDelay)"

.SS "typedef BOOL(WINAPI * PFNWGLGETGENLOCKSOURCEEDGEI3DPROC) (HDC hDC, UINT *uEdge)"

.SS "typedef BOOL(WINAPI * PFNWGLGETGENLOCKSOURCEI3DPROC) (HDC hDC, UINT *uSource)"

.SS "typedef UINT(WINAPI * PFNWGLGETGPUIDSAMDPROC) (UINT \fBmaxCount\fP, UINT *\fBids\fP)"

.SS "typedef INT(WINAPI * PFNWGLGETGPUINFOAMDPROC) (UINT \fBid\fP, int property, \fBGLenum\fP dataType, UINT \fBsize\fP, \fBvoid\fP *\fBdata\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLGETMSCRATEOMLPROC) (HDC hdc, INT32 *numerator, INT32 *denominator)"

.SS "typedef HDC(WINAPI * PFNWGLGETPBUFFERDCARBPROC) (HPBUFFERARB hPbuffer)"

.SS "typedef HDC(WINAPI * PFNWGLGETPBUFFERDCEXTPROC) (HPBUFFEREXT hPbuffer)"

.SS "typedef BOOL(WINAPI * PFNWGLGETPIXELFORMATATTRIBFVARBPROC) (HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int *piAttributes, FLOAT *pfValues)"

.SS "typedef BOOL(WINAPI * PFNWGLGETPIXELFORMATATTRIBFVEXTPROC) (HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int *piAttributes, FLOAT *pfValues)"

.SS "typedef BOOL(WINAPI * PFNWGLGETPIXELFORMATATTRIBIVARBPROC) (HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int *piAttributes, int *piValues)"

.SS "typedef BOOL(WINAPI * PFNWGLGETPIXELFORMATATTRIBIVEXTPROC) (HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int *piAttributes, int *piValues)"

.SS "typedef int(WINAPI * PFNWGLGETSWAPINTERVALEXTPROC) (\fBvoid\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLGETSYNCVALUESOMLPROC) (HDC hdc, INT64 *ust, INT64 *msc, INT64 *sbc)"

.SS "typedef BOOL(WINAPI * PFNWGLGETVIDEODEVICENVPROC) (HDC hDC, int numDevices, HPVIDEODEV *hVideoDevice)"

.SS "typedef BOOL(WINAPI * PFNWGLGETVIDEOINFONVPROC) (HPVIDEODEV hpVideoDevice, unsigned long *pulCounterOutputPbuffer, unsigned long *pulCounterOutputVideo)"

.SS "typedef BOOL(WINAPI * PFNWGLISENABLEDFRAMELOCKI3DPROC) (BOOL *pFlag)"

.SS "typedef BOOL(WINAPI * PFNWGLISENABLEDGENLOCKI3DPROC) (HDC hDC, BOOL *pFlag)"

.SS "typedef BOOL(WINAPI * PFNWGLJOINSWAPGROUPNVPROC) (HDC hDC, \fBGLuint\fP group)"

.SS "typedef \fBGLboolean\fP(WINAPI * PFNWGLLOADDISPLAYCOLORTABLEEXTPROC) (const \fBGLushort\fP *table, \fBGLuint\fP \fBlength\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC) (HDC hDc, HVIDEOINPUTDEVICENV hDevice)"

.SS "typedef BOOL(WINAPI * PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC) (HGLRC hglrc)"

.SS "typedef BOOL(WINAPI * PFNWGLMAKECONTEXTCURRENTARBPROC) (HDC hDrawDC, HDC hReadDC, HGLRC hglrc)"

.SS "typedef BOOL(WINAPI * PFNWGLMAKECONTEXTCURRENTEXTPROC) (HDC hDrawDC, HDC hReadDC, HGLRC hglrc)"

.SS "typedef BOOL(WINAPI * PFNWGLQUERYCURRENTCONTEXTNVPROC) (int iAttribute, int *piValue)"

.SS "typedef BOOL(WINAPI * PFNWGLQUERYFRAMECOUNTNVPROC) (HDC hDC, \fBGLuint\fP *\fBcount\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLQUERYFRAMELOCKMASTERI3DPROC) (BOOL *pFlag)"

.SS "typedef BOOL(WINAPI * PFNWGLQUERYFRAMETRACKINGI3DPROC) (DWORD *pFrameCount, DWORD *pMissedFrames, float *pLastMissedUsage)"

.SS "typedef BOOL(WINAPI * PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC) (HDC hDC, UINT *uMaxLineDelay, UINT *uMaxPixelDelay)"

.SS "typedef BOOL(WINAPI * PFNWGLQUERYMAXSWAPGROUPSNVPROC) (HDC hDC, \fBGLuint\fP *maxGroups, \fBGLuint\fP *maxBarriers)"

.SS "typedef BOOL(WINAPI * PFNWGLQUERYPBUFFERARBPROC) (HPBUFFERARB hPbuffer, int iAttribute, int *piValue)"

.SS "typedef BOOL(WINAPI * PFNWGLQUERYPBUFFEREXTPROC) (HPBUFFEREXT hPbuffer, int iAttribute, int *piValue)"

.SS "typedef BOOL(WINAPI * PFNWGLQUERYSWAPGROUPNVPROC) (HDC hDC, \fBGLuint\fP *group, \fBGLuint\fP *barrier)"

.SS "typedef BOOL(WINAPI * PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC) (HDC hDc, HVIDEOINPUTDEVICENV hDevice, int iAttribute, int *piValue)"

.SS "typedef BOOL(WINAPI * PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC) (HDC hDC, const LPVOID *pAddress, UINT \fBcount\fP)"

.SS "typedef int(WINAPI * PFNWGLRELEASEPBUFFERDCARBPROC) (HPBUFFERARB hPbuffer, HDC hDC)"

.SS "typedef int(WINAPI * PFNWGLRELEASEPBUFFERDCEXTPROC) (HPBUFFEREXT hPbuffer, HDC hDC)"

.SS "typedef BOOL(WINAPI * PFNWGLRELEASETEXIMAGEARBPROC) (HPBUFFERARB hPbuffer, int iBuffer)"

.SS "typedef BOOL(WINAPI * PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC) (HDC hDc, HVIDEOINPUTDEVICENV hDevice)"

.SS "typedef BOOL(WINAPI * PFNWGLRELEASEVIDEODEVICENVPROC) (HPVIDEODEV hVideoDevice)"

.SS "typedef BOOL(WINAPI * PFNWGLRELEASEVIDEOIMAGENVPROC) (HPBUFFERARB hPbuffer, int iVideoBuffer)"

.SS "typedef BOOL(WINAPI * PFNWGLRESETFRAMECOUNTNVPROC) (HDC hDC)"

.SS "typedef BOOL(WINAPI * PFNWGLRESTOREBUFFERREGIONARBPROC) (HANDLE hRegion, int \fBx\fP, int \fBy\fP, int \fBwidth\fP, int \fBheight\fP, int xSrc, int ySrc)"

.SS "typedef BOOL(WINAPI * PFNWGLSAVEBUFFERREGIONARBPROC) (HANDLE hRegion, int \fBx\fP, int \fBy\fP, int \fBwidth\fP, int \fBheight\fP)"

.SS "typedef BOOL(WINAPI * PFNWGLSENDPBUFFERTOVIDEONVPROC) (HPBUFFERARB hPbuffer, int iBufferType, unsigned long *pulCounterPbuffer, BOOL bBlock)"

.SS "typedef BOOL(WINAPI * PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC) (HDC hDC, int iAttribute, const int *piValue)"

.SS "typedef BOOL(WINAPI * PFNWGLSETGAMMATABLEI3DPROC) (HDC hDC, int iEntries, const USHORT *puRed, const USHORT *puGreen, const USHORT *puBlue)"

.SS "typedef BOOL(WINAPI * PFNWGLSETGAMMATABLEPARAMETERSI3DPROC) (HDC hDC, int iAttribute, const int *piValue)"

.SS "typedef BOOL(WINAPI * PFNWGLSETPBUFFERATTRIBARBPROC) (HPBUFFERARB hPbuffer, const int *piAttribList)"

.SS "typedef BOOL(WINAPI * PFNWGLSETSTEREOEMITTERSTATE3DLPROC) (HDC hDC, UINT uState)"

.SS "typedef INT64(WINAPI * PFNWGLSWAPBUFFERSMSCOMLPROC) (HDC hdc, INT64 target_msc, INT64 \fBdivisor\fP, INT64 remainder)"

.SS "typedef BOOL(WINAPI * PFNWGLSWAPINTERVALEXTPROC) (int interval)"

.SS "typedef INT64(WINAPI * PFNWGLSWAPLAYERBUFFERSMSCOMLPROC) (HDC hdc, int fuPlanes, INT64 target_msc, INT64 \fBdivisor\fP, INT64 remainder)"

.SS "typedef BOOL(WINAPI * PFNWGLWAITFORMSCOMLPROC) (HDC hdc, INT64 target_msc, INT64 \fBdivisor\fP, INT64 remainder, INT64 *ust, INT64 *msc, INT64 *sbc)"

.SS "typedef BOOL(WINAPI * PFNWGLWAITFORSBCOMLPROC) (HDC hdc, INT64 target_sbc, INT64 *ust, INT64 *msc, INT64 *sbc)"

.SS "typedef struct \fB_GPU_DEVICE\fP* \fBPGPU_DEVICE\fP"

.SH "Function Documentation"
.PP 
.SS "DECLARE_HANDLE (HPBUFFERARB)"

.SS "DECLARE_HANDLE (HPBUFFEREXT)"

.SS "DECLARE_HANDLE (HGPUNV)"

.SS "DECLARE_HANDLE (HVIDEOOUTPUTDEVICENV)"

.SS "DECLARE_HANDLE (HVIDEOINPUTDEVICENV)"

.SS "DECLARE_HANDLE (HPVIDEODEV)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Killer Engine from the source code\&.
